ing-bank/lion

- packages/form/package.json
- packages/form/src/LionForm.js
- packages/form/test/lion-form.test.js
closes https://github.com/ing-bank/lion/issues/42
> fix(form): native submit event should not trigger an error

- packages/input-iban/src/formatters.js
- packages/input-iban/test/formatters.test.js
This was extracted from this MR https://github.com/ing-bank/lion/pull/15
'lion-input-iban' error occurs when field is cleared and then focus is changed to anything else. After that happen user cannot put anything into the field because everything is removed.
> fix(input-iban): allow formatting empty IBAN model values

- packages/core/src/LionLitElement.js
- packages/input-datepicker/package.json
- packages/input-datepicker/src/LionInputDatepicker.js
- packages/input-datepicker/test/lion-input-datepicker.test.js
Currently the button in the datepicker has a side effect. When the datepicker is within a form it causes the form submission unintentionally.
> fix(input-datepicker): prevent button from submitting forms

- packages/ajax/package.json
- packages/button/package.json
- packages/calendar/package.json
- packages/checkbox-group/package.json
- packages/checkbox/package.json
- packages/choice-input/package.json
- packages/core/package.json
- packages/field/package.json
- packages/fieldset/package.json
- packages/form-system/package.json
- packages/form/package.json
- packages/icon/package.json
- packages/input-amount/package.json
- packages/input-date/package.json
- packages/input-datepicker/package.json
- packages/input-email/package.json
- packages/input-iban/package.json
- packages/input/package.json
- packages/localize/package.json
- packages/overlays/package.json
- packages/popup/package.json
- packages/radio-group/package.json
- packages/radio/package.json
- packages/select/package.json
- packages/steps/package.json
- packages/textarea/package.json
- packages/tooltip/package.json
- packages/validate/package.json
- yarn.lock
I found 2 issues in our production dependencies which makes them non-flat:
1. input-datepicker somehow uses an old localize version, probably due to a mistake during merging/rebasing
2. I forgot to update @open-wc/testing in all subpackages, which breaks legacy karma setup
> Dedupe dependencies

- packages/localize/src/LocalizeManager.js
- packages/localize/test/LocalizeManager.test.js
- yarn.lock
Add throwing an exception for missing namespace in localization key instead of failing with getting "Cannot call method 'split' of undefined".
> Add throwing an exception for missing namespace

- packages/field/src/LionField.js
- packages/field/test/lion-field.test.js
As explained [here](https://github.com/ing-bank/lion/issues/22) changing the order of `ValidationMixin` and `FormatMixin` fixed the problem.
The `InteractionStateMixin` has to be done after the `FormatMixin` otherwise the field(set)s will falsy be set to `dirty`.
> fix(field): formats value after validation update

- packages/steps/src/LionStep.js
- packages/steps/src/LionSteps.js
- packages/steps/test/lion-step.test.js
- packages/steps/test/lion-steps.test.js
Previous implementation used .children to get steps which is not going to work in cases when there are elements inside \<lion-steps\> which are not actually \<lion-step\>.
Added getter returns a list of elements inside the default slot which have to be \<lion-step\> or possibly it's extensions.
> [steps] Allow extensions to introduce new non-default slots

- packages/ajax/package.json
- yarn.lock
I received a ["high severity" security vulnerability](https://nvd.nist.gov/vuln/detail/CVE-2019-10742) alert for `axios` today:
Fixed in [axios 0.18.1 as well](https://github.com/axios/axios/commits/v0.18.1).
So I updated it in `bundled-es-modules` and now time to update it here.
> fix(ajax): update to axios with security vularability fix

- packages/calendar/src/LionCalendar.js
- packages/calendar/test/lion-calendar.test.js
The test is failing here https://circleci.com/gh/ing-bank/lion/488 because we have month day 4 disabled in that test and today is June 4, this causes a side effect where `centralDate` is not initialised from `selectedDate`. This side effect is a bug on its own and I'm fixing it here.
> fix(calendar): init centralDate from selectedDate when today is disabled

- .editorconfig
- assets/.editorconfig
- package.json
- packages/field/docs/CustomFieldsTutorial.md
- packages/select/README.md
- Fixes linting scripts for windows (fixes #31)
- Fixes a problem with prettier I had where double quotes are needed on Windows, 
- Uses .gitignore now instead of us needing to maintain the glob pattern ourselves :) (though exclude for assets folder was still necessary)
- Checks markdown against .editorconfig as well now.
> Fix linting scripts

- packages/button/src/LionButton.js
- packages/button/test/lion-button.test.js
This is a custom implementation to make the active state visually noticeable when Enter or Space are used to trigger click on it.
> fix(button): indicate visually the active state on enter/space

- packages/input-datepicker/src/LionInputDatepicker.js
- packages/input-datepicker/stories/index.stories.js
- packages/input-datepicker/test/lion-input-datepicker.test.js
- packages/input/src/LionInput.js
Fixes https://github.com/ing-bank/lion/issues/92
> fix(input-datepicker): disable invoker when readonly

- package.json
- scripts/yarn-lock-scan.js
This checks for lockfiles generated using a commonly used product in companies that do dependency resolution through a proxy rather than directly from yarn or npm official registry. Such a lockfile would be unusable for users without access to this domain.
> Prevent users from committing lockfiles with invalid resolved source

- packages/overlays/docs/LocalOverlayController.md
- packages/overlays/docs/LocalOverlayPositioning.md
- packages/overlays/src/LocalOverlayController.js
- packages/overlays/test/LocalOverlayController.test.js
I noticed a small bug, when for example updating a modifier while your viewport is pushing on the popper element already, it will not position correctly when you change this modifier.
This fixes it.
> Fix update popper config method

- packages/icon/stories/index.stories.js
My expectation would be:
```html
// mind the loaderSvg
<lion-icon
class="icon"
.svg=${until(import('./icons/bugs/bug12.svg.js').then(e => e.default), loaderSvg)}
aria-label="Striped beatle"
></lion-icon>
```
But we have smth that does not make much sense - renreding string instead if SVG within an icon:
```html
// mind the string 'Loading...'
<lion-icon
class="icon"
.svg=${until(import('./icons/bugs/bug12.svg.js').then(e => e.default), 'Loading...')}
aria-label="Striped beatle"
></lion-icon>
```
Also this story is currently broken due to recent changes in the icon.
I think this is better to remove the story for now from our storybook and contribute a proper and working one later.
PS: if you need a string "Loading..." during loading, the `until` should wrap the entire `lion-icon` element, …
> chore(icon): remove misleading story

- packages/field/src/FormatMixin.js
- packages/field/test/FormatMixin.test.js
- packages/field/test/lion-field.test.js
fixes https://github.com/ing-bank/lion/issues/94
- See for explanation: https://github.com/ing-bank/lion/pull/132/files#diff-8a0f76e26a132ed6bb832fc7ff0518c8R202
- Note that we discriminate two flows: https://github.com/ing-bank/lion/pull/132/files#diff-8a0f76e26a132ed6bb832fc7ff0518c8R11
- `__preventDownwardsSync ` has been renamed to `__isHandlingUserInput `
- other doc changes are cosmetic (indenting)
> fix(field): format conditionally on user input only

- packages/localize/src/LocalizeManager.js
- packages/localize/src/localize.js
- packages/localize/test/LocalizeManager.test.js
- packages/localize/test/localize.test.js
I had to also fix another not related bug when `localeChanged` event fires multiple times with no real changes. That was necessary because the mutation observer is called multiple times for the same attribute change for some reason, like if you change the attribute it is called 5 times for it 🤷‍♂
> Observe <html lang> attribute

- packages/button/src/LionButton.js
- packages/button/test/lion-button.test.js
Quite some fixes for the mechanism of redispatching the click event of the button.
Most important fixes are related to the creation of the new click event:
1. It is created with properties from the original event.
2. We patch the `.target` property of it to fix #89 (and it suddenly does not break integration with forms).
> [button] Fix redispatching of click event

- packages/field/src/InteractionStateMixin.js
- packages/field/src/LionField.js
- packages/field/test/InteractionStateMixin.test.js
- requirement 2 for Rich Select
- let's merge it all to develop and then release
=> has 4 commits
- chore(field): improve InteractionStateMixin tests
- fix(field): move FocusMixin out of InteractionStateMixin
- fix(field): remove CssClassMixin from InteractionStateMixin
- fix(field): make InteractionState leaveEvent protected
probably easier to review them individually
> fix(field): remove CssClassMixin from InteractionStateMixin

- packages/localize/src/LocalizeManager.js
- packages/localize/src/localize.js
- packages/localize/test/LocalizeManager.test.js
- packages/localize/test/localize.test.js
We need this to support multiple scenarios:
1. The apps where some components were translated to English, but NOT YET to other languages the app needs to support, so that the app continues to work with some parts still in English (now it throws and breaks which is not what most people would like to see)
2. Fix [this bug](https://github.com/ing-bank/lion/issues/152) which breaks Google Chrome translate
So this is both a new feature and a bug fix :P
For people who don't like such a default I implemented it as a configurable option. They will be able to opt-out from this behavior if needed, or change the default (currently 'en-GB') by changing the singleton using `setLocalize`.
> Support fallback locale

- packages/input/src/LionInput.js
- packages/input/test/lion-input.test.js
Make step attribute work:
```
<ing-input
step="0.01"
type="number">
<div slot="suffix">%</div>
</ing-input>
```
> [input] Delegate "step" attribute

- packages/field/index.js
- packages/field/src/FormControlMixin.js
- packages/field/src/FormRegisteringMixin.js
- packages/field/src/FormRegistrarMixin.js
- packages/field/src/formRegistrarManager.js
- packages/field/test/FormControlMixin.test.js
- packages/field/test/FormRegistrationMixins.test.js
- packages/fieldset/src/LionFieldset.js
- packages/fieldset/test/lion-fieldset.test.js
This introduces an "update" to the registration system
It is now 2 way... 
1. the form (Registrar) Element which fires an even on the body when it is ready to accepts registrations
2. the field (Registering) Element which waits for the body event and then fires it's registration
The change is needed as ShadyDom can only catch events once fully rendered... e.g. the child needs to wait until it's parent is ready... 
it is implemented via 2 mixins
1. FormRegistrarMixin
2. FormRegisteringMixin
> fix(field): make sure RegistrationSystem works well with ShadyDom

- packages/overlays/src/LocalOverlayController.js
- packages/overlays/test/LocalOverlayController.test.js
https://github.com/FezVrasta/popper.js#dist-targets
I'm under the impression we should use ESM, when reviewing please double check my assumption ;). Works in IE11 as far as I can tell
> fix(overlays): fix popper for IE11 by using esm dist target

- packages/ajax/README.md
- packages/button/README.md
- packages/calendar/README.md
- packages/checkbox-group/README.md
- packages/checkbox/README.md
- packages/choice-input/README.md
- packages/core/README.md
- packages/field/README.md
- packages/fieldset/README.md
- packages/form-system/README.md
- packages/form/README.md
- packages/icon/README.md
- packages/input-amount/README.md
- packages/input-date/README.md
- packages/input-email/README.md
- packages/input-iban/README.md
- packages/input/README.md
- packages/localize/README.md
- packages/overlays/README.md
- packages/popup/README.md
- packages/radio-group/README.md
- packages/radio/README.md
- packages/select/README.md
- packages/steps/README.md
- packages/textarea/README.md
- packages/tooltip/README.md
- packages/validate/README.md
- scripts/insert-header.js
Every time you work on a Markdown file, prettier changes this
```
- [//]: # (AUTO INSERT HEADER PREPUBLISH)
+ [//]: # 'AUTO INSERT HEADER PREPUBLISH'
```
One day someone will accidentally commit this and our `scripts/insert-header.js` will stop working for it. I decided to fix it everywhere to prevent potential issues and confusing side effects of prettier formatting.
> Fix prepublish pattern format

- packages/textarea/src/LionTextarea.js
- packages/textarea/test/lion-textarea.test.js
Hey guys, I'm hoping not being a bother :)
I was taking a look at #165 and I've seen that the autosize library applies a resize horizontal style inline if the textarea element doesn't disable it first:
```
const style = window.getComputedStyle(ta, null);
if (style.resize === 'vertical') {
ta.style.resize = 'none';
} else if (style.resize === 'both') {
ta.style.resize = 'horizontal';
}
```
I thought that applying the resize CSS property as none inline was a bad thing, so I've added it on the slotted ` .form-control` and I've needed to move the autosize call to the firstUpdate lifecycle hook to make sure the styles were applied before calling the library.
I've could have kept it on the connectedCallback and awaited the updateComplete but it looked too noisy for me.
> [textarea] Disable user resize behavior

- packages/button/package.json
- packages/button/src/LionButton.js
- packages/core/index.js
- packages/core/src/DisabledMixin.js
- packages/core/src/DisabledWithTabIndexMixin.js
- packages/core/test/DisabledMixin.test.js
- packages/core/test/DisabledWithTabIndexMixin.test.js
this is hopefully the last requirement for select 🙈 💪 
- add a DisabledMixin and DisabledWithTabIndexMixin that can reliably manage disabled and tabindex (e.g. user can change in between the tabindex (but it will not be "reflected" e.g. disabled will always have tabindex -1) and after disabled gets "revoked" it goes to the last set state and not the original one)
- use that DisabledWithTabIndexMixin in Button
- add before/after template for button (which we will then use/override in the select invoker)
- reduce the stylings of the Button to be very minimalist so we can actually extend them where needed
> feat(button): reduce to minimal css; use DisabledWithTabIndexMixin

- packages/option/README.md
- packages/option/index.js
- packages/option/lion-option.js
- packages/option/package.json
- packages/option/src/LionOption.js
- packages/option/stories/index.stories.js
- packages/option/test/lion-option.test.js
- packages/select-rich/README.md
- packages/select-rich/lion-options.js
- packages/select-rich/lion-select-invoker.js
- packages/select-rich/lion-select-rich.js
- packages/select-rich/package.json
- packages/select-rich/src/LionOptions.js
- packages/select-rich/src/LionSelectInvoker.js
- packages/select-rich/src/LionSelectRich.js
- packages/select-rich/src/differentKeyNamesShimIE.js
- packages/select-rich/stories/index.stories.js
- packages/select-rich/test/keyboardEventShimIE.js
- packages/select-rich/test/lion-options.test.js
- packages/select-rich/test/lion-select-invoker.test.js
- packages/select-rich/test/lion-select-rich-interaction.test.js
- packages/select-rich/test/lion-select-rich.test.js
- stories/index.stories.js
has multiple requirements that need to be met before this can be considered
Until Requirements are met this will remain a draft
- a lot of stuff already works
- lots and lots of tests
=> put here to extract/discuss specifics things that should be extracted before merging this
> feat: add select-rich

- packages/textarea/src/LionTextarea.js
Fixes #203 
I've seen this behavior before, unfortunately, I've misled myself to the thought that it was working.
On Edge, on the `connnectedCalback`, when the lion-textarea tries to apply the `autosize` and `setTextareaMaxHeight`, the `inputElement` isn't rendered yet, and it creates this bug since both functions need the properties related to the rendered state of the element.
I've tried to wait for the `slotchange` event on the `firstUpdated` but the element is only going to be rendered on the next update so it needs to await the `updateComplete` before calling those functions.
Right now It's working and passing the tests on all the browsers that I've tested (Chrome, Opera, Firefox, Edge, and IE), but I've marked it as `WIP` so I can take a look if there is a less "cumbersome" way to …
> [textarea] Wait for textarea slot before init autoresize

- packages/calendar/src/LionCalendar.js
- packages/calendar/test/lion-calendar.test.js
fixes https://github.com/ing-bank/lion/issues/221
> fix(calendar): disabled dates don't trigger @user-selected-date-changed

- packages/field/src/FormRegistrarMixin.js
- packages/field/src/formRegistrarManager.js
- packages/field/test/FormRegistrationMixins.test.js
Fixes https://github.com/ing-bank/lion/issues/215
Credit to @LarsDenBakker, this was pretty much his quick fix after his analysis. I applied it locally and tested my use case, and this resolves the issue for me. The form system is pretty complex so I hope this is on the right track.
I covered the memory leak in a test. In case you would like to see a test for registering elements in the connected callback also, I'd love some feedback on how/where you'd like to see this (I don't see related tests).
> fix(form): improve managing elements in Form Registrar Manager

- packages/localize/src/number/forceSpaceInsteadOfZeroForGroup.js
- packages/localize/src/number/normalizeIntl.js
fixes https://github.com/ing-bank/lion/issues/229
> fix(localize): for bg-BG locale, correct Intl output for group separator

- packages/localize/src/number/getGroupSeparator.js
- packages/localize/test/number/getGroupSeparator.test.js
four digit numbers can be written without separator, so it would be
safer to obtain the separator by formatting a five digit number. The bug
was found with the locale 'es-ES', where the format returned for '1000'
was '1000' instead of the expected '1.000'. We add the specific expect
clause on the test for it.
On branch fix/numberGroupSeparator
Changes to be committed:
modified:   packages/localize/src/number/getGroupSeparator.js
modified:   packages/localize/test/number/getGroupSeparator.test.js
> fix(localize): update the way to obtain the group separator for a number

- packages/localize/test/number/getGroupSeparator.test.js
~We added a specific bg-BG rule, which now turns out to be:~
- ~Unnecessary, because Intl does it correctly if you get the group separator by formatting a 5 digit number, rather than a 4 digit number (1000-9999). This was fixed in https://github.com/ing-bank/lion/pull/245~
- ~Incorrect. You should not always force the space. For example, if the type is currency, for bg-BG, no spaces are ever added as group separator according to what Intl does at least..~
~This change fixes a bug where bg-BG currencies with 4 or more digits would display with space group separators, and it gets rid of quite some technical debt that we added to 'normalize' it.~
> Localize: add expect to test consistent bg-BG group separator

- packages/validate/translations/ro.js
'de, asemenea' does not add additional information to the sentence, and in that syntax it translates roughly to  "add, in addition, a {fieldName}"
> update romanian translation

- packages/steps/stories/index.stories.js
Previous version wouldn't work inside shadowRoots because it relies on implicit document.getElementById
> fix(steps): fix the steps demo to work in all contexts

- packages/input-email/stories/index.stories.js
- packages/localize/RATIONALE.md
- packages/localize/README.md
- packages/localize/src/LocalizeManager.js
- packages/localize/test/LocalizeManager.test.js
- packages/localize/test/date/formatDate.test.js
https://github.com/ing-bank/lion/issues/187
We still want to keep the fallback locale, the rationale of which is explained here: https://github.com/ing-bank/lion/blob/master/packages/localize/RATIONALE.md#fallbacks
It is a good idea that if there is a case where the locale is not a full language locale, we make a best guess using the fallback locale. And for writing translations, it is still good to structure it like this to prevent duplicate translations. 
The only thing that changes is that we heavily discourage using language-only locales on purpose, shown by sending a console warning if the locale changes to a single language locale.
> chore(localize): deprecate language-only locales

- packages/field/index.js
- packages/field/src/FormRegistrarPortalMixin.js
- packages/field/test-suites/FormRegistrationMixins.suite.js
- packages/input-email/stories/index.stories.js
- packages/localize/RATIONALE.md
- packages/localize/README.md
- packages/localize/src/LocalizeManager.js
- packages/localize/test/LocalizeManager.test.js
- packages/localize/test/date/formatDate.test.js
- packages/steps/stories/index.stories.js
Proposal for `FormRegistrationMixins.js`.
the `FormRegistrarPortalMixin` forwards the event to a specific target node so Registering Child does not need to be in the dom tree of the Registrar Parent.
> fix(field): implement FormRegistrarPortalMixin

- packages/input-amount/src/parsers.js
- packages/input-amount/test/parsers.test.js
Fix parseWithLocale function: Pass a string instead of an object to getDecimalSeparator and getLocale. Test added that fails before the fix.
fixes https://github.com/ing-bank/lion/issues/258
> Fix: pass string instead of object in input-amount parser

- CONTRIBUTING.md
- README.md
- docs/README.md
- docs/definitions.md
- docs/guidelinesStyling.md
Draft for documenting shadow BEM modifiers: they should be `.my-block[modifier]` instead of `.my-block--modifier`. See [don't self-apply classes](https://developers.google.com/web/fundamentals/web-components/best-practices).
Please note that the scope of this pull request is way broader than only modifiers: the documentation also contains the context (why we use BEM and how to apply it in shadow dom).
Please have a quick look at this draft. 
If we agree on the approach (about modifiers), we should also make issues to align all of our CSS with it.
Also, it might lead to some discussions about how we want to map style modules to webcomponents having shadow dom.
I will reread this myself and try to wrap up in a few days
> chore(docs): core docs about style components (draft)

- packages/form-system/package.json
- packages/form-system/stories/formatting.stories.js
- packages/form-system/stories/helper-wc/h-output.js
- packages/form-system/stories/interactionStates.stories.js
- stories/index.stories.js
fixes https://github.com/ing-bank/lion/issues/145
**WIP, because:**
- other form mrs need to be merged first:
- https://github.com/ing-bank/lion/pull/88
- https://github.com/ing-bank/lion/pull/148
- add demos about modelValue syncing, see: https://github.com/ing-bank/lion/issues/93#issuecomment-507794951
- 'polish' modelValue demos with better examples for parsers and formatters
**Nice to have: validation demos, including:**
- basic validators are currently demoed in lion-input(?)
- this in demos: https://github.com/ing-bank/lion/blob/master/packages/validate/docs/tutorials/CustomValidatorsTutorial.md
- this in demos: https://github.com/ing-bank/lion/blob/master/packages/validate/docs/ValidationSystem.md
- an explanation how to override messages for custom validators. Also see: …
> chore(form-system): add form fundament demos

- packages/icon/src/LionIcon.js
- packages/icon/test/lion-icon.test.js
Basic fix of #185 following #116
> Update LionIcon to no longer throws when svg is null

- packages/radio-group/src/LionRadioGroup.js
- packages/radio-group/test/lion-radio-group.test.js
Before the serializedValues and formattedValues method call failed if there weren't any selections made
fixes https://github.com/ing-bank/lion/issues/266
> fix(lion-radio-group): handle unchecked state

- packages/input-amount/test/formatters.test.js
- packages/localize/src/number/formatNumberToParts.js
- packages/localize/test/number/formatNumber.test.js
- packages/localize/test/number/formatNumberToParts.test.js
It is important, mostly for screen readers, that when we format numbers, that we use proper minus sign unicode for negative numbers. 
https://www.deque.com/blog/dont-screen-readers-read-whats-screen-part-1-punctuation-typographic-symbols/
This goes into detail a bit more, but to me it seems like screen readers will have more success with this unicode, compared to the old unicode Hyphen-minus.
Old: https://www.compart.com/en/unicode/U+002D
New: https://www.compart.com/en/unicode/U+2212
Tagging a11y guru @erikkroes 
For discussion:
https://github.com/ing-bank/lion/issues/280
> Fix a11y - use proper minus sign unicode that most SRs understand

- packages/calendar/src/LionCalendar.js
- packages/calendar/test/lion-calendar.test.js
It is an edge case, but when trying to render a calendar which has `minDate` and `maxDate` with the same date, and this date is not today, the calendar can't render since tries to select a `centralDate` outside the valid date range.
When the date is "today", everything goes as expected, but when it is a future or a past date, the calendar throws an error at `__findBestEnabledDateFor`.
I'm providing a test to this feature, and I did change two values within two tests, which I think they make sense. `centralDate` was calculated as the next day from the `minDate` value, or the day before from the `maxDate` value, EXCEPT when `minDate` is lower than today, or `maxDate` is greater (and we only provide one validator), or when the range between `minDate` and `maxDate` contains today.
> fix(calendar): render the calendar when min and max date are same date

- packages/button/src/LionButton.js
Not sure how I produced an error using this but I managed to get errors "cannot read form of undefined" so I figured adding this guard is probably a good idea.
> [button] Guard against _nativeButton not defined

- packages/select-rich/src/LionSelectRich.js
- packages/select-rich/test/lion-select-rich.test.js
It's a fix for rich select, because there it was already intended to work, but instead fieldset throws an error.
Then I figured this should be a feature for radio-group and checkbox-group as well.
I realize implementation for radio / checkbox is the same, but radio-group and checkbox-group don't really have a parent specific to just the two of them and I wanted to "avoid hasty abstractions".
> fix(select-rich): set dynamically name prop on child option elements

- packages/core/index.js
I need to use lit-html Parts for directives I'm writing internally, but they're not exported by lion.
We don't need this if we decide to go for https://github.com/ing-bank/lion/pull/341 instead
> feat(core): export Part classes from lit-html

- packages/input/src/LionInput.js
- packages/textarea/src/LionTextarea.js
- packages/textarea/test/lion-textarea.test.js
Also a small fix for readOnly prop on LionField that didn't have reflect set to true.
@ktnl97 tagging you here, I co-authored you for the fix.
closes https://github.com/ing-bank/lion/pull/337
fixes https://github.com/ing-bank/lion/issues/333
> fix(textarea): delegate readonly to the native element

- packages/radio-group/src/LionRadioGroup.js
- packages/radio-group/test/lion-radio-group.test.js
When a radio-button has a modelValue.value of number 0, then the radio-button-group fails to send 'checked-value-changed' event.
This change checks only for null or undefined. I saw at line 30 in the get checkedValue() that if no el is present, there it returns an empty string. That empty string will not be caught with this fix and will sent the 'checked-value-changed' event. I am not sure if that would be ok or not so I haven't yet changed that.
> fix(radio-group): change check of value to only null or undefined

- packages/field/src/FormRegistrarMixin.js
- packages/field/test-suites/FormRegistrationMixins.suite.js
if you add a form elements after first render, your form element will always be pushed (appended) to the array of formElements. 
This PR makes sure we take care of the correct order, so that if you have
```
<parent>
<child></child>
<child></child>
</parent>
```
and you want to insert something after the first child, it should end up in the formElements array as the 2nd item as well (index 1). 
It may also deal with https://github.com/ing-bank/lion/pull/339 but should be confirmed
> fix(field): add form elements in the correct order

- packages/validate/translations/en-US.js
Currently the "error" and "warning" sub-objects are completely overridden. This fixes it by inheriting them from 'en.js'
> Fix en-US translations in lion-validate

- packages/input/src/LionInput.js
- packages/input/test/lion-input.test.js
Added the option to provide the input component with placeholder text
Previous PR before branch name change:
https://github.com/ing-bank/lion/pull/354
> fix: added placeholder attribute for input

- packages/select-rich/src/LionSelectRich.js
- packages/select-rich/stories/index.stories.js
Old:
New:
unfortunately, I could not add a test for it as apparently the scrolling is taking quite some time 😭
> fix(select-rich): keyboard navigation should handle scrolling

- packages/input-datepicker/src/LionInputDatepicker.js
- packages/input-datepicker/test/lion-input-datepicker.test.js
Makes the datepicker closable by clicking outside of it
> fix(datepicker): close with click

- packages/field/src/FormatMixin.js
- packages/input-amount/src/LionInputAmount.js
- packages/input-amount/src/parsers.js
- packages/input-amount/stories/index.stories.js
- packages/input-amount/test/parsers.test.js
we want to handle user pasting special however our field reformats on input AND change event... 
so it respects it when you paste but it overrides it when you tab out (as change event is also triggered on lost of focus)
=> we probably should not use input AND change event?
> fix(input-amount): handle user pasting of amounts heuristically

- packages/dialog/src/LionDialog.js
- packages/dialog/stories/index.stories.js
- packages/input-datepicker/src/LionCalendarOverlayFrame.js
- packages/input-datepicker/src/LionInputDatepicker.js
- packages/overlays/README.md
- packages/overlays/src/OverlayController.js
- packages/overlays/src/OverlayMixin.js
- packages/overlays/stories/index.stories.js
- packages/overlays/test-suites/OverlayMixin.suite.js
- packages/overlays/test/OverlayController.test.js
- packages/tooltip/src/LionTooltip.js
@LarsDenBakker requested a way to synchronize and intercept open/close state in an api similar to:
```javascript
render() {
return html`
<lion-dialog .opened=${this.opened} @close="${() => this.opened = false;}" @before-close=${(e) => {
if (shouldIntercept) {
e.preventDefault();
} 
}}></ing-dialog>
`;
}
```
> feat(overlay): close/hide events on dom (OverlayMixin) level

- packages/fieldset/src/LionFieldset.js
- packages/fieldset/test/lion-fieldset.test.js
0 (number) is considered as falsy by JavaScript. That means the previous check was ignoring the 0 when defining the `serializedValues`  in `serializeGroup`and `__serializeElements` methods.
> Fix bug in serializeGroup and serializeElements

- packages/calendar/src/LionCalendar.js
> fix(#423): prevent default behavior on keyboard interaction

- husky.config.js
- package.json
Changing it to always run, not just if yarn.lock is staged.
Today ran into the issue that a new "bad" yarn.lock got committed with no-verify somewhere, then later another commit was done on top with verify, but then yarn.lock was no longer staged, so the yarn lock scan never ran, and the code was pushed to github.. 
Always running the verification on yarn.lock, whether it is staged or not, seems like a better security practice.
> fix: improve yarn lock scan, always run

- packages/localize/src/number/forceTryCurrencyCode.js
- packages/localize/src/number/normalizeIntl.js
- packages/localize/test/number/formatNumber.test.js
TRY is the universal currency name for Turkish Liras, but in Turkey it is known as TL. This commit fixes this issue for Turkish localization.
> fix(localize): if locale is set to tr, currency TRY should display TL

- packages/form-system/package.json
- packages/form-system/stories/15-features-overview.stories.mdx
Note: removed the .modelValue of the input-date in the demo template because the date is invalid and doesn't make sense to prefill that field anyway since none of the other fields are prefilled.
> chore(form-system): add fields to umbrella form demo

- packages/button/src/LionButton.js
Potentially resolves https://github.com/ing-bank/lion/issues/533
> fix(button): ie11 error when setting attribute in constructor

- README.md
It is not clear for people which do not work with yarn workspaces that installing depencies with yarn is necessary.
Looked into README.md and expected something about it in the demo section so... here is a PR to explain short why and what to do.
> docs: added line to explain how to demo locally

- packages/textarea/stories/index.stories.mdx
improve documentation by adding details and example about the `readonly` attribute
> chore(textarea): document readonly

- packages/validate/src/ValidateMixin.js
- packages/validate/test-suites/ValidateMixin.suite.js
When removing a validator from an element, the results of the validation should be reset.
Otherwise the old validation result will stay and the validation will always fail.
> fix(validate): reset validation result on validators change

- packages/switch/stories/index.stories.mdx
Info type is not supported for this component. Throws error in browser:
> chore(lion-switch): show info type validator

- packages/tabs/src/LionTabs.js
- packages/tabs/test/lion-tabs.test.js
Resolves https://github.com/ing-bank/lion/issues/587
Is it desired that focussing on a tab after a selectedIndex change does _not_ scroll to the element anymore? I am not sure from an accessibility point of view how this should behave.
Here's a hacky way to see the issue. In the selected index tabs storybook, just a while bunch of whitespace on top of the tabs component. Then, refresh the page and you will see it scrolls down to the selected tab. After the fix, it does not behave like that anymore.
```
You can set the `selectedIndex` to select a certain tab.
<Preview>
<Story name="Selected index">
{html`
<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br …
```
> fix(tabs): prevent scrolling when initially focussing a tab

- packages/form/src/LionForm.js
Spotted this small typo while looking into for LionForm works.
Doesn't cause big issues, but long-term it might allocate too much memory to unused event listeners :)
> fix(form): remove correct reset event listener on teardown

- packages/input-amount/stories/index.stories.mdx
If I am blind enough to miss this section then it's likely more people will not find what they are looking for.
This makes it a bit more easily scannable when you are looking for modifying the decimal amount.
> chore(input-amount): improve title of story to modify decimal amount

- packages/dialog/stories/index.stories.mdx
- packages/overlays/stories/20-index.stories.mdx
Hey there,
As discussed in Slack channel, I open this PR in order to make easier to find the docs regarding the `.config` object to be passed to `Dialog`.
Also, I fixed another link that was broken.
Any questions, please let me know.
Many thanks! ✌️
> Adding link to Overlay System - Configuration from Dialog storybook docs

- packages/checkbox-group/stories/index.stories.mdx
- packages/overlays/src/OverlayController.js
- packages/overlays/src/OverlayMixin.js
- packages/overlays/stories/20-index.stories.mdx
- packages/overlays/test/OverlayController.test.js
- yarn.lock
I think what is appropriate to do in the case when we want to pass controls over styling and animation to the developer is to avoid all the style and animation manipulations in OverlayController.
Only dispatch events for 'init' 'show' 'hide' and 'teardown' and pass backdropNode as a parameter for an overlay controller.
> fix(overlays): support backdrop with local overlay

- packages/calendar/src/LionCalendar.js
- packages/input-datepicker/src/LionCalendarOverlayFrame.js
- packages/input-datepicker/src/LionInputDatepicker.js
- packages/input-iban/src/validators.js
- packages/localize/README.md
- packages/localize/docs/message.md
- packages/localize/stories/50-system-overview.stories.mdx
- packages/validate/src/loadDefaultFeedbackMessages.js
```js
return import(`../translations/${locale}.js`);
```
is problematic for static analysis (webpack, rollup, and probably also the logic unpkg uses to resolve ES Modules).
We could fix it by publishing code that doesn't have dynamic content inside a dynamic import, by doing a prepublish step to go from what's in the source code:
```js
return import(`../translations/${locale}.js`);
```
to generating something that makes the published code like this:
```js
switch(locale) {
case 'en-GB': 
return import('../translations/en-GB.js');
break;
case 'nl-NL':
return import('../translations/en-GB.js');
break;
// etc.
}
```
But we decided that since we already have the switch statements in all cases, we just edit the default case and set it to en-GB. If our users stiill wanna use the dynamic var in …
> fix: refrain from using dynamic vars inside dynamic import

- packages/overlays/src/OverlayMixin.js
- packages/overlays/stories/demo-overlay-system.js
- packages/overlays/test-suites/OverlayMixin.suite.js
this MR fixes issue 469 
Thanks to @tlouisse for the fix. I added a test to cover the real use case (clicking on the invoker and not calling the show directly)
> fix(overlays): synchronize intercepted opened state OverlayMixin

- CONTRIBUTING.md
- packages/input-datepicker/src/LionInputDatepicker.js
Using MinMaxDate or MaxDate validators didn't limit the range of dates, this fix is treating the issue.
> fix(datepicker): selection of dates outside of min/max range is permitted

- packages/input-amount/src/LionInputAmount.js
- packages/input-amount/test/lion-input-amount.test.js
Added inputmode='decimal' to improve experience on mobile devices (numeric keyboard with decimal signs opens automatically on supported browsers => see https://css-tricks.com/everything-you-ever-wanted-to-know-about-inputmode/ )
> fix(input-amount): set hint to use numeric on-screen keyboard

- packages/remark-extend/index.js
without it this fails
```js
const { remarkExtend } = require('remark-extend');
```
> fix(remark-extend): add missing main entry point

- packages/localize/src/number/normalizeIntl.js
- packages/localize/test/number/formatNumber.test.js
It is uncommon for Turkish people to use currency code at the start of a number. This commit fixes that.
> fix(localization): for tr currencycode must be on end

- packages/dialog/src/LionDialog.js
- packages/dialog/test/lion-dialog.test.js
- packages/overlays/src/OverlayMixin.js
fixes https://github.com/ing-bank/lion/issues/676
The reason this bug was here is because open/close event listeners were added on a nested dialog, but then the nested dialog would be moved through the DOM **before** finishing setting up the overlay controller. So then disconnectedCallback would happen and not tear down the open/close event listeners (because of the overlay controller guard). 
And then you get duplicate open/close listeners on the nested dialog, resulting in a double toggle on click, which means it opens and instantly closes.
> fix(dialog): teardown open close listeners after initial updateComplete

- packages/validate/stories/Overview.stories.mdx
Fixes #714 
Add short explanation/example of using `hasFeedbackFor` or `showsFeedbackFor` in JS code to determine a fields validity.
> fix: add brief explanation of hasFeedbackFor and showsFeedbackFor

- packages/remark-extend/src/remarkExtend.js
- packages/remark-extend/test-node/remark-extend.test.js
- tasks where gathered independently e.g. first all Replacements, then additions then removals.
but users will not write their extendMd in this way they will expect the order to be exactly like they wrote it
- tasks are exactly the same as in the extendMd
> fix(remark-extend): task order is the same as in provided extend md

- packages/overlays/src/configurations/withDropdownConfig.js
- packages/select-rich/test/lion-select-rich.test.js
- yarn.lock
Fixes:
To:
Overriding this inheritsReferenceWidth for noDefaultSelected still works as before, but is now less useful as a default because we now set the width to 'min' by default already (before it was 'full').
> fix(select-rich): set inherits reference width to min

- packages/form-core/src/validate/ValidateMixin.js
- packages/form-core/test/lion-field.test.js
Closes #705 
When a field is enabled and then toggled to disabled while being invalid, it still had the `validationStates` and `hasFeedbackFor` properties set from when it was enabled.
Calling `this.__finishValidation` synchronously after `this.__clearValidationResults`, ensures that those properties are reset.
> fix(field): remove validation toggled disable

- packages/overlays/docs/20-index.md
- packages/overlays/src/OverlayController.js
- packages/overlays/test/OverlayController.test.js
- packages/overlays/test/OverlaysManager.test.js
This was already not working and would give you problems, now we explicitly mention why it fails by throwing an error
> fix: throw when passing unconnected contentNode

- packages/overlays/docs/40-system-configuration.md
- packages/overlays/src/OverlayController.js
- packages/overlays/src/utils/typedef.js
- packages/overlays/test/OverlayController.test.js
- packages/tooltip/README.md
- packages/tooltip/src/LionTooltip.js
- packages/tooltip/test/lion-tooltip.test.js
Fixes:
- clean up a11y attrs for all types of overlays on teardown
- enables a11y in lion-tooltip
- expose tooltip prop `invokerRelation` and connect to OverlayCtrl
closes https://github.com/ing-bank/lion/issues/754
> [tooltip] accessibility fixes

- packages/checkbox-group/README.md
- packages/form-core/src/choice-group/ChoiceInputMixin.js
- packages/radio-group/README.md
help-text attribute is available on choice inputs (checkbox and radio), but it's not rendered.
Here is a proposal for rendering them.
> feat(choice-input): add rendering of help-text

- packages/localize/src/date/addLeadingZero.js
- packages/localize/src/date/pad.js
- packages/localize/src/date/parseDate.js
- packages/localize/test/date/formatDate.test.js
- packages/localize/test/date/parseDate.test.js
- packages/validate-messages/translations/bg.js
- fix memoize function & correct computation of date format
- modify date format in bulgarian validation messages
BREAKING CHANGE: N
closes #540
Please refer previous PR https://github.com/ing-bank/lion/pull/780 for discussions.
> fix(localize): format hungarian & bulgarian dates

- package.json
- web-test-runner.config.js
- yarn.lock
This updates to the latest version of web test runner which among other changes is a lot faster.
I notice this test is flaky:
```
packages/overlays/test/OverlayMixin.test.js:
❌ OverlayMixin integrations > OverlayMixin > syncs opened to overlayController
at: packages/overlays/test-suites/OverlayMixin.suite.js
error: expected true to be false
+ expected - actual
-true
+false
```
Is that already the case on master?
> chore: update to test runner v0.6

- packages/select-rich/src/LionSelectRich.js
- packages/select-rich/test/lion-select-rich-dialog-integration.test.js
closes https://github.com/ing-bank/lion/issues/806
> fix(select-rich): align teardown phase with OverlayMixin

- docs/extending-documentation.md
This was the only way for me to make it look good in storybook
> chore: fix extend docs fenced codeblocks in docs

- package.json
- yarn.lock
Currently results in this output
```
Chromium: |██████████████████████████████| 117/117 test files | 1502 passed, 0 failed
Firefox:  |██████████████████████████████| 117/117 test files | 1478 passed, 24 failed
Webkit:   |██████████████████████████████| 117/117 test files | 1488 passed, 14 failed
```
before we can enable it in the CI this needs to be green for everything.
Errors are most likely in the tests but needs to be clean up. (Firefox fails on all focus tests - potentially a playwright config issue)
> chore: add playwright and a script to test in all evergreen browsers

- .changeset/silver-penguins-juggle.md
- packages/overlays/src/OverlayController.js
Fix of issue - #826
OverlayController.js has unhandled rejection -
`Unhandled rejection: Error: Failed to execute 'appendChild' on 'Node': The new child element contains the parent.`
> fix: [overlay] fix unhandled rejection

- .changeset/sharp-rules-tell.md
- packages/providence-analytics/src/cli/cli-helpers.js
- packages/providence-analytics/src/cli/cli.js
- packages/providence-analytics/src/program/analyzers/helpers/Analyzer.js
- packages/providence-analytics/src/program/analyzers/helpers/from-import-to-export-perspective.js
- packages/providence-analytics/src/program/analyzers/match-imports.js
- packages/providence-analytics/src/program/analyzers/match-paths.js
- packages/providence-analytics/src/program/utils/async-array-utils.js
- packages/providence-analytics/test-node/cli/cli.test.js
- packages/providence-analytics/test-node/program/analyzers/match-imports.test.js
- packages/providence-analytics/test-node/program/services/InputDataService.test.js
adds:
- `--include-target-deps`: For all search targets, will include all its dependencies
(node_modules and bower_components). When --target-deps-filter is applied, a subset
will be applied that matches the filter condition
- `--target-deps-filter`: Regex condition to be applied to dependencies of search targets.
- extensive cli tests
> feat(providence-analytics): allow target dependencies via cli

- .changeset/five-donuts-joke.md
- packages/select-rich/README.md
- packages/select-rich/src/LionSelectRich.js
- packages/select-rich/test/lion-select-rich.test.js
1. Make sure that when doing additions and removals of options that singleOption gets set to true/false
closes https://github.com/ing-bank/lion/issues/919
> fix(select-rich): singleOption true only if there is exactly one option

- .changeset/early-houses-punch.md
- .changeset/shaggy-dolls-trade.md
- .eslintrc.js
- packages/checkbox-group/src/LionCheckbox.js
- packages/checkbox-group/src/LionCheckboxGroup.js
- packages/checkbox-group/test/lion-checkbox-group.test.js
- packages/radio-group/src/LionRadio.js
- packages/radio-group/src/LionRadioGroup.js
- packages/radio-group/test/lion-radio-group.test.js
- tsconfig.json
1. Add types
2. Disable linting rule since TSC checks it in a better way and it was conflicting with each other
3. TSC config --> alphabetical order to please my OCD.
> feat: add types for checkbox-group & radio-group

- .changeset/lucky-otters-appear.md
- packages/pagination/src/LionPagination.js
1. Extract the nav list template logic into a protected method so that the derived component can easily reuse it.
> fix(pagination): extract nav list template to reuse in derived component

- .changeset/little-jeans-yell.md
- package.json
- packages/input-datepicker/test/lion-input-datepicker.test.js
- packages/overlays/src/OverlayController.js
- packages/overlays/test-suites/OverlayMixin.suite.js
- packages/overlays/test/OverlayController.test.js
1. Add `async transitionShow` and `async transitionHide` to OverlayController to enable basic support for transitions/animations
> fix(overlays): add transition hooks to overlays

- .changeset/five-tips-camp.md
- packages/tabs/README.md
- packages/tabs/src/LionTabs.js
- packages/tabs/test/lion-tabs.test.js
fixed: https://github.com/ing-bank/lion/issues/960
By only looking for tabs and panels as direct children.
> fix(tabs): allow nested tabs

- .changeset/heavy-ghosts-sell.md
- packages/combobox/README.md
- packages/combobox/docs/demo-selection-display.js
- packages/combobox/docs/lazyRender.js
- packages/combobox/docs/levenshtein.js
- packages/combobox/src/LionCombobox.js
- packages/combobox/test/lion-combobox.test.js
- renamed `filterOptionCondition ` (similarity to `match-mode`, since this is basically an override)
- demos for `matchCondition`
- inline autocompletion edge cases solved (that would be inconsistent ux otherwise)
- demos took a long time render: introduced a lazyRender directive that only adds (expensive) lionOptions after first meaningful paint has happened
- made clearer from the code that selectionDisplay component is for demo purposes only at this moment
> feat(combobox): improvements api, demos and autocompletion ux

- .changeset/stupid-ads-guess.md
- packages/select-rich/src/LionSelectRich.js
1. Change scrollTargetNode to listboxNode, same as parent and extention layer. The extention layer has a different overlayContentNode and had to set it back to listboxNode.
> fix(select-rich): change scrollTargetNode to listboxNode

- .changeset/hip-pears-vanish.md
- packages/calendar/src/LionCalendar.js
- packages/calendar/src/utils/createDay.js
- packages/calendar/src/utils/createMonth.js
- packages/calendar/src/utils/createMultipleMonth.js
- packages/calendar/src/utils/createWeek.js
- packages/calendar/src/utils/dataTemplate.js
- packages/calendar/src/utils/dayTemplate.js
- packages/calendar/src/utils/getFirstDayNextMonth.js
- packages/calendar/src/utils/getLastDayPreviousMonth.js
- packages/calendar/src/utils/isSameDate.js
- packages/calendar/test-helpers/CalendarObject.js
- packages/calendar/test-helpers/DayObject.js
- packages/calendar/test/lion-calendar.test.js
- packages/calendar/test/utils/createMonth.test.js
- packages/calendar/test/utils/createMultipleMonth.test.js
- packages/calendar/test/utils/createWeek.test.js
- packages/calendar/test/utils/isSameDate.test.js
- packages/calendar/test/utils/snapshots/monthTemplate_en-GB_Sunday_2018-12.js
- packages/calendar/types/day.d.ts
- packages/input-datepicker/src/LionCalendarOverlayFrame.js
- packages/input-datepicker/src/LionInputDatepicker.js
- packages/input-datepicker/test-helpers/DatepickerInputObject.js
- packages/input-datepicker/test/lion-input-datepicker-integrations.test.js
- packages/input-datepicker/test/lion-input-datepicker.test.js
- tsconfig.json
1. Type calendar
2. Fix a bug in calendar where it does not properly add / remove event listeners especially when moving in the DOM
- The code for tearing down is just wrong, because it tries to event handler `void`....
- firstUpdated only runs once and this is where the listeners are added, so they are added only once 
- This makes the tests pass.. because they are not torn down, and they are not re-added, so it looks like it works 😅 
- Did the following fix, made connectedCallback async, add await updateComplete and move firstUpdated logic that needs to happen on every reconnect to below the await.
```js
async connectedCallback() {
// eslint-disable-next-line wc/guard-super-call
super.connectedCallback();
this.__connectedCallbackDone = true;
this.__calculateInitialCentralDate();
// …
```
> feat: add types for calendar and datepicker

- packages/listbox/src/ListboxMixin.js
1. This change fixes [this](https://github.com/ing-bank/lion/issues/993) issue. As modelValue is not getting changed when new child components are added, passed `this.modelValue` to be mapped to `oldValue` for comparison
> fix(listbox): prevent modelValue change by child components addition

- .changeset/shaggy-pans-kiss.md
- packages/combobox/README.md
- packages/combobox/src/LionCombobox.js
- packages/combobox/test/lion-combobox.test.js
- packages/listbox/test-suites/ListboxMixin.suite.js
adds feature `show-all-on-empty` (by default, wai-aria example + <datalist> hide list when no matches are found (input is empty))
One edge case is still not fixed (see TODO), we need a separate issue for that
> feat(combobox): option showAllOnEmpty

- .changeset/eleven-bears-repair.md
- packages/combobox/src/LionCombobox.js
1. define enhancer for `formControlMixin` to add `form-control` class to slot element instead of child element of slot so as to style slot from component
> fix(combobox): form-control class to correct node

- .changeset/cool-panthers-design.md
- .changeset/shiny-cameras-sparkle.md
- packages/overlays/docs/20-index.md
- packages/overlays/docs/40-system-configuration.md
- packages/overlays/docs/demo-overlay-backdrop.js
- packages/overlays/docs/demo-overlay-system.js
- packages/overlays/src/OverlayController.js
- packages/overlays/src/OverlayMixin.js
- packages/overlays/src/globalOverlaysStyle.js
1. Fix a bug where teardown did not properly teardown the right backdropNode for animation = true
2. Fix a bug where content node was not torn down properly when updateConfig is called every time we show (when for example the config is updated on before-show based on viewport)
3. Simplify the code for backdrop feature
4. Added demos for backdrop
5. Align API for backdrop (can pass `hasBackdrop: true` which spawns a default backdropNode, can pass `backdropNode` or declaratively `<div slot="backdrop"></div>` to pass your own, and can pass `hasBackdropAnimation: true` which turns on animation, assumes you have CSS animations applied to your backdropNode)
6. Small fix for overlayContentNode in OverlayMixin, to support imperatively passed contentNode
The two bugs were quite difficult to create …
> fix: fix backdrop teardown/init bugs and align APIs

- .changeset/breezy-emus-rush.md
- packages/localize/src/number/forceTryCurrencyCode.js
- packages/localize/test/number/formatNumber.test.js
The old code was taking only the index 0 of formatted parts. This cause a bug in minus amount values. This foreach function changes the specific 'currency' value.
> fix(localization): was not formatting minus values

- .changeset/hungry-files-lay.md
- .changeset/sour-apes-reply.md
- packages/form-core/src/FormControlMixin.js
- packages/form-core/src/choice-group/ChoiceGroupMixin.js
- packages/form-core/src/choice-group/ChoiceInputMixin.js
- packages/form-core/src/registration/FormRegistrarMixin.js
- packages/form-core/test-suites/ValidateMixinFeedbackPart.suite.js
- packages/form-core/test-suites/choice-group/ChoiceGroupMixin.suite.js
- packages/form-core/test-suites/form-group/FormGroupMixin.suite.js
- packages/form-core/types/FormControlMixinTypes.d.ts
- packages/form-core/types/form-group/FormGroupMixinTypes.d.ts
- packages/listbox/test-suites/ListboxMixin.suite.js
1. fixes issue where name delegation in ChoiceGroupMixin doesn't happen on updated callback when parent name changes
2. fixes #730
> fix(form-core): update child choice fields name attr to parent

- .changeset/gorgeous-poets-explain.md
- packages/form-core/src/validate/ValidateMixin.js
- packages/form-integrations/docs/35-system-interaction-states.md
1. Add missing interactions states 'filled' and 'focused' to be considered in validation.
2. Fix our long-broken demo that actually very neatly shows how you can vary the interaction state conditions that apply to whether feedback gets shown or not.
> fix(form-core): add missing interaction states for feedback conditions

- .changeset/two-rats-tease.md
- packages/button/README.md
- packages/button/src/LionButton.js
- packages/button/test/lion-button.test.js
- remove click-area --> move styles to host::before
- reduce css so that extending styles makes sense. Merge .btn with host.
- reduce the template and remove the if else construction inside the template.
- hide focus styles if they're not needed, for example, when an element receives focus via the mouse.
- improve `__clickDelegationHandler`. Use current slotted native button instead of create new one.
- fix vertical alignment when 2 buttons are inline and one has icon. Example included.
- add min-with to ensure target size for mobile, not only height
- add test to check event.target in all situations (inside and outside form)
> refactor(button): several improvements

- .changeset/many-cougars-sit.md
- packages/textarea/README.md
- packages/textarea/src/LionTextarea.js
- packages/textarea/test/lion-textarea.test.js
1. Added Intersection Observer to ensure textarea gets recalculated on visibility changes, e.g. when it is inside a dialog, tabs, or accordion when they are hidden initially
fixes https://github.com/ing-bank/lion/issues/855
> fix(textarea): add intersection observer for textarea recalculate

- .changeset/silent-waves-teach.md
- packages/combobox/README.md
- packages/combobox/package.json
- packages/combobox/src/LionCombobox.js
- packages/combobox/test/lion-combobox.test.js
- packages/form-core/src/FocusMixin.js
- packages/form-core/src/FormControlMixin.js
- packages/form-core/src/FormatMixin.js
- packages/form-core/src/InteractionStateMixin.js
- packages/form-core/src/choice-group/ChoiceGroupMixin.js
- packages/form-core/src/choice-group/ChoiceInputMixin.js
- packages/form-core/src/form-group/FormGroupMixin.js
- packages/form-core/src/validate/ValidateMixin.js
- packages/form-core/types/FormControlMixinTypes.d.ts
- packages/form-integrations/docs/15-features-overview.md
- packages/listbox/src/ListboxMixin.js
- packages/listbox/test-suites/ListboxMixin.suite.js
- packages/listbox/types/ListboxMixinTypes.d.ts
1. Allow flexibility for extending the repropagation prevention conditions, which is needed for combobox, so that a model-value-changed event is propagated when no option matches after an input change. This allows validation to work properly e.g. for Required. fixes https://github.com/ing-bank/lion/issues/1018
It's a tricky one, because of two reasons: 
- First, the redispatching of modelValue update to Lit was not done correctly. The oldValue was passed as the already updated value since it goes through a custom getter, so Lit didn't see a change, and no updated callback would happen for modelValue. This part is fixed by storing and passing the oldModelValue, which makes validation work.
- Second, dirty is not set to true when pressing backspace (see demo). The reason is that the …
> fix(combobox): dispatch model-value-changed properly on unselect

- .changeset/hip-peaches-shake.md
- packages/tooltip/README.md
- packages/tooltip/src/LionTooltip.js
- packages/tooltip/test/lion-tooltip.test.js
1. Add a check if the invoker is disabled, if so don't open the tooltip
> fix(tooltip): keeps tooltip closed when invoker is disabled

- .changeset/eight-lions-provide.md
- packages/combobox/docs/LinkMixin.js
- packages/combobox/docs/Subclassers.md
- packages/combobox/docs/lm-option/lm-option.js
- packages/listbox/src/ListboxMixin.js
- packages/listbox/test-suites/ListboxMixin.suite.js
1. Current implementation with LinkMixin allows to add links to the options of a combox, however link is only triggered on a 'click' and not on 'enter' as the listboxmixin blocks this. 
In order to get the same behaviour an extra check is implemented to click on 'enter' of an option with a 'href' attribute.
2. Added example doc.
3. added Rel option to LinkMixin in order to allow passing in 'noopener noreferrer' when required.
Test to follow (let me know if you have a suggestion on how to test this properly)
> feat(listbox): add click on enter for options with href

- .changeset/tasty-rabbits-fry.md
- packages/providence-analytics/src/cli/launch-providence-with-extend-docs.js
- packages/providence-analytics/src/program/analyzers/helpers/Analyzer.js
- packages/providence-analytics/src/program/analyzers/match-imports.js
- packages/providence-analytics/src/program/analyzers/match-paths.js
- packages/providence-analytics/src/program/analyzers/match-subclasses.js
- packages/providence-analytics/src/program/providence.js
- packages/providence-analytics/test-node/cli/cli.test.js
1. add `skipCheckMatchCompatibility` for mono repo support (which have their deps not in main package.json)
See: https://github.com/ing-bank/lion/issues/858
> feat(providence-analytics): add option skipCheckMatchCompatibility

- .changeset/curly-oranges-promise.md
- packages/button/src/LionButton.js
As it may be a bit unclear without a visual:
Red being the click-area and black being the button "real" visual area.
> fix(button): set width/height clickarea 100%

- .changeset/large-dodos-notice.md
- packages/icon/README.md
- packages/icon/src/LionIcon.js
- packages/icon/test/lion-icon.test.js
1. Fixed some minor demo details
2. Added aria-hidden to the SVG in the icon to hide it for FireFox
Fixes https://github.com/ing-bank/lion/issues/172
> fix(icon): single pronounciation in JAWS/FF

- .changeset/silver-forks-learn.md
- packages/form-integrations/test/model-value-consistency.test.js
- packages/listbox/src/ListboxMixin.js
- packages/listbox/test-suites/ListboxMixin.suite.js
1. Does not dispatch model-value-changed on reappend checked child
2. Add combobox and listbox to the `model-value-change` integration test
> fix(listbox): on fire model-value-changed when update from children

- .changeset/short-scissors-poke.md
- packages/combobox/src/LionCombobox.js
- packages/form-core/src/choice-group/ChoiceGroupMixin.js
- packages/form-core/test-suites/FormatMixin.suite.js
- packages/form-integrations/package.json
- packages/form-integrations/test/form-integrations.test.js
- packages/form-integrations/test/form-reset.test.js
- packages/input-datepicker/test/lion-input-datepicker.test.js
- packages/input-stepper/src/LionInputStepper.js
- packages/localize/src/date/formatDate.js
- packages/localize/src/date/normalizeIntlDate.js
- packages/localize/src/date/parseDate.js
- packages/localize/test/date/formatDate.test.js
- packages/localize/test/number/formatNumber.test.js
- packages/localize/test/number/formatNumberToParts.test.js
- packages/select-rich/README.md
- packages/select-rich/test/lion-select-rich.test.js
- packages/switch/test/lion-switch.test.js
- packages/tooltip/test/lion-tooltip.test.js
- web-test-runner-chrome.config.mjs
- web-test-runner-firefox.config.mjs
- web-test-runner-webkit.config.mjs
- web-test-runner.config.mjs
1.
Failed test files:
```
[1]   packages/combobox/test/lion-combobox.test.js
[2]   packages/form-integrations/test/model-value-consistency.test.js
[3]   packages/input-datepicker/test/lion-input-datepicker.test.js
[4]   packages/input-stepper/test/lion-input-stepper.test.js
[5]   packages/localize/test/date/formatDate.test.js
[6]   packages/localize/test/number/formatNumber.test.js
[7]   packages/localize/test/number/formatNumberToParts.test.js
done:
[8]   packages/select-rich/test/lion-select-rich.test.js
[9]   packages/switch/test/lion-switch.test.js
[10]  packages/tooltip/test/lion-tooltip.test.js
```
at: node_modules/chai/chai.js:9449:22
+ expected - actual
-5
+2
expected 5 to equal 2
at: node_modules/chai/chai.js:9449:22
+ expected - actual
-5
+2
expected 5 to equal 2
at: …
> Run tests also on webkit

- .changeset/silent-steaks-marry.md
- packages/input-stepper/src/LionInputStepper.js
- packages/input-stepper/test/lion-input-stepper.test.js
1. Use prefix and suffix existing slots for the increment and decrement buttons
2. Add methods that can be overridden for increment and decrement icons
> fix(input-stepper): make use of prefix and suffix slots

- .changeset/rotten-foxes-tan.md
- packages/core/index.d.ts
- packages/core/index.js
Export removeNodes and reparentNodes functions from lit-html. This is needed to write directives.
> Export reparentNodes and removeNodes

- .changeset/swift-windows-train.md
- packages/localize/src/date/parseDate.js
- packages/localize/test/date/parseDate.test.js
`parseDate('31.02.2020') returned 'Mon Mar 02 2020 00:00:00 GMT+0100....'`
But not anymore, now it returns `undefined`.
> fix(localize): do not parse non-existing dates

- .changeset/fifty-jars-sing.md
- .changeset/olive-news-suffer.md
- packages/helpers/renderLitAsNode/src/renderLitAsNode.js
- packages/helpers/sb-action-logger/src/SbActionLogger.js
- packages/helpers/sb-action-logger/test/sb-action-logger.test.js
- packages/helpers/sb-locale-switcher/src/SbLocaleSwitcher.js
- packages/helpers/sortEachDepth/src/sortEachDepth.js
- packages/icon/src/IconManager.js
- packages/icon/src/LionIcon.js
- packages/icon/src/icons.js
- packages/icon/test/IconManager.test.js
- packages/icon/test/hammer.svg.js
- packages/icon/test/heart.svg.js
- packages/icon/test/lion-icon.test.js
- tsconfig.json
Changed from whitelisting packages to be typed to blacklisting those who should not.
Found out we are missing types for quite many things still, not sure what happened there. Most important is `icon`, `ajax` and a few issues in `helpers` (minor)
Added FIXMEs for those that we MUST type ASAP.
Added TODOs for those that we SHOULD type (tests etc.)
> chore: whitelist -> blacklist for tsconfig

- .changeset/soft-steaks-cross.md
- packages/collapsible/src/LionCollapsible.js
- packages/form-core/src/FormControlMixin.js
- packages/form-core/src/choice-group/ChoiceInputMixin.js
- packages/helpers/sb-action-logger/src/SbActionLogger.js
- packages/listbox/src/ListboxMixin.js
- packages/overlays/src/ArrowMixin.js
- packages/overlays/types/ArrowMixinTypes.d.ts
- packages/pagination/src/LionPagination.js
1. Make all styles getters from components that can be extended or implemented (mixins) return a CSSResultArray instead of CSSResult. Makes typing for subclassers easier, since they have to do overrides and apply `super.styles`
2. Noticed a few mixins were not typing their superclass param properly. This showed some problems. ArrowMixin must implement OverlayMixin for example, because it has a strict contract with it through the defineOverlay method that ArrowMixin calls through super.
> fix: make styles consistent across lion and fix some missing types

- .changeset/friendly-islands-repair.md
- packages/localize/src/LocalizeManager.js
- packages/localize/src/date/formatDate.js
- packages/localize/src/number/formatNumber.js
- packages/localize/test/date/formatDate.test.js
- packages/localize/test/number/formatNumber.test.js
- packages/localize/types/LocalizeMixinTypes.d.ts
From the proposal from @tlouisse I have added the functionality to allow **formatDate** and **formatNumber** post-processing.
Apparently, we want to be able to provide `formatDate` settings that only apply to the ing layer.
In this case, we should allow extra options like a 'post-process function' to `formatDate` in the Lion layer.
We then would have to do:
_formatDate_ (https://github.com/ing-bank/lion/blob/master/packages/localize/src/date/formatDate.js)
```javascript
export function formatDate(date, options) {
...
if (typeof options.postProcessor === 'function') {
return options.postProcessor(formattedDate);
}
return formattedDate;
}
```
_localizeManager_ (https://github.com/ing-bank/lion/blob/master/packages/localize/src/LocalizeManager.js)
```javascript
constructor() {
... …
```
> Localize post processors

- .changeset/soft-walls-swim.md
- packages/ajax/src/interceptors.js
- packages/form-core/src/registration/FormRegistrarMixin.js
- packages/form-core/test-suites/FormRegistrationMixins.suite.js
1. chore(ajax): remove console logs in test files
2. Adding form elements at the top of a form now adds them to the beginning of the `.formElements` to keep it in sync with the dom order.
> fix(form-core): make sure .formElements stays in sync with dom order

- .changeset/proud-geckos-arrive.md
- packages/overlays/src/ArrowMixin.js
extract arrow config, so it's possible to reapply in different configs in extension layers
> feat(overlays): make arrow config more composable

- .changeset/weak-papayas-sort.md
- packages/overlays/src/OverlayMixin.js
- packages/overlays/test-suites/OverlayMixin.suite.js
- packages/overlays/types/OverlayMixinTypes.d.ts
expose `open()`,  `close()` and `toggle()` methods on host,
- requested by consumers: See: https://github.com/ing-bank/lion/discussions/1095. It's a better interface than the opened attribute
- makes it more straightforward to add your own click/hover etc. handlers
So before, for every extension you would have to do:
```js
constructor() {
super();
this._myToggleMethod = this._myToggleMethod.bind(this);
}
_myToggleMethod() {
this._overlayCtrl.toggle();
}
_setupOverlayCtrl() {
super._setupOverlayCtrl();
this._invokerNode.addEventListener('click', this._myToggleMethod);
}
_teardownOverlayCtrl() {
super._teardownOverlayCtrl();
this._invokerNode.removeEventListener('click', this._myToggleMethod);
}
```
Now it's just :
```js
_setupOverlayCtrl() {
super._setupOverlayCtrl(); …
```
> feat(overlays): open, close and toggle methods on host

- .changeset/popular-bugs-roll.md
- packages/calendar/src/LionCalendar.js
- packages/input-datepicker/test/lion-input-datepicker.test.js
1. fix duplicate events bug
2. Removed useCapture true on the focus and blur event delegation, since it resulted in strange behaviour when clicking a date in the previous month or next month from the current month display. I'm not sure why it was added, but it seems to be unnecessary and even causing the wrong behaviour.
> fix(calendar): fix bug with duped events, unintended behavior useCapture

- .changeset/silent-ligers-clean.md
- packages/singleton-manager/README.md
- packages/singleton-manager/package.json
- packages/singleton-manager/src/SingletonManagerClass.js
- packages/singleton-manager/test/SingletonManagerClass.test.js
1. Save all instances of singletonManager in the Window object. This avoids the issue of having multiple singletonManagers if this library gets imported more than one time.
> feat(singleton-manager): save singleton instance on window object

- .changeset/popular-needles-hug.md
- packages/listbox/README.md
- packages/listbox/src/LionOption.js
- packages/listbox/src/ListboxMixin.js
- packages/listbox/test-suites/ListboxMixin.suite.js
- packages/listbox/test/lion-option.test.js
1. Fix keyboard navigation when `selection-follows-focus` and `orientation="horizontal"` are set on a `<lion-listbox>`
1. Fix keyboard navigation with `selection-follows-focus` and disabled options
1. On click of an option, it become active
Closes #1105
> fix(listbox): using selection-follows-focus with horizontal orientation

- .changeset/forty-buttons-occur.md
- packages/icon/src/LionIcon.js
Add a _iconManager function at LionIcon to allow components extending LionIcon to use their own IconManager, or at least, set a project specific key for the singletonManager
> feat(icon): allow custom iconManager

- .changeset/dirty-students-smile.md
- .changeset/purple-beers-applaud.md
- packages/input-datepicker/test-helpers/DatepickerInputObject.js
- packages/overlays/src/OverlayController.js
- packages/overlays/src/OverlayMixin.js
- packages/overlays/src/utils/is-equal-config.js
- packages/overlays/test-suites/OverlayMixin.suite.js
- packages/overlays/test/OverlayController.test.js
- packages/overlays/test/utils-tests/is-equal-config.test.js
- packages/select-rich/test/lion-select-rich.test.js
Fixes #1075. Since a `config` reference change in the `OverlayMixin` resets the DOM, essentially hiding the opened content...
1. Prevented the teardown and init from happening caused by calling the `_controller.updateConfig()` if the new config is equivalent to the original. Considering the bundle size I've opted for the manual implementation of the `isEqualConfig` over depending on / inlining a deep equal check from `ramda` or `lodash`.
2. Triggered `__syncToOverlayController()` if the config changed intending to re-trigger the necessary DOM updates.
Deeper, on the `OverlayController` level diffing the exact nature of the config change, and doing a minimal DOM change instead of a complete teardown and init. Didn't have the confidence to pull off such an invasive change.
It's also …
> fix(overlays): sync config change to controller

- .changeset/fair-meals-sell.md
- packages/overlays/docs/20-index.md
- packages/overlays/src/ArrowMixin.js
1. Position arrow correctly for placement top
2. Add demo to show the correct placement (same order and styles are used for the tooltip placement demo)
> fix(overlays): position arrow correctly for placement top

- .changeset/chilly-cooks-judge.md
- yarn.lock
1. Yarn lock was bad, caused types to be built wrongly with the dependency type imports, so we re-release core so that all types get rebuilt and published.
> chore: fix yarn.lock and schedule rebuilt all types

- .changeset/silver-horses-return.md
- packages/overlays/src/OverlayMixin.js
- packages/overlays/test-suites/OverlayMixin.suite.js
1. Prevent opened-changed to be sent twice.
If you add an event listener on a `<lion-dialog>`, you have 2 events sent when you open it.
> fix(dialog): prevent opened-changed to be sent when it is not changing

- .changeset/serious-candles-serve.md
- packages/overlays/types/ArrowMixinTypes.d.ts
Corrects typescript from `@popperjs/core` for overlays package
1. Corrects typescript from `@popperjs/core` for overlays package
> fix(overlays): typescript errors

- .changeset/eleven-pans-shave.md
- packages/form-core/src/choice-group/ChoiceInputMixin.js
- packages/form-core/test-suites/choice-group/ChoiceInputMixin.suite.js
- packages/form-core/types/choice-group/ChoiceInputMixinTypes.d.ts
Not sure if this is the right place to fix it, but doing
```html
<lion-checkbox 
@click=${() => console.log('clicked')} 
label="Francis Bacon" 
.choiceValue=${'Francis Bacon'}
></lion-checkbox>
```
and then clicking the label creates 2 click events.
Clicking the graphic container only creates 1 click event. 
Therefore, I figured we just prevent the label click from propagating on the CE (lion-choice-input), so that you only get 1 click event on the CE.
> fix(form-core): dedupe click event label choice inputs

- .changeset/five-onions-hope.md
- .changeset/lazy-chicken-speak.md
- .changeset/witty-mugs-vanish.md
- packages/checkbox-group/README.md
- packages/checkbox-group/index.js
- packages/checkbox-group/lion-checkbox-indeterminate.js
- packages/checkbox-group/package.json
- packages/checkbox-group/src/LionCheckboxIndeterminate.js
- packages/checkbox-group/test/lion-checkbox-indeterminate-integrations.test.js
- packages/checkbox-group/test/lion-checkbox-indeterminate.test.js
- packages/form-core/src/choice-group/ChoiceGroupMixin.js
- packages/form-core/src/choice-group/ChoiceInputMixin.js
- packages/form-core/src/form-group/FormGroupMixin.js
- packages/form-core/src/registration/FormRegisteringMixin.js
- packages/form-core/src/registration/FormRegistrarMixin.js
- packages/form-core/test/lion-field.test.js
- packages/form-core/types/choice-group/ChoiceInputMixinTypes.d.ts
- packages/form-core/types/registration/FormRegisteringMixinTypes.d.ts
- packages/form-core/types/registration/FormRegistrarMixinTypes.d.ts
- packages/listbox/src/LionOption.js
- packages/listbox/types/LionOption.d.ts
- packages/switch/src/LionSwitch.js
- packages/switch/src/LionSwitchButton.js
Based on https://github.com/ing-bank/lion/discussions/1128, and inspired by https://github.com/ing-bank/lion/pull/1134, I open this PR to add the checkbox with indeterminate state.
What is different from https://github.com/ing-bank/lion/pull/1134 is mostly that I added the nested checkbox in the slot of the `lion-checkbox-indeterminate` instead of being siblings.
This my first PR in lion, so any feedback will be appreciated, I will update the PR based on your comments.
> feat: add checkbox indeterminate

- .changeset/long-fans-flash.md
- packages/overlays/src/utils/contain-focus.js
- packages/overlays/test/utils-tests/contain-focus.test.js
1. Observe content node children, reinsert tab detection element if children have changed but tab detection element is missing 
2. Guard disconnect tab detection el to check if the el is a child of the root element. This happens only if content node children change is observed and the tab detection element is identified as missing. It will disconnect and reconnect a containFocus, essentially re-inserting the tab detection element
> fix(overlays): reinsert missing tab detect el, don't error on disconnect

- packages/core/docs/guidelines/30-guidelines-scoped-elements.md
1. Fixed the link to @open-wc scoped elements documentation page
> Fix @open-wc scoped elements link

- .changeset/warm-beds-design.md
- packages/collapsible/demo/CustomCollapsible.js
- packages/combobox/docs/gh-combobox/gh-button.js
- packages/combobox/docs/gh-combobox/gh-combobox.js
- packages/form-core/src/FocusMixin.js
- packages/form-core/src/FormatMixin.js
- packages/form-core/src/InteractionStateMixin.js
- packages/form-core/src/LionField.js
- packages/form-core/src/choice-group/ChoiceGroupMixin.js
- packages/form-core/src/choice-group/ChoiceInputMixin.js
- packages/form-core/src/form-group/FormGroupMixin.js
- packages/form-core/src/validate/ValidateMixin.js
- packages/form-core/test-suites/ValidateMixin.suite.js
- packages/form-core/test/validate/Validator.test.js
- packages/input-amount/src/LionInputAmount.js
- packages/input-date/src/LionInputDate.js
- packages/input-datepicker/src/LionInputDatepicker.js
- packages/input-range/src/LionInputRange.js
- packages/input-stepper/src/LionInputStepper.js
- packages/input/src/LionInput.js
- packages/select-rich/src/LionSelectRich.js
- packages/textarea/src/LionTextarea.js
1.  Removed "ts-expect-error" annotations for lit static get properties
2. Type annotated lit static get properties with "type {any}"
Context on the changes: the actual properties are class fields that get defined e.g. in the constructor where we set a default value. The static get properties is just "configuring" and has no real special meaning beyond configuring lit.
> chore: remove @ts-expect-error & add @type {any} to  static get props

- .changeset/forty-taxis-lay.md
- docs/docs/systems/overlays/configuration.md
- packages/input-datepicker/test/lion-input-datepicker.test.js
- packages/overlays/package.json
- packages/overlays/src/OverlayController.js
- packages/overlays/test-helpers.js
- packages/overlays/test-helpers/mimicClick.js
- packages/overlays/test/OverlayController.test.js
- packages/select-rich/test/lion-select-rich.test.js
1. Updated Overlaycontroller to add/remove mousedown events instead of click for "outside clicks"
2. Added & updated relevant tests
fixes https://github.com/ing-bank/lion/issues/920
> fix: overlay closed on mouseup

- docs/components/content/accordion/overview.md
- docs/components/content/collapsible/overview.md
- docs/components/content/progress-indicator/overview.md
- docs/components/content/tabs/overview.md
- docs/components/inputs/calendar/overview.md
- docs/components/inputs/checkbox-group/overview.md
- docs/components/inputs/fieldset/overview.md
- docs/components/inputs/form/overview.md
- docs/components/inputs/input-amount/overview.md
- docs/components/inputs/input-date/overview.md
- docs/components/inputs/input-datepicker/overview.md
- docs/components/inputs/input-email/overview.md
- docs/components/inputs/input-iban/overview.md
- docs/components/inputs/input-range/overview.md
- docs/components/inputs/input-stepper/overview.md
- docs/components/inputs/input/overview.md
- docs/components/inputs/listbox/overview.md
- docs/components/inputs/radio-group/overview.md
- docs/components/inputs/select-rich/overview.md
- docs/components/inputs/select/overview.md
- docs/components/inputs/textarea/overview.md
- docs/components/interaction/button/overview.md
- docs/components/interaction/dialog/overview.md
- docs/components/interaction/switch/overview.md
- docs/components/interaction/tooltip/overview.md
- docs/components/navigation/pagination/overview.md
- docs/components/navigation/steps/overview.md
1. Removed lion-specific component namings from overview.md files
2. Minor changes to description text of overview.md files
2. Fixed a couple small linting errors
> chore: remove lion-specific component namings from overview files

- .changeset/four-days-pull.md
- packages/combobox/src/LionCombobox.js
- packages/combobox/test/lion-combobox.test.js
- packages/listbox/test-suites/ListboxMixin.suite.js
replaces https://github.com/ing-bank/lion/pull/1214
closes https://github.com/ing-bank/lion/issues/1209
> fix(combobox): displayoverlay on keydown event

- .changeset/curly-lamps-cheer.md
- packages/form-core/src/FormatMixin.js
- packages/form-core/test-suites/FormatMixin.suite.js
- packages/form-core/types/FormatMixinTypes.d.ts
closes https://github.com/ing-bank/lion/issues/1298
The test structure was a bit rearranged (to avoid merge conflicts with an upcoming merge request), the added test for this merge request: 
```js
it('does not preprocess during composition', async () => {
const el = /** @type {FormatClass} */ (await fixture(html`
<${tag} .preprocessor=${(/** @type {string} */ v) => v.replace(/\$$/g, '')}>
<input slot="input">
</${tag}>
`));
const preprocessorSpy = sinon.spy(el, 'preprocessor');
el._inputNode.dispatchEvent(new Event('compositionstart', { bubbles: true }));
mimicUserInput(el, '`');
expect(preprocessorSpy.callCount).to.equal(0);
// "à" would be sent by the browser after pressing "option + `", followed by "a"
mimicUserInput(el, 'à');
el._inputNode.dispatchEvent(new Event('compositionend', { …
```
> fix(form-core): do not preprocess during composition

- .changeset/cold-spies-press.md
- packages/form-core/src/choice-group/ChoiceGroupMixin.js
- packages/form-core/src/form-group/FormGroupMixin.js
- packages/form-core/src/registration/FormRegistrarMixin.js
- packages/form-core/test-suites/form-group/FormGroupMixin.suite.js
- packages/form-core/types/registration/FormRegistrarMixinTypes.d.ts
- packages/form-integrations/test/form-integrations.test.js
- packages/form-integrations/test/helpers/umbrella-form.js
see https://github.com/ing-bank/lion/issues/1241
Assume this code:
`<lion-form .serializedValue="${{ x: 'y' }}">
<lion-radio-group name="x">
<lion-radio>`
`lionForm.dirty` became `true` on init, whereas it should be `false`...
This was because the initial `.serializedValue` was scheduled until after `registrationComplete`, just like `__initInteractonStates()`.
Since the latter was scheduled and executed first, the inital radio value caused the `dirty` state of the form to change.
- first, wait for registrationComplete to resolve.
- then resolve `initComplete` that guarantees all initial logic affecting children has run. The `__initInteractonStates` can wait for this Promise and everything works as expected.
- all registration logic is put in one mixin: FormRegistrarMixin
- …
> chore(form-core): fix prefilled FormGroups

- docs/_assets/style.css
- docs/_assets/variables.css
1. [x] P: Purple on white gives a contrast ratio of 4.3:1. On grey it's 3.7:1. That's less than the required 4.5:1 for small text P: Found text is using color only to be recognized. S: Make it bold
2. [x] P: Image in search has no alt (invalid HTML) S: Set alt to function of image (search)
3. [x] P: Accessible name: "rocket search". S: Change name to search
4. [x] P: There's no indication of the current page. S: Use aria-current and different styling on the current page
5. [x] P: Focus on logo-link practically invisible S: Add padding 2px to sidebar-nav.
6. [x] P: The follow guides-link (CTA) has small text and a contrast ratio of less than 4.5:1 with the background. S: Pick a different color combination.
7. [x] P: "see components" does not have a visual focus state S: Change styling to …
> Apply all a11y improvements on new branch

- .changeset/friendly-pianos-pay.md
- .changeset/wicked-games-dress.md
- docs/components/inputs/input-amount/features.md
- packages/form-core/src/FormatMixin.js
- packages/form-core/src/NativeTextFieldMixin.js
- packages/form-core/test-suites/FormatMixin.suite.js
- packages/form-core/types/FormatMixinTypes.d.ts
- packages/form-core/types/NativeTextFieldMixinTypes.d.ts
- packages/input-amount/src/LionInputAmount.js
closes https://github.com/ing-bank/lion/issues/404
(fixing 404s...)
Pasted “400,0” gets instantly formatted
> feat(form-core): support paste functionality in FormatMixin

- docs/docs/systems/form/features.md
I was seeking for exactly this example, just noticed it. Thanks for the Umbrella form, it's really valuable :)
> Typo in `mulipleChoice`

- .changeset/dull-geckos-fail.md
- packages-node/providence-analytics/index.js
- packages-node/providence-analytics/package.json
- packages-node/providence-analytics/src/program/analyzers/find-exports.js
- packages-node/providence-analytics/src/program/analyzers/find-imports.js
- packages-node/providence-analytics/src/program/analyzers/helpers/Analyzer.js
- packages-node/providence-analytics/src/program/services/QueryService.js
When boolean `isDebugEnabled` is provided to main providence method, you will see the path it traverses within analyzers in your console
> fix(providence): add entries for debugging

- .changeset/short-llamas-share.md
- packages/form-core/src/FocusMixin.js
- packages/form-core/src/LionField.js
- packages/form-core/src/NativeTextFieldMixin.js
- packages/form-core/test/FocusMixin.test.js
- packages/form-core/test/FormControlMixin.test.js
- packages/form-core/types/FocusMixinTypes.d.ts
- packages/listbox/src/LionListbox.js
closes https://github.com/ing-bank/lion/issues/1206
Basically, leaves the choice to do progressive enhancement to the consumer:
- for progressive enhancement, do nothing
- otherwise, just load the polyfill in the index of your app
> feat(form-core): add [focused-visible] when matching :focus-visible

- .changeset/wet-crabs-shop.md
- docs/components/inputs/combobox/features.md
- packages/combobox/src/LionCombobox.js
- packages/combobox/test/lion-combobox.test.js
This PR aims to fix this discussion: https://github.com/ing-bank/lion/discussions/1247
> feat: add _getTextboxValueFromOption method

- docs/guides/principles/definitions-and-terms.md
Fix documentation to specify private methods and properties, rather than protected, with two underscores.
1. Changed the word `protected` under the `Private` heading to the word `private`.
> Fix typo under Private heading of definitions

- packages-node/publish-docs/index.d.ts
- packages/calendar/index.d.ts
1. they were probably committed by accident and are blocking the release CI because of this tsc error
```
error TS5055: Cannot write file '/home/runner/work/lion/lion/packages-node/publish-docs/index.d.ts' because it would overwrite input file.
error TS5055: Cannot write file '/home/runner/work/lion/lion/packages/calendar/index.d.ts' because it would overwrite input file.
```
> chore: remove generated type files from git

- .changeset/mighty-cars-grow.md
- packages/localize/src/LocalizeManager.js
- packages/localize/test/LocalizeManager.test.js
Long running imports were polluting newly reset storage (#1376)
1.  When the promise is fulfilled, it is checked if it's still in the .__namespaceLoaderPromisesCache before calling addData.
> Race condition in LocalizeManager

- .changeset/beige-students-vanish.md
- docs/components/inputs/combobox/features.md
- packages/combobox/src/LionCombobox.js
- packages/combobox/test/lion-combobox.test.js
Added some logic to better handle the autocompletion when options changed (use case of a server interaction).
Fixes #1395
See https://github.com/ing-bank/lion/pull/1398 for the initial PR (closed due to git history issues...)
> fix: better support when options change dynamically

- .changeset/cool-lemons-search.md
- .changeset/curly-ants-beg.md
- .changeset/giant-deers-poke.md
- .changeset/weak-pears-sing.md
- packages-node/rocket-preset-extend-lion-docs/preset/extendLionDocs.js
- packages-node/rocket-preset-extend-lion-docs/src/generateExtendDocsConfig.js
- packages-node/rocket-preset-extend-lion-docs/test-node/fixtures/core/@lion/core/index.js
- packages-node/rocket-preset-extend-lion-docs/test-node/fixtures/core/@lion/core/package.json
- packages-node/rocket-preset-extend-lion-docs/test-node/fixtures/core/@lion/core/src/calculateSum.js
- packages-node/rocket-preset-extend-lion-docs/test-node/fixtures/export-map-json/@lion/accordion/exports.json
- packages-node/rocket-preset-extend-lion-docs/test-node/fixtures/export-map-json/@lion/accordion/index.js
- packages-node/rocket-preset-extend-lion-docs/test-node/fixtures/export-map-json/@lion/accordion/lion-accordion.js
- packages-node/rocket-preset-extend-lion-docs/test-node/fixtures/export-map-json/@lion/accordion/src/LionAccordion.js
- packages-node/rocket-preset-extend-lion-docs/test-node/fixtures/multi-line/@lion/core/index.js
- packages-node/rocket-preset-extend-lion-docs/test-node/fixtures/multi-line/@lion/core/package.json
- packages-node/rocket-preset-extend-lion-docs/test-node/fixtures/no-node-modules-scope-folder/accordion/index.js
- packages-node/rocket-preset-extend-lion-docs/test-node/fixtures/no-node-modules-scope-folder/accordion/lion-accordion.js
- packages-node/rocket-preset-extend-lion-docs/test-node/fixtures/no-node-modules-scope-folder/accordion/package.json
- packages-node/rocket-preset-extend-lion-docs/test-node/fixtures/no-node-modules-scope-folder/accordion/src/LionAccordion.js
- packages-node/rocket-preset-extend-lion-docs/test-node/generateExtendDocsConfig.test.js
```js
export {
// HTML,
calculateSum,
offsetValue,
} from './src/helpers.js';
```
> feat: extend lion docs improvements

- .changeset/mean-garlics-occur.md
- packages/calendar/src/LionCalendar.js
> fix(calendar): add support for using language subtag only

- .changeset/short-rockets-fail.md
- packages-node/rocket-preset-extend-lion-docs/src/remarkExtendLionDocsTransformJs.js
- packages-node/rocket-preset-extend-lion-docs/test-node/remarkExtendLionDocsTransformJs.test.js
1. Replace tags in html stories when extending
> fix(rocket-preset-extend-lion-docs): handle html stories

- .changeset/sour-oranges-matter.md
- docs/docs/systems/localize/features.md
- packages/form-core/src/validate/ValidateMixin.js
- packages/form-integrations/test/form-validation-integrations.test.js
- packages/localize/src/LocalizeManager.js
fixes https://github.com/ing-bank/lion/issues/1446
> fix(localize,form-core): wait for localize before updating feedback

- .changeset/thin-bulldogs-warn.md
- packages/form-core/src/NativeTextFieldMixin.js
- packages/form-core/test-helpers/getFormControlMembers.js
- packages/form-core/test-suites/NativeTextFieldMixin.suite.js
- packages/form-core/test-suites/index.js
- packages/form-core/test/NativeTextFieldMixin.test.js
- packages/input/test/input-integrations.test.js
- packages/textarea/test/lion-textarea-integrations.test.js
> fix(form-core): only preserve caret if value changed

- docs/components/interaction/tooltip/features.md
When checking these docs to extend tooltip arrow, I realized after scratching my head a lot, that my arrow wasn't looking right because I was missing the arrow__graphic classname ;)
> chore: add missing arrow__graphic class to docs

- .changeset/long-eels-guess.md
- .changeset/soft-snakes-decide.md
- docs/components/inputs/input-amount/features.md
- packages/input-amount/src/LionInputAmount.js
- packages/input-amount/test/lion-input-amount.test.js
- packages/localize/types/LocalizeMixinTypes.d.ts
1. Add missing types to localize mixin type definition
2. Make input-amount reformat when locale changes
3. Add locale property and make input-amount respond properly when it is used
> Input amount locale

- .changeset/chatty-clocks-sleep.md
- docs/components/inputs/input-iban/features.md
- packages/input-iban/src/validators.js
- packages/input-iban/test/validators.test.js
Accepting an array for IsNotCountryIBAN was a contribution accepted a while ago. We never got to implementing the same feature for the reverse validator, and I ran into a use case where I actually wanted to show how to enforce IBANs to only BeNeLux countries which might be a common use case, and wasn't able to do it without creating my own validator.
So I implemented it :)
> feat(input-iban): allow array for IsCountryIBAN validator

- .changeset/olive-seas-promise.md
- packages-node/babel-plugin-extend-docs/src/handleImports.js
- packages-node/babel-plugin-extend-docs/test-node/babelPluginExtendDocs.test.js
- packages-node/babel-plugin-extend-docs/test-node/helpers.js
- packages-node/rocket-preset-extend-lion-docs/package.json
- packages-node/rocket-preset-extend-lion-docs/src/remarkExtendLionDocsTransformJs.js
- packages-node/rocket-preset-extend-lion-docs/test-node/remarkExtendLionDocsTransformJs.test.js
- yarn.lock
1. Support usage of import assertions like `import style from 'my-pkg/style' assert { type: 'css' };`
> feat: add support to use import assertions

- .changeset/unlucky-cameras-joke.md
- packages/calendar/test/lion-calendar.test.js
- packages/form-core/src/validate/ValidateMixin.js
- packages/form-core/test-suites/ValidateMixinFeedbackPart.suite.js
- packages/form-integrations/test/form-validation-integrations.test.js
- packages/localize/src/LocalizeManager.js
- packages/localize/src/LocalizeMixin.js
- packages/localize/test-helpers/fake-imports.js
- packages/localize/test/LocalizeMixin.test.js
- packages/localize/types/LocalizeMixinTypes.d.ts
See changeset, it explains it in more detail. Hopefully the test I added also shows why it is more user-friendly this way. Mostly, `localize.msg()` calls may fail when called directly after locale switches where the new locale is still loading. now this is fixed :)
> feat(localize): await loadingComplete before sending locale changed

- .changeset/odd-fans-clap.md
- packages/input-datepicker/index.js
Let me know if you guys think it makes sense to export this or to expect subclassers to always write their own from scratch
> feat(input-datepicker): export calendar overlay frame

- .changeset/strong-icons-argue.md
- packages-node/remark-extend/package.json
- packages-node/remark-extend/src/remarkExtend.js
- packages-node/remark-extend/test-node/fixtures/import-table.md
- packages-node/remark-extend/test-node/remark-extend.test.js
1. Support GitHub Flavored Markdown (gfm) tables when importing markdown
> fix(remark-extend): support importing of tables

- .changeset/purple-ways-shout.md
- packages-node/babel-plugin-extend-docs/src/babelPluginExtendDocs.js
- packages-node/babel-plugin-extend-docs/test-node/babelPluginExtendDocs.test.js
1. Replace `scopedElements` keys (= tag names) when extending
> fix(babel-plugin-extend-docs): handle scopedElement renames

- .changeset/thirty-dryers-listen.md
- packages/button/package.json
1. Add files that result in customElements.define to sideEffect so build tools don't tree shake them
2. This also fixes our not working demos on the lion docs side (for example https://lion-web.netlify.app/components/interaction/button/overview/)
> fix(button): register element registration side effects

- .changeset/perfect-bags-compare.md
- packages/switch/src/LionSwitchButton.js
- packages/switch/test/lion-switch-button.test.js
1. Make key handler methods protected. People may want to disable some of the keys, maybe add their own keys, etc.
2. By default also allow arrow keys to toggle the switch (but now overridable by subclassers), I think this is a better default especially given the visual cue of a switch which goes from one direction to another, therefore arrow keys make sense as interaction handlers for that. Often, ArrowUp gets paired with ArrowRight (on) in this case, and ArrowDown with ArrowLeft (off)
> feat(switch): make key handlers protected, enable arrow keys

- docs/components/content/tabs/overview.md
1. Removed an errant `;` from the Tabs npm install instructions
> remove errant semicolon from tabs npm install step

- .changeset/swift-cups-tease.md
- packages/textarea/src/LionTextarea.js
https://lit-and-friends.slack.com/archives/CJGFWJN9J/p1636110255076200
https://bugzilla.mozilla.org/show_bug.cgi?id=1739079
> fix(textarea): firefox bug with disabled textarea drag

- .changeset/cuddly-ties-repeat.md
- package.json
- packages/core/index.js
Bundlesize core went <11kb to 11.3 kb and all <46kb to 46.06KB, kinda makes sense when adding 4 directives to the re-exports I think :)
> feat(core): export latest added lit directives

- .changeset/short-horses-run.md
- packages/overlays/src/OverlaysManager.js
- packages/overlays/src/globalOverlaysStyle.js
1. Found that the global-overlays-scroll-lock-ios-fix sets position: fixed on the body. 
2. Found out that iOS does not like that, and how to fix it : [Stackoverflow](https://stackoverflow.com/questions/69589924/ios-15-minimized-address-bar-issue-with-fixed-position-full-screen-content)
3. Fix it by applying height: 100vh; to the <html> root element in the same way the other iOS fix is applied.
> Fix black bars on dialogs with preventsScroll enabled on ios 15

- .changeset/brown-dodos-own.md
- packages-node/providence-analytics/src/program/analyzers/helpers/track-down-identifier.js
- packages-node/providence-analytics/test-node/program/analyzers/helpers/track-down-identifier.test.js
1. Small addition on top of https://github.com/ing-bank/lion/pull/1519 . Will replace that pr
> fix(providence): correctly handle exports like "const x=3; export {x};"

- .changeset/fast-trees-prove.md
- packages/localize/src/LocalizeManager.js
- packages/localize/test/LocalizeManager.test.js
Whenever a language is missing a translation for a key, it currently shows an empty string. I would like the option to show the translation key instead. This is not only making it visible for developers that some translation is missing, but could potentially even be descriptive enough for users to figure out what it should say (at least more than an empty string) so they can continue their work for the time being.
> feat(localize): add option to show the key when a locale is missing a translation

- yarn.lock
1. bump versions in lock file to please dependabot
2. this will get rid of probably half of the dependeabot alerts
> chore: bump versions in lock file to please dependabot

- .changeset/clever-tables-bow.md
- .changeset/fair-adults-carry.md
- docs/components/content/tabs/features.md
- packages/tabs/src/LionTabs.js
- packages/tabs/test/lion-tabs.test.js
1. Added a function to retrieve the next available index of a not-disabled tab. Depending on the keyboard direction, the next available not-disabled tab will be selected.  
3. Added tests to ensure disabled tabs are skipped with [arrow-right]/[arrow-down] and [arrow-left]/[arrow-up].
Currently, any disabled tabs within a tab list are still selectable. A user shouldn't be able to interact with a disabled tab – please see a minimal reproduction [here](https://codesandbox.io/s/lion-tabs-disabled-attr-issue-nwrzu?file=/src/index.js). 
Unfortunately,  adding an early return if the next tab element is disabled will not cover all edge cases (as originally mentioned in the Slack channel). We could have instances where there are disabled tabs in varying orders within the tab list. …
> fix(tabs): prevent selection of disabled tabs.

- .changeset/grumpy-lemons-repeat.md
- packages/overlays/src/OverlayMixin.js
- packages/overlays/types/OverlayMixinTypes.d.ts
- packages/select-rich/src/LionSelectRich.js
1.  The type for `open`, `close` and `toggle` of the overlayMixin were incorrect, because the functions are async. That means that the return type should be `Promise<void>` instead of `void`.
1. Removed type import as it was not used.  
1. Removed the `toggle` from `LionSelectRich` as this can be handled by the `overlayMixin` now (as the TODO states).
There are 2 failing tests that already failed before I started, so I assume my changes do not have effect on those tests. Let me know if I have to make them work in order to get this pull request merged. Also, let me know if I messed something up :)
> fix: type info in OverlayMixinTypes

- docs/docs/systems/overlays/overview.md
The event-name to close an overlay was wrong in a docs page. This PR just corrects the name.
I also checked for other occurrences where this name might be wrong, but I couldn't find any.
> chore(docs): correct event-name to close overlay

- .eslintrc.js
- package.json
- scripts/lint-versions.js
Sooo after we merged the last PR, in the release workflow we would run changeset version which bumps `@lion/core`.
lint-versions was ran afterwards on precommit and started complaining, because it decided 0.21.1 was not okay with ^0.21.0, however, this should be okay because we use caret.
I adjusted the script to do a `semver.satisfies` which takes the version (0.21.1) and checks if it satisfies the range (^0.21.0).
There is also a situation where two ranges are compared, e.g. when root package.json has a devDependency and a subpackage has that same dependency (but as a real dependency), e.g. semver ^7.1.3 and ^7.3.5. 
I'm not sure if we're supposed to be comparing them, but I guess it's a good practice to have them aligned from semver perspective.
In this case, you can convert both …
> chore: lint-versions to do semver satisfy check

- .changeset/tender-rockets-vanish.md
- packages/validate-messages/src/loadDefaultFeedbackMessages.js
- packages/validate-messages/translations/en-PH.js
1. Fixed default date validation message for `en-PH`.
Please let me know if I missed some files.
> fix(lang): fix default en-PH date validation message

- docs/components/input/use-cases.md
1. Added a section under `components/input/use-cases/` that displays an example on how to use the `label-sr-only` attribute on an input element.
closes https://github.com/ing-bank/lion/issues/1630
> chore: add eg for label-sr-only attribute on input element

- .changeset/real-yaks-float.md
- docs/blog/lion-without-polyfills.md
- packages/combobox/index.d.ts
- packages/core/package.json
- packages/form-core/src/validate/ValidateMixin.js
- packages/listbox/src/ListboxMixin.js
- packages/select-rich/src/LionSelectRich.js
- packages/switch/src/LionSwitch.js
- yarn.lock
BREAKING CHANGE: Work without polyfill if possible
When using [component composition](https://lit.dev/docs/composition/component-composition/) in a Lion Component we always made it very explicit which sub-components are used.
On top of that we scoped these [sub components](https://open-wc.org/docs/development/scoped-elements/) to the [current shadow root](https://github.com/WICG/webcomponents/blob/gh-pages/proposals/Scoped-Custom-Element-Registries.md) allowing multiple version to be used simultaneously.
To enable this features we relied on the fact that the `ScopedElementsMixin` did loaded the needed polyfill for us.
We however over time got feedback from multiple consumers that lion components "break the app as soon as you load them".
The reasons is/was that not everyone is always using …
> feat: update to @open-wc/scoped-element not needing a polyfill

- docs/fundamentals/systems/form/validate.md
- packages/form-core/src/validate/Validator.js
1. Added an example of a new Validator class that returns an enum instead of a boolean value.
closes [#1631](https://github.com/ing-bank/lion/issues/1631)
> chore: add eg for validator class that returns enum

- .changeset/tender-otters-shake.md
- docs/components/form/use-cases.md
- packages/form-core/src/validate/ValidateMixin.js
- packages/form-core/test-suites/ValidateMixinFeedbackPart.suite.js
Co-authored by: Gerjan van Geest <gerjan.van.geest@ing.com>
1. Check if the modeValue is empty to reset the validators after a form `reset` button click
2. Add test for this case
3. Refactor code to keep __isEmpty from being called more times, causing existing tests to fail
> fix: do not show ResultValidator feedback message if input field is empty

- .changeset/rotten-birds-call.md
- packages/input-tel-dropdown/src/LionInputTelDropdown.js
- packages/input-tel-dropdown/test-suites/LionInputTelDropdown.suite.js
- packages/input-tel-dropdown/test-suites/index.js
1. Export the testSuite
2. Sync disabled state to dropdown (for a11y)
3. Set dropdown disabled if input is readonly (for a11y)
> fix(input-tel-dropdown): sync disabled state to dropdown

- .changeset/pretty-mice-beam.md
- packages/ajax/src/cacheManager.js
- packages/ajax/src/interceptors/cacheInterceptors.js
- packages/ajax/test/cacheManager.test.js
- packages/ajax/test/interceptors/cacheInterceptors.test.js
- packages/ajax/types/types.d.ts
1. Added "contentTypes" parameter to CacheOptions
2. Disabled cache writing / reading based on said parameter
3. Moved some things around in the cacheInterceptors test
> feat: content-type filter for ajax cache

- .changeset/hungry-mirrors-stare.md
- packages/form-core/src/registration/FormRegistrarMixin.js
- packages/form-core/test-suites/form-group/FormGroupMixin.suite.js
1. Remove check for name property as discussed with @tlouisse
> fix(lion-field): remove name property exception to align with platform

- scripts/check-npm-dist-tag.mjs
1. Add a script to verify that the npm dist tag is the same version as in the repo
Run it via
```
node ./scripts/check-npm-dist-tag.mjs
```
Outputs info like so
```
| Name                     | Local Version | NPM dist tag latest | Check |
| ------------------------ | ------------- | ------------------- | ----- |
| @lion/accordion          | 0.9.0         | 0.9.0               |   ✓   |
| @lion/ajax               | 0.15.0        | 0.15.0              |   ✓   |
| @lion/button             | 0.17.0        | 0.17.0              |   ✓   |
| @lion/calendar           | 0.19.0        | 0.19.0              |   ✓   |
| @lion/checkbox-group     | 0.20.1        | 0.20.1              |   ✓   |
| @lion/collapsible        | 0.8.0         | 0.8.0               |   ✓   |
| @lion/combobox           | …
```
> chore: add a script to check latest npm dist tags

- .changeset/mean-ducks-occur.md
Forgot to add changeset for combobox.
fix: https://github.com/ing-bank/lion/issues/1704
> fix(combobox): set no typeahead to true

- .changeset/eight-years-pump.md
- packages/overlays/src/utils/is-visible.js
- packages/overlays/test/utils-tests/get-focusable-elements.test.js
- packages/overlays/test/utils-tests/visibility.test.js
I noticed an issue in overlays, where keyboard event trapping would skip certain focusable elements. After debugging for a while, I discovered that certain elements were deemed 'not visible' and would be skipped from the traversal if `display: contents` had been set. This is because of the check that is in place to explicitly query the box model as a last check, which would give a false negative.
This is problematic for when `display: contents` is important, and definitely has visible focusable elements within it!
1. Added a check to see if `display: contents` is in the computed styles, and resolve `true`.
If anyone can think of a smarter check then I'm happy to change this. Perhaps querying the box model is not the right approach here anyway?
> fix: Allow elements with display:contents to be focusable in keyboard event trapping

- .changeset/run-forrest-run.md
- packages/ajax/src/Ajax.js
- packages/ajax/src/Cache.js
- packages/ajax/src/cacheManager.js
- packages/ajax/src/interceptors/cacheInterceptors.js
- packages/ajax/src/typedef.js
- packages/ajax/test/Ajax.test.js
- packages/ajax/test/Cache.test.js
- packages/ajax/test/cacheManager.test.js
- packages/ajax/test/interceptors/cacheInterceptors.test.js
- packages/ajax/types/types.d.ts
1. Add maxCacheSize option to cacheOptions
2. Store size with requests in the cache
3. Add size field to cache
4. Remove old entries from the cache when it is full
5. Added computing of response size from `response.blob().size` when `Content-Length` header is not available
> feat(ajax): add maxCacheSize option

- .changeset/little-melons-lay.md
- .changeset/nervous-cobras-know.md
- packages/accordion/package.json
- packages/accordion/src/LionAccordion.js
- packages/collapsible/package.json
- packages/collapsible/src/LionCollapsible.js
- packages/core/index.d.ts
- packages/core/index.js
- packages/core/src/uuid.js
- packages/form-core/package.json
- packages/form-core/src/FormControlMixin.js
- packages/helpers/index.js
- packages/listbox/package.json
- packages/listbox/src/ListboxMixin.js
- packages/switch/package.json
- packages/tabs/package.json
- packages/tabs/src/LionTabs.js
- Keep number of production deps as limited as possible
- Use @lion/helpers only for devDeps
- Clean up unused occurrences of @lion/helpers
> chore: keep prod dependencies limited and simple

- .changeset/eight-years-pump.md
- .changeset/soft-trains-brush.md
- packages/ajax/src/Ajax.js
- packages/ajax/test/Ajax.test.js
- When an interceptor returns a Response, the original request object was missing.
- When an interceptor returns a 4xx or 5xx Response, the response was returned as is instead of throwing a fetch error.
> fix(ajax): align intercepted and non-intercepted response behavior

- .changeset/grumpy-donkeys-camp.md
- packages/core/src/SlotMixin.js
Makes sure that safari doesn't throw an error when ScopedElementsMixin renderOptions are used for "offline" render of nodes.
(was not possible to test this without loading the polyfill)
> fix(core): use partial renderOptions in SlotMixin (for Safari)

- .changeset/wise-carrots-mix.md
- packages/switch/src/LionSwitch.js
- packages/switch/test/lion-switch.test.js
Intending to fix the LionSwitch throwing an error in non-lit environments:
1. Relocated setting the `role` to `'switch'` from the `constructor` to the `connectedCallback`.
2. Considering that someone else may also want to set it differently, so it only happens if it had a falsy value
3. Added a test intentionally using basic `document.createElement` instead of relaying on lit in order to trigger the bug.
> feat(switch): fix error caused by setting role in constructor (fixes #1740)

- .changeset/mighty-frogs-wave.md
- packages/form-core/types/validate/validate.d.ts
I have extended the return type of getMessage in the validator to support string and Element types.
> fix: getMessage return type supports string and Element

- docs/_assets/style.css
@gerjanvangeest in order to fix the combobox example demos (and basically all demos that inherit portal styles in light dom inside mdjs-preview), I reset all css to initial values.
Added:
```css
.markdown-body mdjs-preview > [slot='story'],
.markdown-body mdjs-preview > [slot='story'] :where(img, button) {
all: initial;
}
.markdown-body mdjs-preview > [slot='story'] {
/** keep user-agent behaviors for browser elements */
display: revert;
/** relevant inherited props (like font styles) should be kept */
font-family: inherit;
font-size: inherit;
color: inherit;
}
```
> chore: reset light dom styles in mdjs-preview

- .changeset/sweet-bags-listen.md
- README.md
- docs/guides/how-to/get-started.md
1. As discussed with @daKmoR and @narzac, let's release version 1 of the ajax library
2. Fixed a few references in the docs to the old `ajax.get` syntax
> chore(ajax): bump to major version 1.0.0

- .changeset/rare-tomatoes-kiss.md
- packages/input-amount/test/lion-input-amount.test.js
- packages/localize/src/number/formatNumberToParts.js
- packages/localize/src/number/getDecimalSeparator.js
- packages/localize/src/number/parseNumber.js
- packages/localize/test/number/getDecimalSeparator.test.js
- yarn.lock
1. Fix some types where we did not pass FormatNumberOptions properly
2. Pass options to getDecimalSeparator util
3. Make formatNumberToParts actually use the decimal that was passed in the format options over the default decimal computed from the locale using Intl NumberFormat
fixes https://github.com/ing-bank/lion/issues/1762 : 
```js
html`<lion-input-amount
.formatOptions="${{ locale: 'nl-NL', decimalSeparator: '.' }}"
.modelValue="${99}"
></lion-input-amount>`
// expected formatted value will be 99.00 instead of 99,00 which would be default for Dutch locale
```
> fix(input-amount,localize): make decimalSeparator formatOptions work

- .changeset/late-donkeys-collect.md
- packages/ajax/src/Ajax.js
- packages/ajax/test/Ajax.test.js
- yarn.lock
Fixes https://github.com/ing-bank/lion/issues/1763
I added a check for the content-type of the fetch response. Only if it's JSON, `fetchJson` should try to parse the response. Otherwise it should just return the response text.
> fix(ajax): don't throw on non-JSON responses in fetchJson

- .changeset/tiny-lamps-melt.md
- packages/calendar/translations/de.js
1. Updated the translation strings for calendar. It should use the correct labelling of the year navigation buttons
Translation reference:
https://translate.google.de/?sl=en&tl=de&text=previous%20year%3B%0Anext%20year&op=translate
> Fix: calendar translation de.js strings corrected

- packages/combobox/test/lion-combobox.test.js
I was unsure why 
Cabbage option isn't preselected and set to active state. I realized later it's because it goes hand in hand with autocomplete, and because the word isn't typed correct from the first letter, it's not autocompleted.
This makes more sense with the following example:
We type "d", first match is Chard, but Daikon is autocompleted and auto-selected because it's a better match, match from the first character.
I added some tests to clarify this behavior, as being intended.
> chore(combobox): add clarifying test for autocomplete/check

- .changeset/curly-tools-sin.md
- packages/singleton-manager/package.json
> fix(singleton-manager): keep "main" in package.json for older tools

- .changeset/five-dolls-begin.md
- packages/ui/components/overlays/src/globalOverlaysStyle.js
1. Disables (actually reduces to 1ms) the 300ms opacity transition in the overlay manager when the customer has the reduced motion capability enabled on its browser.
The animation is not removed, but reduced to 1ms, so everything is working as expected, but the customer won't see the transition. Also, this helps the use of visual testing (screenshot testing) when opening an element from the overlay manager suite.
> fix(overlay-manager): disable transition when reduced motion enabled

- .changeset/twenty-tomatoes-wash.md
- package-lock.json
- package.json
- packages/ui/package.json
- packages/ui/tsconfig-check-only.json
- scripts/types-correct-after-build.mjs
TS build uses jsdoc and TS files with "import { LitElement } from 'lit'"
- jsdoc compiles into "import { LitElement } from 'lit-element/lit-element.js'"
- TS output remains unchanged
These different imports (although they should both ultimately resolve to "{ LitElement } from 'lit-element/lit-element.js'")
are incompatible (not considered the same class), which leads to errors for Subclassers.
This script will make sure everything stays "import { LitElement } from 'lit'"
See: https://github.com/microsoft/TypeScript/issues/51622
> chore: fix LitElement imports in TS build output

- .changeset/tall-spiders-tie.md
- packages/ui/components/overlays/src/OverlayController.js
- packages/ui/components/overlays/test/OverlayController.test.js
overlays: make sure adopted stylesheets are not adopted twice and attached to body instead of document
> overlays: make sure adopted stylesheets are not adopted twice and attached to body instead of document

- docs/fundamentals/systems/overlays/configuration.md
- format section isTooltip
- removed trailing closing brackets which caused the error
fix for #1872
> docs: fix TemplateContentRenderError

- docs/components/button/use-cases.md
- add lion-button-reset and lion-button-submit imports fixing the usage with native form demo
buttons were not imported and therefore didn't work accordingly
fixes #1874
> docs: add reset and submit button imports

- .changeset/forty-hornets-speak.md
- packages/ui/components/localize/src/LocalizeMixin.js
1. The type of `get localizeNamespaces()` was not matching the correct type. According to the [documentation](https://github.com/ing-bank/lion/blob/master/docs/fundamentals/systems/localize/use-cases.md?plain=1#L211) and subsequent [functions](https://github.com/ing-bank/lion/blob/master/packages/ui/components/localize/src/LocalizeManager.js#L223) is  `NamespaceObject[]` the correct type
- `NamespaceObject` may not to be exported correctly from this package
> Update namespace type for localize mixin

- .changeset/cuddly-hats-beg.md
- package-lock.json
- packages/ui/components/icon/src/LionIcon.js
1. Wrap icon manager resolve icon in try-catch to catch fatal error, then console.error it (non-fatal)
In short, missing assets like images, svgs, etc. should not cause fatal errors and cause your entire program (app) to break. 
With lion, icon assets are JS files (SVG-in-JS if you will), so we should take this extra precaution in my opinion.
Another argument can be that apps might choose to create a robots.txt file where they exclude icon files. This is necessary so that crawlers (like Googlebot for Google SEO), do not hit their [crawl request limits](https://support.google.com/webmasters/thread/173793044?hl=en&msgid=173822151) due to many icons. Icons, in the end, are not necessary to render the app for indexing it. When not bundling, e.g. loading Lion (or a Lion extension) from a CDN, …
> fix(icon): non-fatal console error for missing icons

- .changeset/violet-ducks-suffer.md
- packages/ui/components/select/src/LionSelect.js
- packages/ui/components/select/test/lion-select.test.js
closes https://github.com/ing-bank/lion/issues/1580
TODO:
> fix(select): sync values with async option contents

- .changeset/clever-parrots-sniff.md
- packages/ui/components/input-amount/test/formatters.test.js
- packages/ui/components/input-date/test/lion-input-date.test.js
- packages/ui/components/localize/src/date/parseDate.js
- packages/ui/components/localize/test/date/parseDate.test.js
fix: https://github.com/ing-bank/lion/issues/1478
I tested the suggested solution inside the input-datepicker with MinMaxDate validator. But then a day before the min date was approved. With the switch to locale DateString the min date worked as expected.
Only i had a hard time to get a working test for this. I tried `.formatOptions="${{ timeZone: "America/New_York" }}"`, but this changed the modelValue date (and others) to the day before.
> fix(localize): don't set modelValue to unparseable if date has a negative timezone

- .eslintrc.js
- docs/components/form/use-cases.md
- docs/fundamentals/systems/form/use-cases.md
- docs/fundamentals/systems/overlays/assets/umbrella-form.js
- packages/ui/components/form-integrations/test/form-group-methods.test.js
- packages/ui/components/form-integrations/test/form-integrations.test.js
- packages/ui/components/form-integrations/test/helpers/umbrella-form.js
- packages/ui/docs/fundamentals/systems/overlays/assets/umbrella-form.js
- web-test-runner-browserstack.config.js
1. Added a new code convention: camelcase for all properties
2. Updated non-camelcase properties to camelcase
Initially trying out this convention in the lion codebase gave:
✖ 18 problems (18 errors, 0 warnings)
Only on 2 .test files 
So the codebase was already consistent with the "camelCase" convention. 
Therefore, we are making this more explicit by creating this new convention as an ESLint rule.
> chore: new camelCase convention for properties

- .changeset/rich-apricots-argue.md
- packages/ui/components/select-rich/src/LionSelectRich.js
- packages/ui/components/select-rich/test/lion-select-rich.test.js
1. When the overlay is shown, the "autofocus" attribute is added to _listboxNode (_inputNode) to make sure that keyboard navigation continues to work when the element is inside a bottomsheet. When the overlay is closed the attribute is removed.
2. Added test
3. Added changes
> fix:  "autofocus" attribute added to _listboxNode

- .changeset/ten-plums-notice.md
- packages/ui/exports/types/core.ts
Regretfully, I overlooked two Host types in the core in the https://github.com/ing-bank/lion/pull/1906 . Mea culpa. Fixes #1903 some more, this time for extenders who create a component that is tied to the `DisabledMixin`.
1. Added the overlooked `DisabledHost` and `DisabledWithTabIndexHost` types as well.
> fix(@lion/ui): export types necessary for type inference of core.js

- .changeset/witty-carpets-clap.md
- packages/ui/package.json
1. Added the following side effects (between scripts and dependencies, where I found them in older Lion packages):
```
"sideEffects": [
"exports/define/**/*.js",
"exports/define-helpers/**/*.js",
"exports/icon.js",
"exports/localize.js",
"exports/overlays.js"
],
```
2. Did the same change in the node_modules of our design system, and checked that indeed they fix the broken tree-shaking. All of our components now report bundle sizes similar to the pre-@lion/ui migration, including zero-import, single component imports and import everything tests.
3. Looked for the hint "singleton" in the `@lion/ui` source js files to see if any `singleton-manager` usages get caught that were not mentioned in the issue.
All the `define` and `define-helpers` were my take, not directly suggested by @tlouisse. …
> fix(@lion/ui): declare sideEffects in package.json (fixes #1915)

- .changeset/chilly-plants-cry.md
- packages/ui/components/combobox/src/LionCombobox.js
- packages/ui/components/combobox/test/lion-combobox.test.js
> fix(combobox): fix direct open and closing of the overlay on focus of empty input when showAllOnEmpty

- .changeset/eight-cooks-clap.md
- packages/ajax/src/Ajax.js
- packages/ajax/test/Ajax.test.js
1. Added a condition for checking if the content-type is not available in the response headers, then parse the JSON
2. The responses without content-type in the headers would not parse the JSON and throw an error.
> Check content-type in response headers

- .changeset/eleven-walls-vanish.md
- package-lock.json
- packages/ui/components/overlays/src/OverlayController.js
- packages/ui/components/overlays/test/OverlayController.test.js
1. Set 0 padding on wrapping dialog el
2. fix tests
Fixes this issue:
> fix(ui/overlays): set <dialog> wrapping el padding to 0

- package-lock.json
- package.json
1. Added override for transitive dependency "sharp" until `@rocket/cli` can be updated without being breaking.
> chore: a higher sharp version that can be built on Mac

- .changeset/nervous-numbers-smash.md
- packages/ui/components/input-iban/translations/de.js
IBAN is feminin in German: <https://www.duden.de/rechtschreibung/IBAN>
1. Changed spelling/grammar of the german error message for an invalid IBAN.
> Fixed grammar

- .changeset/afraid-nails-tap.md
- packages/ui/components/switch/src/LionSwitch.js
- packages/ui/components/switch/test/lion-switch.test.js
1. remove one of the two role="switch" (nested-interactive). Only leave it on the switch-button.
Fix: https://github.com/ing-bank/lion/issues/1772
Fix: https://github.com/ing-bank/lion/issues/1517
> fix(switch): remove one of the two nested role="switch"

- .changeset/soft-eagles-reply.md
- docs/components/combobox/overview.md
- docs/components/combobox/use-cases.md
- packages/ui/components/combobox/src/LionCombobox.js
- packages/ui/components/combobox/src/validators.js
- packages/ui/components/combobox/test-helpers/combobox-helpers.js
- packages/ui/components/combobox/test/lion-combobox.test.js
- packages/ui/components/combobox/test/validators.test.js
- packages/ui/components/form-core/types/choice-group/ChoiceGroupMixinTypes.ts
- packages/ui/components/listbox/test-suites/ListboxMixin.suite.js
- packages/ui/components/validate-messages/src/loadDefaultFeedbackMessagesNoSideEffects.js
- packages/ui/components/validate-messages/translations/bg.js
- packages/ui/components/validate-messages/translations/cs.js
- packages/ui/components/validate-messages/translations/de.js
- packages/ui/components/validate-messages/translations/en.js
- packages/ui/components/validate-messages/translations/es.js
- packages/ui/components/validate-messages/translations/fr.js
- packages/ui/components/validate-messages/translations/hu.js
- packages/ui/components/validate-messages/translations/it.js
- packages/ui/components/validate-messages/translations/nl.js
- packages/ui/components/validate-messages/translations/pl.js
- packages/ui/components/validate-messages/translations/ro.js
- packages/ui/components/validate-messages/translations/ru.js
- packages/ui/components/validate-messages/translations/sk.js
- packages/ui/components/validate-messages/translations/uk.js
- packages/ui/components/validate-messages/translations/zh.js
- packages/ui/exports/combobox-test-helpers.js
- packages/ui/exports/combobox.js
1. Allow unmatching values to be typed, before this returned an empty string.
2. Added an IsMatchingAnOption validator to check if the value is matching an option.
> feat(combobox): add `requireOptionMatch` flag and MatchesOption validator

- .changeset/tough-rivers-punch.md
- package-lock.json
- packages/ui/components/calendar/src/LionCalendar.js
1. lion-calendar: when determining if user interacted with a day button we no longer examine event.target but event.composedPath()[0] since it otherwise fails in Firefox 111+
(fixes #1962)
> fix: lion-calendar Firefox

- docs/components/checkbox-group/use-cases.md
1. add missing import of lion-checkbox-indeterminate to the checkbox-group docs
> chore: add missing import of lion-checkbox-indeterminate

- .npmrc
1. Make registry=https://registry.npmjs.org/ the default by adding it in .npmrc on project level
2. Update package-lock.json
> chore: make default public npm registry explicit

- .changeset/nasty-dodos-fold.md
- docs/components/input-datepicker/use-cases.md
- packages/ui/components/input-date/src/LionInputDate.js
- packages/ui/components/input-datepicker/src/LionInputDatepicker.js
- packages/ui/components/input-datepicker/test/lion-input-datepicker.test.js
1. Refactored `LionInputDate` to use only one method of date validation
2. Fixed initial date validation in `LionInputDatePicker` that caused Issue: #1812 
3. Updated `LionInputDate` tests
4. Updated `LionInputDate` docs
> Fix: LionInputDatePicker enters an endless loop on InvalidDate modelValue

- .changeset/silly-shirts-promise.md
- packages/ui/components/dialog/test/lion-dialog.test.js
- packages/ui/components/form-core/src/FocusMixin.js
- packages/ui/components/form-core/test/FocusMixin.test.js
- packages/ui/components/form-core/types/FocusMixinTypes.ts
- packages/ui/components/form-integrations/test/dialog-integrations.test.js
1. In FocusMixin synced the autofocus attribute from the host to the focusable node.
2. Added tests to ensure the sync happens if autofocus was set on the host during render or when autofocus is added or removed from the host.
> fix(form-core) sync autofocus to focusable node (fixes #1775)

- .changeset/blue-boats-arrive.md
- docs/components/calendar/use-cases.md
- docs/components/input-datepicker/use-cases.md
- packages/ui/components/calendar/src/LionCalendar.js
- packages/ui/components/calendar/src/calendarStyle.js
- packages/ui/components/calendar/src/utils/createDay.js
- packages/ui/components/calendar/src/utils/dayTemplate.js
- packages/ui/components/calendar/src/utils/getDayMonthYear.js
- packages/ui/components/calendar/test-helpers/DayObject.js
- packages/ui/components/calendar/test/lion-calendar.test.js
- packages/ui/components/calendar/test/utils/dayTemplate.test.js
- packages/ui/components/calendar/test/utils/snapshots/monthTemplate_en-GB_Sunday_2018-12.js
- packages/ui/components/calendar/types/day.ts
- packages/ui/components/input-datepicker/src/LionInputDatepicker.js
Rebased version of: https://github.com/ing-bank/lion/pull/1381
- Do not automatically force selection of a valid date
- Enables focus to disabled dates to make it more reasonable for screen readers
- Add helper functions to find next/previous/nearest enabled date
TODO:
- For disabled dates before minDate => aria-describe-by... element with "before first available date"
- For disabled dates after maxDate => aria-describe-by... element with "after last available date"
- What should happen on selection of disabled date?
Fix: https://github.com/ing-bank/lion/issues/194
> fix(calendar): focusable disabled dates

- .changeset/chilly-bananas-talk.md
- packages/ajax/src/Ajax.js
- packages/ajax/test/Ajax.test.js
We saw some errors in production environment of API calls that _did_ successfully complete, but then threw an error because `ajax` is trying to call `JSON.parse("")` on an empty string, which results in: `Uncaught SyntaxError: Unexpected end of JSON input
`.
> fix: avoid JSON.parsing empty responses

- .changeset/little-worms-exist.md
- package-lock.json
- packages/ui/components/overlays/src/ArrowMixin.js
- packages/ui/components/overlays/test/ArrowMixin.test.js
1. Add aria-hidden to overlay arrows, as discussed in #2014 
fix: #2014
> fix(overlays): add aria-hidden to arrow

- .changeset/quiet-insects-shake.md
- package-lock.json
- packages/ajax/src/Ajax.js
- packages/ajax/src/AjaxFetchError.js
- packages/ajax/test/Ajax.test.js
1. Add automatic response body parsing for fetchJson failed responses
2. Add test for manually parsing body for fetch failed responses
> feat: parsing body for failed ajax responses

- .changeset/old-camels-deliver.md
- package-lock.json
- packages/ajax/src/Ajax.js
- packages/ajax/test/Ajax.test.js
1. Fix a regression that I introduced by reading out the response. People were doing error.response.text() themselves, and now they get an error that the body stream has already been read, because in fetchJson I added the feature that it reads out the body for you and puts it on error.body already.
> fix: clone response when reading the response for error

- .changeset/hot-melons-grab.md
- package-lock.json
- packages/ajax/src/AjaxFetchError.js
- packages/ajax/test/Ajax.test.js
1. I set the `name` property of the error so that the name is preserved. Without setting the `name` property it's overwritten when calling `super`.
```js
class MyError extends Error {
constructor() {
super('My error!')
}
}
try { throw new MyError('foobar') } catch(err) { console.log(err.name) }
```
```
Error
```
Compare that with the same code where we actually set the `name` property:
```js
class MyError extends Error {
constructor() {
super('My error!')
this.name = 'MyError'
}
}
try { throw new MyError('foobar') } catch(err) { console.log(err.name) }
```
```
MyError
```
2. Added the response status code and text to the message.
> Ajax fetch error fixes

- .changeset/early-bats-dance.md
- packages/ui/components/progress-indicator/src/LionProgressIndicator.js
- packages/ui/components/progress-indicator/test/lion-progress-indicator.test.js
1. Updated the condition in removing the value attribute.
2. When the value is set to 0, currently, without this fix, the value is being removed because the condition is **!this.value || typeof this.value !== 'number'** => !0 is equal to true that's why the progress bar value is being removed (**this.removeAttribute('value')**)
3. I updated the condition to check if the value is 0, it will be accepted and the value attribute will not be removed.
4. I also added and updated the unit test. The current unit test on setting the value of the value attribute to an empty string will fail because according to this [documentation](https://lit.dev/docs/components/properties/), on the convertion for Number (attribute to property) **_If the element has the corresponding attribute, set the property to …
> fix(progress-indicator): accept 0 as a valid value

- .changeset/dull-tools-protect.md
- packages/ui/components/overlays/src/OverlayController.js
If we e.g. `import "@lion/ui/define/lion-dialog.js";`, `document.body` can be null.
`document.body` is a read-only property that gets set by the browser when it parses the HTML document.
As it's used only inside `__keepBodySize`, no need to declare `supportsCSSTypedObject` before.
> Fix undefined `document.body`

- .changeset/grumpy-buckets-hide.md
- packages/ui/components/calendar/src/utils/createMonth.js
- packages/ui/components/calendar/test/lion-calendar.test.js
- packages/ui/components/calendar/test/utils/createMonth.test.js
Modifying the Calendar component to render exactly 6 weeks every month. It stabilizes position during month navigation, eliminating the disruptive jumping behavior. 
Corresponding issue and the problem explanation: fixes #2036
> Fix: Calendar jumping size

- .changeset/khaki-wasps-worry.md
- packages/ui/components/calendar/src/LionCalendar.js
1. If other buttons outside the dataTable contains `[tabindex=0]`, then the `focusCentralDate` function may set focus to the wrong element. This fix removes that mistake.
> fix(calendar): focusCentralDate function should only use buttons inside the dates table

- .changeset/stale-tips-begin.md
- packages/ui/components/accordion/src/LionAccordion.js
- packages/ui/components/accordion/test/lion-accordion.test.js
Modifying the LionAccordion component to handle the focusin event in the invokers. The focusedIndex is always changed to the focused element and now navigating with the tab key does not confuse the arrow key navigation.
Corresponding issue and the problem explanation: fixes https://github.com/ing-bank/lion/issues/2055
> fix(lion-accordion): Navigating with tab confuses the arrow key navigation

- .changeset/late-pianos-draw.md
- packages/ui/components/calendar/src/LionCalendar.js
- packages/ui/components/calendar/test/lion-calendar.test.js
After navigating with the keyboard, when pressing enter it was not checked if the day button had been disabled or not. The corresponding tests were not covering this case, so I created a test.
Corresponding issue and the problem explanation: fixes https://github.com/ing-bank/lion/issues/2057
> fix(lion-calendar): Make disabled dates not selectable via keyboard navigation

- .changeset/pretty-glasses-invent.md
- packages/ui/components/input-datepicker/src/LionInputDatepicker.js
- packages/ui/components/input-datepicker/test/lion-input-datepicker.test.js
1. fix: https://github.com/ing-bank/lion/issues/2075
> fix(input-datepicker): only disable dates if validator is of type error

- .changeset/odd-cameras-rush.md
- packages/ui/exports/types/calendar.ts
- packages/ui/exports/types/combobox.ts
- packages/ui/exports/types/listbox.ts
- packages/ui/exports/types/localize.ts
1. export more type definitions of calendar, combobox, localize and listbox
> fix: export more type definitions

- .changeset/long-actors-trade.md
- packages/ajax/src/Ajax.js
- packages/ajax/src/index.js
- packages/ajax/test/Ajax.test.js
- packages/ajax/types/types.ts
1. The types in `packages/ajax/types/types.ts` arent reachable via the `index.d.ts`, this exports them and makes the available to import
> fix: export ajax types

- .changeset/early-steaks-attend.md
- packages/ajax/src/Ajax.js
1. Makes the return type for `fetchJson` generic instead of `Object`. I did this only for `fetchJson`, and not for `fetch`, because for `fetch` we want the actual `Promise<Response>`, and we dont do any transformation there; for `fetchJson` we try to parse the response, so it makes more sense to support a generic here
> fix: make `fetchJson` return type generic instead of `Object`

- .changeset/nine-icons-end.md
- packages/ui/components/combobox/src/LionCombobox.js
- packages/ui/components/combobox/test-helpers/combobox-helpers.js
- packages/ui/components/combobox/test/lion-combobox.test.js
The _handleAutocompletion recognized a selection in the input even if the selection was empty.
Corresponding issue and the problem explanation: fixes https://github.com/ing-bank/lion/issues/2084
> fix(combobox): Fix search issues when modifying the middle of the input word

- .changeset/nice-months-applaud.md
- packages/overlays/src/OverlayMixin.js
The `OverlayMixin` connectedCallback has some async code to initialise the `OverlayController` which (by the time the promise is resolved) can already be removed. This change will make sure the mixin won't initialise a controller if the render target is not connected anymore.
> fix(overlays): fix OverlayController being added to a target that is already removed

- packages/ajax/test/Ajax.test.js
hardcoded port of 8000 leads to failing tests when multiple local servers are running
> chore: allow ajax test to work with different dev server ports

- docs/fundamentals/systems/overlays/configuration.md
At the moment if going to https://lion-web.netlify.app/fundamentals/systems/overlays/configuration/ there are errors in the browser console as follows:
```
__mdjs-stories.js:8 Uncaught (in promise) ReferenceError: withDropdownConfig is not defined
at HTMLElement.placementLocal [as __story] (__mdjs-stories.js:8:36)
at HTMLElement.update (MdJsPreview.js:308:45)
at HTMLElement.performUpdate (reactive-element.ts:1327:14)
at HTMLElement.scheduleUpdate (reactive-element.ts:1259:17)
at HTMLElement._$Ej (reactive-element.ts:1231:25)
```
The fix remedies it.
> bugfix: import missing dependencies for configuration.md

- .changeset/unlucky-owls-search.md
- packages/ui/components/combobox/src/LionCombobox.js
- packages/ui/components/combobox/test/lion-combobox.test.js
This pull request fixes a bug which I noticed in the `lion-combobox` component. First I will describe a bug and then there will be a section with explanation regarding the PR itself.
Autocomplete feature is not being stable in multiple cases.
* Navigate to https://lion-web.netlify.app/components/combobox/use-cases/#validation (`Validation` section)
* Type `m` and wait until `Mango` autocompletion happens
* Type one more symbol `o` and wait until autocompletion disappears
* Type backspace 2 times to erase `mo`
* Type `m` and wait until `Mango` autocompletion happens
* Type one more symbol `o` and wait until autocompletion disappears
* Hit `Enter`
The autocomplete feature replaces `mo` to `Mango`
Autocompletion should not happen since there are no words in the combobox list which starts …
> fix: autocomplete for combobox

- .changeset/khaki-scissors-refuse.md
- .changeset/nice-spoons-rush.md
- packages/ui/components/core/src/browserDetection.js
- packages/ui/components/overlays/src/OverlaysManager.js
- packages/ui/components/overlays/src/utils/adopt-styles.js
- packages/ui/components/overlays/test-suites/OverlayMixin.suite.js
- packages/ui/components/overlays/test/OverlaysManager.test.js
- packages/ui/components/overlays/test/utils-tests/adopt-styles.test.js
We have detected problems on iOS 16.4 and newer versions where the overlays styles were not applied to the overlay and only the basic overlay were keep.
To test the fix we have patched it in our component and tested it with our customers and we have not detected any new error since we applied it.
We have not found a way to isolated the problem and replicate it as the problem was not happening in all the sessions, it seems some kind of race condition when applying the styles to the overlay.
To mitigate this issue I propose this PR to avoid applying the styles using adopt styles on ios devices.
> fix(adopt-styles): use traditional style on ios

- .changeset/tender-cows-exercise.md
> add changeset to currently opened pull-request

- .changeset/grumpy-bags-give.md
- packages/ui/components/localize/src/date/parseDate.js
- packages/ui/components/localize/test/date/parseDate.test.js
The date picker Autofill the wrong date starting from 1900 year when trying to enter manually for e.g. -
12/12/1 => it auto completes to 12/12/1901
12/12/2 => it auto completes to 12/12/1902... etc
So in the code `12/12/1` resulted in `new Date(1, 11, 12))` which gave `12/12/1901`.
This fix adds 2000 to all numbers below 50.
> fix(localize): parseDate by default to 2000 instead of 1900 when date is below 49

- .changeset/tender-cows-exercise.md
- packages/ui/components/validate-messages/translations/de.js
1. Fixed a typo for DE locale on validation messages
> chore: fix DE locale typo for validation messages

- .changeset/big-gifts-reflect copy 2.md
- .changeset/big-gifts-reflect copy 3.md
- .changeset/big-gifts-reflect copy.md
- .changeset/big-gifts-reflect.md
- packages-node/providence-analytics/src/program/analyzers/helpers/from-import-to-export-perspective.js
- packages-node/providence-analytics/src/program/analyzers/index.js
- packages-node/providence-analytics/src/program/core/Analyzer.js
- packages-node/providence-analytics/src/program/utils/resolve-import-path.js
- packages-node/providence-analytics/src/program/utils/swc-traverse.js
- packages-node/providence-analytics/test-node/program/utils/swc-traverse.test.js
correct export path for MatchImportAnalyzer
> fix(providence): correct export path for MatchImportAnalyzer

- .changeset/small-pumpkins-peel.md
- packages/ui/components/tabs/src/LionTabs.js
- packages/ui/components/tabs/test/lion-tabs.test.js
I modified the selectedIndex setter. Now it sets the selectedIndex only if the new value is different than the current selectedIndex.
> fix(tabs): set selectedIndex only if differ from previous selectedIndex

- .changeset/fifty-nails-cry.md
- packages/ui/components/overlays/src/configurations/visibility-trigger-partials/withHoverInteraction.js
- packages/ui/components/tooltip/test/lion-tooltip.test.js
1. When a button had a tooltip open at the moment the button got disabled, it stayed open.
> fix(tooltip): hide tooltip if the invoker gets disabled

- .changeset/hot-otters-push.md
- packages/ui/components/overlays/src/OverlayController.js
When closing an overlay, `scrollIntoView` forced the invoker element to be placed in the middle of the screen. This fix prevents the scroll if the invoker is already visible, but still scrolls it into view if needed.
Related to #1957. Existing tests still apply.
1. Replace the `scrollIntoView` [block options](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView#block) from `center` to `nearest`
> fix(overlay-controller): do not scroll to invoker if it is visible

- .changeset/swift-deers-taste.md
- packages/ui/components/validate-messages/src/getLocalizedMessage.js
- packages/ui/components/validate-messages/src/loadDefaultFeedbackMessagesNoSideEffects.js
- packages/ui/components/validate-messages/src/per-entrypoint/README.md
- packages/ui/components/validate-messages/src/per-entrypoint/loadComboboxMessagesNoSideEffects.js
- packages/ui/components/validate-messages/src/per-entrypoint/loadFormCoreMessagesNoSideEffects.js
- packages/ui/components/validate-messages/src/per-entrypoint/loadInputTelMessagesNoSideEffects.js
- packages/ui/exports/validate-messages-no-side-effects.js
For optimized bundling, it's reccommended to load feedback messages per entrypoint. For instance, when you only use form-core in your app:
```js
import { LionInputTel } from '@lion/ui/input-tel.js';
import { getLocalizeManager } from '@lion/ui/localize-no-side-effects.js';
import { loadInputTelMessagesNoSideEffects } from '@lion/ui/validate-messages-no-side-effects.js';
export class MyInputTel extends LionInputTel {
constructor() {
super();
loadInputTelMessagesNoSideEffects({ localize: getLocalizeManager() });
}
}
```
This prevents you from loading unused entrypoints like input-tel (which loads a full phone validation library) etc.
> feat: split up validate-messages per entrypoint for smarter bundling

- .changeset/two-plums-run.md
- packages/ajax/src/Ajax.js
- packages/ajax/src/interceptors/xsrfHeader.js
- packages/ajax/test/Ajax.test.js
- packages/ajax/test/interceptors/xsrfHeader.test.js
- packages/ajax/types/types.ts
- web-test-runner.config.mjs
Previously the XSRF token was added to any call to any origin.  
This is changed to only attach the token to requests that are POST/PUT/PATCH/DELETE.  
And another change is that it will validate if the request origin is the same as current origin or when the origin is in the xsrfTrustedOrigins.
This is a fix for a vulnerability found, as we inadvertently revealed the confidential XSRF-TOKEN stored in cookies by including it in the HTTP header X-XSRF-TOKEN for every request made to any host allowing attackers to view sensitive information.
> @lion/ajax: BREAKING: Only add XSRF token on mutable requests and on same origin or whitelisted origins

- .changeset/cold-pets-retire.md
- package-lock.json
- packages/ui/package.json
1. Pinned the version of `@open-wc/scoped-elements` to `2.2.0`
This is the last non-build breaking version that doesn't need `@lit/reactive-element` v2 for which AFAIK Lion is not yet ready due to using Lit v2 ATM. The issue with the `2.2.3` was that it failed type checks of some mixins.
> fix(ui): Fix multiple Lit versions - pin @open-wc/scoped-elements to 2.2.0 (#2224)

- .changeset/smooth-suits-compare.md
- packages/ui/components/core/src/SlotMixin.js
- packages/ui/components/core/test/SlotMixin.test.js
- packages/ui/components/core/types/SlotMixinTypes.ts
- packages/ui/components/input-file/src/LionInputFile.js
- packages/ui/components/input-tel-dropdown/src/LionInputTelDropdown.js
- packages/ui/components/input-tel-dropdown/test-suites/LionInputTelDropdown.suite.js
- web-test-runner.config.mjs
```ts
/**
* This is recommended to set to true always, as its behavior is usually desired and more in line with slot nodes that
* are not configured as rerenderable.
* For backward compatibility, it is set to false by default.
* When not configured, content is wrapped in a div (this can be problematic for ::slotted css selectors and for
* querySelectors that expect [slot=x] to have some semantic or (presentational) value).
*/
renderAsDirectHostChild?: boolean;
```
> feat(ui): [SlotMixin] allow to (re)render scoped elements as direct light dom child

- .changeset/spotty-clocks-hide.md
- .prettierignore
- packages/ui/components/select-rich/test-helpers/getSelectRichMembers.js
- packages/ui/components/select-rich/test/lion-select-rich-interaction.test.js
- packages/ui/components/select-rich/test/lion-select-rich.test.js
- packages/ui/exports/select-rich-test-helpers.js
1. Fixed a misleading test - more details on line comments
- Found this during fixing https://github.com/ing-bank/lion/issues/2208 but noticed that there's already a PR for it: https://github.com/ing-bank/lion/pull/2235
2. Updated `.prettierignore` to include machine-generated files
> chore: misleading test disabled select rich

- .changeset/fifty-shrimps-float.md
- packages/ui/components/select-rich/src/LionSelectRich.js
- packages/ui/components/select-rich/test/lion-select-rich.test.js
1. fixes [#2208](https://github.com/ing-bank/lion/issues/2208)
> fix(select-rich): readonly works with keyboard interaction

- .changeset/kind-clouds-kiss.md
- packages/ui/components/select-rich/src/LionSelectRich.js
- packages/ui/components/select-rich/test/lion-select-rich-interaction.test.js
1. I fixed [ArrowUp]/[ArrowDown] not setting isTriggeredByUser to true when done directly on the select-rich component, not in the listbox
> Fix select rich key interaction not setting correct isTriggeredByUser value

- .changeset/quick-seas-help.md
- packages/ajax/src/PendingRequestStore.js
- packages/ajax/src/cacheManager.js
- packages/ajax/src/interceptors/cacheInterceptors.js
- packages/ajax/test/Ajax.test.js
- packages/ajax/test/interceptors/cacheInterceptors.test.js
1. Sometimes the logged in session ID will change when processing a "pending" request before a "current" request is processed, meaning that the "current" request no longer should be cached. This PR cleans up and invalidates the request and cache if the session ID changes.
> Clean up cache properly if session ID changes

- .changeset/stupid-pandas-greet.md
- packages/ajax/test/Ajax.test.js
1. Previous to this two PRs were merged that added an option for getCacheIdentifier to be asynchronous and for the cache to be cleaned up gracefully when the session ID changed.
2. This PR adds tests for  the cache cleanup when using the new async getCacheIdentifier functionality
> Add caching tests for when getCacheIdentifier is asynchronous

- .changeset/ninety-needles-drop.md
- packages/ui/components/tabs/src/LionTabs.js
- packages/ui/components/tabs/test/lion-tabs.test.js
> fix(tabs): make tab panels focusable

- .changeset/olive-meals-explode.md
- packages/ui/components/form-core/src/FormControlMixin.js
- packages/ui/components/form-core/src/registration/FormRegisteringMixin.js
- packages/ui/components/form-core/test-suites/FormRegistrationMixins.suite.js
- packages/ui/components/form-core/test/FormControlMixin.test.js
- packages/ui/components/form-core/types/FormControlMixinTypes.ts
- packages/ui/components/form-core/types/registration/FormRegisteringMixinTypes.ts
1. Updated the behavior of the `name` attribute to convert values to `string` type
> fix(form-core): Implement conversion of name attribute value to string type

- .changeset/rude-deers-taste.md
- packages/ui/components/input-file/src/LionInputFile.js
- packages/ui/components/input-file/test/lion-input-file.test.js
1. Fixed a bug that when user adds files more than once, the model value is overwritten by the last addition but the file list grows, adding the last addition to the existing list
- Example: User added two files, `a` and `b` in a file dialog, then  added another file `c` opening a file dialog once more. The file list would have `a`, `b`, `c` but the model value would be `c`. After the fix, the model value also would be `a`, `b`, `c`.
- Tested on both dialog and drag & drop
----
> fix: add files more than once doesn't overwrite anymore

- .changeset/tender-moles-tell.md
- packages/ui/components/form/src/LionForm.js
- packages/ui/components/form/test/lion-form.test.js
closes https://github.com/ing-bank/lion/issues/2275
> fix(ui): fix focus first erroneous for listbox

- .changeset/fuzzy-poets-brake.md
- docs/components/dialog/src/external-dialog.js
- docs/components/dialog/use-cases.md
- packages/ui/components/dialog/test/lion-dialog.test.js
- packages/ui/components/overlays/src/OverlayMixin.js
1. Replaced the `Event` with `CustomEvent` to include the `opened` state in the event's detail.
2. The `CustomEvent` now also references the host element in its event target.
The `opened-changed` event previously lacked detail, and the `event.target` was `null`, making it impossible to determine the dialog's state within the event. This caused issues when attempting to control the dialog's state dynamically via the `opened` property.
A potential scenario is where a user dynamically triggers the dialog through the `opened` property, expecting to open or close the dialog accordingly. However, when the ESC key is pressed and the dialog closes, the state is not synced externally. As a result, the dialog might not reopen the next time the `opened` property is set to `true`.
By including `{ …
> opened-changed event detail exposes opened state

- package-lock.json
- package.json
Fixes https://github.com/ing-bank/lion/issues/2345
1. Updated "@custom-elements-manifest/analyzer" to version 0.10.3 (currently the latest version)
2. It was causing the malformed "API Tables" pages described in this issue: Fixes https://github.com/ing-bank/lion/issues/2345
3. I don't know why it occurred and how its fixed. Just randomly updated the dependency and it worked. 
* `package-lock.json` is updated using npm@9.5.1
> deps: update "@custom-elements-manifest/analyzer" to 0.10.3

- .changeset/olive-mirrors-grab.md
- packages/ui/components/dialog/test/lion-dialog.test.js
- packages/ui/components/input-datepicker/test/lion-input-datepicker.test.js
- packages/ui/components/overlays/src/OverlayController.js
- packages/ui/components/overlays/test/OverlayController.test.js
Add `aria-expanded` attribute to the dialog element only when it is a non-modal dialog
> fix dialog aria-expand attribute

- .changeset/fair-tables-pay.md
- packages/ui/components/input-file/src/FileHandle.js
- packages/ui/components/input-file/src/LionInputFile.js
- packages/ui/components/input-file/test/lion-input-file.test.js
1. Fix the bug that the `accept` attribute in the input field didn't work
- When the accepted extensions have `.`, the `IsAcceptedFile` validator always fails. (It tries to compare `jpg` (from the accept attirbute) and `.jpg` (from file name)
-  Quick reproduction: go to https://lion-web.netlify.app/components/input-file/use-cases/#basic-file-upload, select an accepted file then check the `hasFeedbackFor` property of the `lion-input-file` from the inspector
- When the accepted extensions doesn't have `.`, the file dialog disable those file with the extensions (`accept="jpg"` will make jpg files unselectable - actually all files become unselectible)
Apparently we officially supported extensions without `.` for the `accept` attribute, but [this is not a valid accept …
> Fix the bug that accept attribute in the input field didn't work properly

- README.md
I really find it hard to read this part:
> This makes sense as the main use case is to extend those components and if you do you do not want to override existing stylings.
Especially the part that says: "and if you do you do not want to"
Even though, after these commas I inserted, it is still hard to understand.
> Update README.md: grammatical fix

- .changeset/chilly-teachers-compare.md
- packages/ui/components/input-datepicker/src/LionInputDatepicker.js
- packages/ui/components/input-datepicker/test/lion-input-datepicker.test.js
1. Remove hard-coded formattedValue & value and make the chain-reaction of updating model value handles formatted value & value when user selects date from calendar in date picker.
> Use model value chain instead of hard-coding formatted value and value

- .changeset/serious-mails-matter.md
- packages/ui/components/calendar/src/LionCalendar.js
- packages/ui/components/calendar/test/lion-calendar.test.js
1. Add back the logic that checks the central date is available (removed from this PR: #1978 
2. Call `this.__calculateInitialCentralDate()` and `this.__createData()` in `firstUpdated` instead of `connectedCallback` because props (like `minDate`) are not assigned yet when `connectedCallback` is called.
3. Fix a few exisitng tests (check more details on the line comments)
> fix the bug that disabled date becomes central date

- .changeset/five-squids-act.md
- docs/components/accordion/index.md
- docs/components/accordion/use-cases.md
- docs/components/checkbox-group/use-cases.md
- docs/components/fieldset/use-cases.md
- docs/components/form/use-cases.md
- docs/components/input-amount/use-cases.md
- docs/components/input-date/use-cases.md
- docs/components/pagination/use-cases.md
- docs/components/select-rich/use-cases.md
- docs/components/steps/overview.md
- docs/components/steps/use-cases.md
- docs/fundamentals/systems/form/use-cases.md
- docs/fundamentals/systems/localize/use-cases.md
- docs/fundamentals/systems/overlays/use-cases.md
- package-lock.json
- packages/ui/components/accordion/src/LionAccordion.js
- packages/ui/components/accordion/test/lion-accordion.test.js
This PR adds a new property called "exclusive" , which when enabled allows only one accordion to be open at any given time.
> Exclusive accordion

- .changeset/green-chefs-live.md
- .eslintrc.cjs
- packages/ui/components/combobox/test-helpers/combobox-helpers.js
- packages/ui/components/combobox/test/lion-combobox.test.js
- packages/ui/components/combobox/test/validators.test.js
Replace `mimicUserTyping` in some tests with `sendKeys ` to unblock the [PR](https://github.com/ing-bank/lion/pull/2369) related to the overlay bug
> Fix keyboard typing

- .changeset/perfect-jeans-search.md
- packages/ui/components/calendar/src/LionCalendar.js
1. Adjusted the `firstUpdated` of LionCalendar based on other working examples (LionStep specifically).
> fix(ui/calendar): use correct firstUpdated type signature

- .changeset/happy-ducks-wink.md
- packages/ui/components/calendar/src/LionCalendar.js
- packages/ui/components/core/src/DisabledWithTabIndexMixin.js
- packages/ui/components/form-core/src/FormControlMixin.js
- packages/ui/components/form-core/src/utils/SyncUpdatableMixin.js
- packages/ui/components/icon/src/LionIcon.js
- packages/ui/components/overlays/src/OverlayMixin.js
- packages/ui/components/progress-indicator/src/LionProgressIndicator.js
- packages/ui/components/steps/src/LionStep.js
- packages/ui/components/steps/src/LionSteps.js
- packages/ui/components/tabs/src/LionTabs.js
- packages/ui/components/tooltip/src/LionTooltip.js
A simple PR that:
- improves test experience in dev-mode by limiting verbose warnings
- makes explicit which components could potentially be improved
> fix(ui): improve test experience in dev-mode

- .changeset/rude-flies-reflect.md
- .changeset/short-experts-mix.md
- packages/ui/components/overlays/src/OverlayController.js
- packages/ui/components/overlays/test-helpers/mimicClick.js
- packages/ui/components/overlays/test/OverlayController.test.js
- tsconfig.json
closes https://github.com/ing-bank/lion/pull/2198
> fix(overlays): no hiding of nested overlays having `hideOnEsc` configured

- .changeset/metal-ears-bathe.md
- packages/ui/exports/types/form-core.ts
1. Exported the missing `FocusHost` type so that component libraries can use the FocusMixin and get their type definitions correctly generated.
> fix(ui/types): export FocusHost type from types/form-core.js (fixes: #2366)

- .changeset/flat-fireants-hang.md
- docs/fundamentals/tools/ajax/overview.md
- packages/ajax/src/Ajax.js
- packages/ajax/test/Ajax.test.js
- packages/ajax/types/types.ts
1. added `addResponseJsonInterceptor` to be able to intercept parsed response JSON objects
2. added docs and tests for it
> feat(ajax): add interceptors for parsed response JSON objects

- .changeset/happy-bears-rescue.md
- .changeset/happy-toes-yell.md
- package-lock.json
- packages-node/providence-analytics/src/program/utils/optimised-glob.js
- packages-node/providence-analytics/test-node/program/utils/optimised-glob.test.js
- packages/ui/components/core/src/ScopedElementsMixin.js
- packages/ui/scripts/types-correct-after-build.js
> fix: expand script that corrects types after build

- docs/components/select/use-cases.md
- package-lock.json
1. Added documentation about updating lion-select options using the repeat directive from Lit, to fix odd user experience when using map or other types of repeating templates.
> chore: adds lion-select docs about the repeat directive

- .changeset/spotty-penguins-taste.md
- packages/ui/components/overlays/src/OverlayController.js
- packages/ui/components/overlays/test/OverlayController.test.js
In lion-overlays a blur event listener was added to window, which closes the overlay when focused outside when hidesOnOutsideClick is enabled in the overlay config.
Corresponding issue and the problem explanation: fixes https://github.com/ing-bank/lion/issues/2315
> fix(overlays): clicking outside iframe not closing the overlay

- .changeset/quiet-apricots-sneeze.md
- packages/ui/components/overlays/src/OverlayController.js
- packages/ui/components/overlays/src/OverlayMixin.js
- packages/ui/components/overlays/src/utils/adopt-styles.js
- packages/ui/components/overlays/test/OverlayController.test.js
1. Adjust the `adopt-style` styleCache to be a `WeakMap` preventing the `renderRoot`s from being garbage collected
2. Let the `OverlayMixin` unwire its `OverlayController` from the `OverlayManager` on teardown
> fix(overlays): fix memory leaks of adopt-styles and OverlayMixin (#2300)

- .changeset/late-adults-ring.md
- packages/ui/components/calendar/src/LionCalendar.js
- packages/ui/components/input-datepicker/test/lion-input-datepicker.test.js
In case the disabled dates of the calendar element in `LionInputDatepicker` changes dynamically (for instance, when two date pickers take start and end date from user, while start date changes the min value of the end date), the calendar's central date can be a disabled date and it doesn't get updated to the nearest enabled date.
This PR fixes the issue by getting nearest enabled date in case the initial central date becomes disabled.
I introduced 10ms timeout in the test. `await el.completeUpdate` nor `await el.{internal_node_getter}.completeUpdate` didn't work because the date picker waits for its child node to be updated before it calls `this._calendarNode.initCentralDate()`. I even tried to wait the calendar node to complete updates multiple times but no luck. Please enlighten me if I …
> Fix the issue that dynamically updated disabled date doesn't update the central date

- .changeset/purple-paws-scream.md
- packages/ui/components/pagination/src/LionPagination.js
- packages/ui/components/pagination/test/lion-pagination.test.js
The fix makes a text reader announce the current page when it is changed.
> fix: announce current page for pagination

- .changeset/wise-mirrors-grab.md
- .github/ISSUE_TEMPLATE/bug_report.md
- packages/ui/components/core/test/SlotMixin.test.js
- packages/ui/components/form-core/test-suites/NativeTextFieldMixin.suite.js
- packages/ui/components/form-core/test/FocusMixin.test.js
- packages/ui/components/input-tel-dropdown/test-suites/LionInputTelDropdown.suite.js
- packages/ui/components/input-tel-dropdown/test/LionInputTelDropdown.test.js
- packages/ui/components/overlays/src/OverlayController.js
- packages/ui/components/overlays/test/OverlayController.test.js
- packages/ui/components/select-rich/test/lion-select-rich.test.js
- packages/ui/components/switch/test/lion-switch.test.js
- packages/ui/components/tabs/test/lion-tabs.test.js
- warning when `.contentNode` is a shadowRoot host (as they break in Safari when tabindex of -1 is applied)
- extra hardening of tests by applying `isActiveElement` helper everywhere
- update the issue template with working stackblitz playground
closes https://github.com/ing-bank/lion/issues/2403
> fix: make sure that voiceover + safari modals are accessible

- .changeset/dirty-scissors-invent.md
- packages/ui/components/input-stepper/src/LionInputStepper.js
- packages/ui/components/input-stepper/test/lion-input-stepper.test.js
1. To make input-stepper work with NVDA we move the `role="spinbutton"` to the inputNode.
2. To make the decrease & increase buttons announce the new value, a hidden value element was created.
**Before:**
https://github.com/user-attachments/assets/051d7efd-4e19-4ba9-abee-bc5199c0dcb5
**After:**
https://github.com/user-attachments/assets/d46c6cc5-7aa9-4c8f-a7b4-9c28b75c6ccc
> fix(input-stepper): move role=spinbutton to input node

- .changeset/weak-hairs-jump.md
- packages/ui/components/combobox/src/LionCombobox.js
- packages/ui/components/combobox/test/lion-combobox.test.js
1. I added a test called `'does not flash the menu when _showOverlayCondition returns "false"` which fails in the master and works with the proposed PR. The test makes sure the overlay indeed does not flash when it is not expected
2. In some tests I replaced `return options.currentValue.length > 3 && super._showOverlayCondition(options);` with 
```js
return (
// @ts-ignore
this.__prevCboxValueNonSelected.length > 3 && super._showOverlayCondition(options)
);
```
because the tests like that do not check if the menu shows up after each letter typed and check it only after all text is typed. And at the very beginning `options.currentValue` is the whole option value like `Artichoke` which is a error.  `this.__prevCboxValueNonSelected` contains the actual value typed by that is a private …
> do not show overlay when _showOverlayCondition is "false"

- .changeset/smooth-boats-argue.md
- .changeset/tricky-suns-change.md
- .changeset/tricky-suns-changerz.md
- .github/workflows/verify-pr.yml
- packages/ui/components/combobox/test/lion-combobox.test.js
- packages/ui/components/dialog/test-helpers/test-router.js
- packages/ui/components/dialog/test/lion-dialog.test.js
- packages/ui/components/overlays/src/OverlayController.js
- packages/ui/components/overlays/src/OverlayMixin.js
- packages/ui/components/overlays/test-suites/OverlayMixin.suite.js
- packages/ui/components/select-rich/src/LionSelectRich.js
- packages/ui/components/select-rich/test/lion-select-rich.test.js
> fix(overlays): allow Subclassers to teardown at the right moment

- .changeset/cuddly-bottles-camp.md
- docs/components/dialog/use-cases.md
- docs/fundamentals/systems/overlays/configuration.md
- packages/ui/components/dialog/src/LionDialog.js
- packages/ui/components/dialog/test/lion-dialog.test.js
- packages/ui/components/overlays/src/OverlayController.js
- packages/ui/components/overlays/test/OverlayController.test.js
- packages/ui/components/overlays/types/OverlayConfig.ts
> feat(dialog): add is-alert-dialog option

- .changeset/great-pumas-rush.md
- packages/ui/components/core/src/SlotMixin.js
- packages/ui/components/core/test/SlotMixin.test.js
- packages/ui/components/input-tel-dropdown/src/LionInputTelDropdown.js
// Assume we had: { template: myBool ? html`<div id=a></div>` : html`<span id=b></span>`, renderAsDirectHostChild: true }
// If myBool started as true, <div id=a></div> would be rendered in first render above, A slot would be applied...
// However, when myBool changes to false, the <span id=b></span> would be rendered instead...
// We need to make sure that this "replaced root" gets the slot applied as well
> fix(ui/core): rerender direct host child with right slot attr when root is switched

- docs/guides/how-to/create-a-form.md
I rearranged the doc the way that is easier to extend it.  The examples are moved under `### Example of a component that renders into Light DOM` section which is easier to override when extending the docs.
> chore: update documentation for better extending

- .changeset/good-squids-love.md
- packages/ui/components/checkbox-group/src/LionCheckboxIndeterminate.js
- packages/ui/components/checkbox-group/test-suites/CheckboxIndeterminate.suite.js
- packages/ui/components/form-core/src/FocusMixin.js
- packages/ui/components/form-core/src/LionField.js
There were a few problems in the LionCheckboxIndeterminate:
1. When the element was connected, the last child was ignored because the `_setOwnCheckedState()` was called by `form-element-register` event **before** the same event was handled by the checkbox group which adds the element emitting the event to the `formElements`
2. When it had disabled child and all the other children were checked, clicking the indeterminate checkbox didn't respond, because the checked state was `false` although, in practice, it was fully checked
3. When the custom element's `indeterminate` property was `true` and the same property of the input node was also `true`, and clicking it should keep it indeterminated (like when one of the children is disabled and the others are mixed with checked and unchecked), the …
> Fix indeterminate checkbox edge cases

- README.md
Found two simple typos in README.md and corrected them accordingly.
> README.md, line 48
```diff
- - [...] Ships a functionality in it's most appropriate form.
+ - [...] Ships a functionality in its most appropriate form.
```
> README.md, line 116
```diff
- [...] the current behavior - additional adding a [...]
+ [...] the current behavior - additionally adding a [...]
```
See `files changed` to see changes in context.
> docs: Fixed two typos in README.md

- .changeset/rare-walls-lay.md
- packages/ui/components/select-rich/src/LionSelectRich.js
- packages/ui/components/select-rich/test/lion-select-rich.test.js
> fix(select-rich): block arrow key interaction when singleOption is set

- packages/ui/components/localize/types/LocalizeMixinTypes.ts
1. remove the performUpdate Method from the LocalizeMixinHost type as it as the wrong access modifier and is not used anymore.
See #2479
> fix: remove unused typed method

- .changeset/new-cobras-sort.md
- packages/ui/components/localize/src/date/parseDate.js
- packages/ui/components/localize/src/date/utils/checkYearFormat.js
- packages/ui/components/localize/test/date/parseDate.test.js
Details: The function now includes logic to correct years less than 50 by adding 2000 to the year value.
Example:
Input: parseDate('1/1/49')
Output: new Date('2049/01/01')
Details: The function now checks if the year format is correct before proceeding with date parsing.
Example:
Input: parseDate('12-12-0000')
Output: undefined
Details: Added tests to ensure the year correction and validation logic works as expected.
Test: expect(equalsDate(parseDate('1/1/49'), new Date('2049/01/01'))).to.equal(true);
> fix: bug that accepted 3 digit year

- README.md
1. L40 - There should be a comma before the conjunction and final list item.
2. L47 - Typo: Lion is "distributes" -> Lion is "distributed"
> Fix 2 issues in ReadME

- .changeset/witty-oranges-lick.md
- .github/workflows/release.yml
- .github/workflows/verify-pr.yml
- package-lock.json
- package.json
- packages/ui/CHANGELOG.md
- packages/ui/package.json
The pipeline to release 0.11.3 was failed due to outdated dependency in pipeline.
In case we need create the version PR to run the release pipeline again, I created this PR to revert the previous version PR (#2508).
> Revert version package PR

- .changeset/tall-doors-smoke.md
- packages/ui/components/form-core/src/validate/ValidateMixin.js
- packages/ui/components/form-core/test-suites/ValidateMixin.suite.js
In `ValidateMixin.js` a combination of approaches was used to determine if a `Required` validator is a `Required` validator, so that the validation routines can be executed accordingly. This involved:
- an `instanceof` approach (initial, changed later by #2397)
- a characteristics approach: by looking at `.validatorName` (introduced by #2397)
However, an `instanceof` check still remained in the `__executeValidators` function. This PR aims to unify the approach in `ValidateMixin.js`.
1. When classifying the passed validators (in `MetaValidators`, `AsyncValidators`, `SyncValidators`), both the `Required` check and the `MetaValidator` checks are now done via characteristics of each:
- the `Required` validator should have `.validatorName === 'Required'`
- the `MetaValidator` should present a …
> fix(validate-mixin): determine required or result validators based on characteristics

- .changeset/witty-geese-exercise.md
- packages/ui/components/input-tel-dropdown/src/LionInputTelDropdown.js
- packages/ui/components/input-tel-dropdown/src/regionCodeToLocale.js
- packages/ui/components/input-tel-dropdown/test-suites/LionInputTelDropdown.suite.js
- packages/ui/components/input-tel-dropdown/test/regionCodeToLocale.test.js
1. Pass full locale to `new Intl.DisplayNames` constructor.
The constructor accepts either a language (e.g. `en`, `nl`, ...) or the full locale (e.g. `en-GB`, `nl-BE`, ...).
Instead, we're passing only the region (e.g. `GB`, `BE`, ...), which is not a valid param for the constructor.
Sometimes that works because language and region are the same (e.g. `fr-FR`, `de-DE`), but that is not always the case.
- [Intl locales argument](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl#locales_argument)
- [Intl.Locale](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Locale)
If the specified locale is not recognized, the translations default to English.
1. Go to the demo of [input-tel-dropdown …
> fix(input-tel): use full locale to translate country names in dropdown

- .changeset/brown-shirts-count.md
- packages/ui/package.json
1. Updated the `@open-wc/scoped-elements` dependency to start from `3.0.6` as it transitively depends on the v2 version of the `@open-wc/dedupe-mixin`
2. Updated the `@open-wc/dedupe-mixin` direct dependency to use the latest, v2 version
Currently, there is a dependency version conflict in `@lion/ui` hindering component packs that build on top of it. In the current version of `@lion/ui`, the package explicitly depends on the v1 version of the `@open-wc/dedupe-mixin`. However, since it allows patch versions of the `@open-wc/scoped-elements` newer than `3.0.5`, recent npm installs will resolve the transitive `@open-wc/dedupe-mixin` to become v2.
Building component packs on top of `@lion/ui` typically involves generating type definitions for those components. When a more strict bundler, like …
> fix(dedupe-mixin): resolve version conflict between v1 and v2 - fixes (#2535)

- packages/ui/components/form-core/src/FocusMixin.js
- packages/ui/components/overlays/src/OverlayMixin.js
In our application, there is a very complicated logic that creates a bunch of form fields based on some data. It's very complicated, we hate that logic; but it exists, it works, and it is being used in production.
Somewhere in that logic, under a very specific case, a datepicker form field is created, connected, and then immediately disconnected. Don't ask me why, I said it is complicated.
This commit fixes a bug in OverlayMixin. The `connectedCallback` calls `_setupOverlayCtrl()` asynchronously, after a `Promise.then()`. Thus, by the time this setup function is called, the component has already been disconnected (and `disconnectedCallback()` has already been called).
The fix is simple: don't try to setup the overlay if the component is no longer connected.
> fix(overlays): don't call _setupOverlayCtrl() in OverlayMixin if the component is not connected

- .changeset/serious-toys-hug.md
- docs/fundamentals/systems/form/validate.md
- packages/ui/components/form-core/src/validate/LionValidationFeedback.js
- packages/ui/components/form-core/src/validate/ValidateMixin.js
- packages/ui/components/form-core/test-suites/ValidateMixinFeedbackPart.suite.js
- packages/ui/components/form-core/test/validate/lion-validation-feedback.test.js
- packages/ui/components/form-core/types/validate/validate.ts
1. added the option to keep the `success` type validator persistent on screen
2. moved the removal of the success message from the `LionValidateFeedback` into the `ValidateMixin`, per a TODO. 
3. added the option to configure the duration of the success message on screen, per a TODO
4. added documentation on the `success` type 
5. fixed small typos
> feat: adds display options configurability to the success validation

- .gitignore
Bring back .gitignore entries that got lost
> chore: ignore portal build files
