ing-bank/lion

- packages/core/index.js
- packages/input-iban/index.js
- packages/localize/index.js
closes https://github.com/ing-bank/lion/issues/6
> fix: add missing exports to core, input-iban, localize

- packages/field/README.md
- packages/field/docs/CustomFieldsTutorial.md
- packages/field/docs/FieldCustomMixin.md
After getting some feedback that it was hard to find documentation for creating your own custom fields, I decided to create a small guide/tutorial for it.
It will also serve as a guide when we want to build our own slider, select(dropdown listbox) and combobox/autocomplete.
> chore(field): custom fields tutorial

- package.json
- packages/input-iban/test/validators.test.js
- packages/localize/test/date/parseDate.test.js
- packages/validate/test/test-utils.js
- packages/validate/test/validators.test.js
- wallaby.js
- yarn.lock
For everyone who uses Wallaby.js this config will be very helpful.
> chore(wallaby.js): configure wallaby.js

- README.md
- packages/calendar/package.json
I forgot to update README yesterday...
> Fix calendar docs

- packages/button/src/LionButton.js
- packages/button/test/lion-button.test.js
closes https://github.com/ing-bank/lion/issues/39
> fix(button): do not override user provided tabindex

- packages/ajax/package.json
- packages/button/package.json
- packages/calendar/package.json
- packages/checkbox-group/package.json
- packages/checkbox/package.json
- packages/choice-input/package.json
- packages/core/index.js
- packages/core/package.json
- packages/field/package.json
- packages/fieldset/package.json
- packages/form-system/package.json
- packages/form/package.json
- packages/icon/package.json
- packages/input-amount/package.json
- packages/input-date/package.json
- packages/input-datepicker/README.md
- packages/input-datepicker/package.json
- packages/input-email/package.json
- packages/input-iban/package.json
- packages/input/package.json
- packages/localize/package.json
- packages/overlays/package.json
- packages/popup/package.json
- packages/radio-group/package.json
- packages/radio/package.json
- packages/select/package.json
- packages/steps/package.json
- packages/textarea/package.json
- packages/tooltip/package.json
Fixes
- translations were not published
- readme for input-datepicker
> chore: exposed '/docs' and '/translations' for all packages

- packages/calendar/test/lion-calendar.test.js
- yarn.lock
> Fix date dependent test (fixes #54)

- packages/core/package.json
- yarn.lock
fixes https://github.com/ing-bank/lion/issues/65
> fix(core): do not pin lit-html version and allow lit-element patches

- packages/localize/src/LocalizeManager.js
- packages/localize/test/LocalizeManager.test.js
Closes https://github.com/ing-bank/lion/issues/41
> Allow custom locale when loading namespaces

- packages/calendar/src/LionCalendar.js
- packages/input-datepicker/src/LionCalendarOverlayFrame.js
- packages/input-datepicker/src/LionInputDatepicker.js
- packages/input-iban/src/LionInputIban.js
- packages/validate/src/ValidateMixin.js
Replace default case for dialects
> fix(defect #100): replace default case for dialects

- packages/calendar/src/LionCalendar.js
- packages/input-datepicker/src/LionCalendarOverlayFrame.js
- packages/input-datepicker/src/LionInputDatepicker.js
- packages/input-iban/src/LionInputIban.js
- packages/validate/src/ValidateMixin.js
> Support en-PH locale for polymer-cli

- packages/overlays/README.md
- packages/overlays/docs/GlobalOverlayController.md
- packages/overlays/docs/LocalOverlayController.md
- packages/overlays/docs/OverlaySystemImplementation.md
- packages/overlays/docs/OverlaySystemScope.md
Co-authored-by: Thijs Louisse <Thijs.Louisse@ing.com>
> chore(overlays): outline doc for all overlay occurrences

- packages/input-amount/src/parsers.js
- packages/input-amount/stories/index.stories.js
- packages/input-amount/test/formatters.test.js
- packages/input-amount/test/parsers.test.js
Note: this is a reverted MR from https://github.com/ing-bank/lion/pull/110
> fix(input-amount): support negative numbers

- packages/field/src/FormControlMixin.js
- requirement 1 for Rich Select
- let's merge it all to develop and then release
> fix(field): no DomHelpers for FormControl and apply all needed mixins

- packages/field/src/FormatMixin.js
- packages/validate/src/ValidateMixin.js
- packages/validate/test/ValidateMixin.test.js
- requirement 3 for Rich Select
- let's merge it all to develop and then release
=> has 4 commits
- chore(validate): add tests for state css classes
- fix(validate): remove deprecated CssClassMixin
- fix(validate): add attributes for validation states
- fix(field): remove unused EventMixin from FormatMixin
probably easier to review them individually
> fix(validate): remove deprecated CssClassMixin

- packages/calendar/src/LionCalendar.js
- packages/calendar/translations/zh.js
- packages/input-datepicker/src/LionCalendarOverlayFrame.js
- packages/input-datepicker/src/LionInputDatepicker.js
- packages/input-datepicker/translations/zh.js
- packages/input-iban/src/LionInputIban.js
- packages/input-iban/translations/zh.js
- packages/input/stories/localize.stories.js
- packages/input/stories/translations/zh-CN.js
- packages/input/stories/translations/zh.js
- packages/overlays/translations/zh.js
- packages/validate/src/ValidateMixin.js
- packages/validate/translations/zh.js
Added translations to support chinese language
> Support Chinese language

- packages/validate/docs/tutorials/CustomValidatorsTutorial.md
Update custom validator examples
> Update custom validator docs

- packages/textarea/src/LionTextarea.js
- packages/textarea/test/lion-textarea.test.js
Update setTextareaMaxHeight to fix the bug reported on #184 
Let me know if there's anything that should be improved, I'll be glad to help and work on it :)
> Calculate max-height based on empty state

- packages/field/src/formRegistrarManager.js
- packages/input-email/stories/index.stories.js
- packages/localize/src/LocalizeManager.js
- packages/overlays/src/LocalOverlayController.js
- packages/popup/README.md
- packages/tooltip/README.md
> Cleanup references

- packages/button/src/LionButton.js
- packages/button/stories/index.stories.js
- packages/button/test/lion-button.test.js
- packages/popup/test/lion-popup.test.js
Fixes #179, #188, #210 and some other things, e.g. improves performance.
> [button] Fix IE11 bugs or bugs introduced by fixes for IE11

- packages/calendar/package.json
- packages/input-datepicker/package.json
- packages/localize/package.json
- packages/validate/package.json
> Include test-helpers dir in the released package

- packages/overlays/src/globalOverlaysStyle.js
fixes: https://github.com/ing-bank/lion/issues/220
> fix(overlays): global overlays have fixed positioning context

- packages/localize/RATIONALE.md
This is a draft, but contains quite some insights about the requirements and the decision making process for the `localize`.
> [localize] Rationale

- packages/localize/README.md
- packages/localize/test/LocalizeMixin.test.js
The documentation is currently very outdated, contains some very old APIs which are not supported, misleading recommendations and lacks some recent new features information.
> [localize] Improve documentation

- packages/input-amount/src/parsers.js
- packages/input-amount/test/parsers.test.js
fixes https://github.com/ing-bank/lion/issues/232
> fix(input-amount): return undefined for non numbers with spaces

- packages/button/src/LionButton.js
- packages/button/test/lion-button.test.js
> fix(button): make JAWS/IE11 work with inner button

- packages/field/src/FocusMixin.js
- packages/field/test/FocusMixin.test.js
https://developer.mozilla.org/en-US/docs/Web/API/FocusEvent#Browser_compatibility
> Change FocusEvent to regular Event to support IE11

- packages/field/src/FormControlMixin.js
fixes https://github.com/ing-bank/lion/issues/123
fixes https://github.com/ing-bank/lion/pull/136
> Disable input-group disabled styling if slotted el is button

- packages/button/src/LionButton.js
- packages/button/stories/index.stories.js
- packages/button/test/lion-button.test.js
fixes https://github.com/ing-bank/lion/issues/240
fixes https://github.com/ing-bank/lion/issues/249
> Fix button implicit submission on enter keypress

- packages/field/src/FormControlMixin.js
- packages/field/test/FormControlMixin.test.js
Closes [field] Feedback slots lack aria-live #190
> [field] Add aria-live=polite attribute to feedback slot

- packages/input-email/stories/index.stories.js
- packages/input-iban/stories/index.stories.js
Fix [input-email]/[input-iban] Demo's lack labels #169
> Add labels to input-email and input-iban stories

- packages/select-rich/src/LionSelectRich.js
- packages/select-rich/stories/index.stories.js
- packages/select-rich/test/lion-select-rich.test.js
- Still focusable
- Still will be serialized
- No longer able to open and change the checked option.
> [select-rich]: make readonly work

- packages/calendar/src/LionCalendar.js
- packages/calendar/test/lion-calendar.test.js
Fixes the second issue listed at: https://github.com/ing-bank/lion/issues/302
> fix(calendar): issue 302 part 2 - skipped month

- packages/button/README.md
- packages/button/src/LionButton.js
- packages/button/stories/index.stories.js
- packages/button/test/lion-button.test.js
fixes https://github.com/ing-bank/lion/issues/322
fixes https://github.com/ing-bank/lion/issues/316
> fix(button): remove submit() on click

- packages/localize/src/date/formatDate.js
- packages/localize/stories/date.stories.js
- packages/localize/test/date/formatDate.test.js
also added test cases and storybook demo.
> fix: [localize] date formatting forced #296

- packages/steps/src/LionStep.js
- packages/steps/src/LionSteps.js
- packages/steps/test/lion-steps.test.js
closes: https://github.com/ing-bank/lion/issues/323, https://github.com/ing-bank/lion/issues/324
> fix(steps): steps.current should be update before @Enter

- packages/input-amount/stories/index.stories.js
> fix(input-amount): add demo how to show no fractions

- packages/field/src/FormRegisteringMixin.js
fixes https://github.com/ing-bank/lion/issues/283
> fix(field): teardown registrarmanager listener on field after register

- CONTRIBUTING.md
- README.md
Updating docs for our new feature request approach
> chore: update docs for closing feature requests

- packages/select-rich/src/LionSelectRich.js
- packages/select-rich/test/lion-select-rich.test.js
> fix(lion-select-rich): keep showing selected item dynamic options bug

- packages/button/src/LionButton.js
- packages/button/test/lion-button.test.js
- packages/calendar/test/lion-calendar.test.js
- packages/checkbox-group/test/lion-checkbox-group.test.js
- packages/icon/test/lion-icon.test.js
- packages/input-amount/test/lion-input-amount.test.js
- packages/input-date/test/lion-input-date.test.js
- packages/input-datepicker/test/lion-input-datepicker.test.js
- packages/input-email/test/lion-input-email.test.js
- packages/input-iban/test/lion-input-iban.test.js
- packages/input/test/lion-input.test.js
- packages/overlays/src/OverlayController.js
- packages/radio-group/test/lion-radio-group.test.js
- packages/select-rich/test/lion-select-rich.test.js
- packages/select/test/lion-select.test.js
- packages/textarea/test/lion-textarea.test.js
- packages/tooltip/test/lion-tooltip.test.js
Start for #293 and making it pass.
> feat: integrate and pass automated a11y testing

- packages/calendar/src/LionCalendar.js
- packages/calendar/test/lion-calendar.test.js
> fix(catalog): add info for next/previous month on to the buttons

- packages/form/src/LionForm.js
- packages/form/stories/index.stories.js
- packages/form/test/lion-form.test.js
fixes  https://github.com/ing-bank/lion/issues/336
> fix(form): event order of reset and submit

- packages/fieldset/src/LionFieldset.js
- packages/fieldset/test/lion-fieldset.test.js
Fixes https://github.com/ing-bank/lion/issues/405
> fix(fieldset): wait for registration before setting values

- packages/input-datepicker/src/LionInputDatepicker.js
- packages/input-datepicker/stories/index.stories.js
- packages/input-datepicker/test/lion-input-datepicker.test.js
Improved MR of https://github.com/ing-bank/lion/pull/375
> fix(datepicker): focus on selected date on opening

- packages/textarea/src/LionTextarea.js
Unable to update original https://github.com/ing-bank/lion/pull/504.
This PR will take its place.
Thanks to **dmarcu** for contribution.
> fix: unregister form element when disconnected

- packages/button/src/LionButton.js
Fix #525: Add preventDefault event as @erikkroes suggested
> fix(button): using space on button should not scroll page

- packages/button/src/LionButton.js
- packages/button/test/lion-button.test.js
- packages/core/index.js
- packages/core/package.json
- packages/core/src/browserDetection.js
- packages/field/src/utils/getAriaElementsInRightDomOrder.js
- packages/field/test/utils/getAriaElementsInRightDomOrder.test.js
Resolves https://github.com/ing-bank/lion/issues/546
> fix(button): run regexp once instead of every render cycle

- packages/validate/src/Validator.js
- packages/validate/test/Validator.test.js
> fix(validator): throw error if getMessage not of type Function

- packages/overlays/src/OverlayController.js
- packages/overlays/test/OverlayController.test.js
- packages/tooltip/src/LionTooltip.js
- packages/tooltip/test/lion-tooltip.test.js
> fix(tooltip): dismissable on escape keypress

- packages/validate/stories/Overview.stories.mdx
Added extra documentation on how to add your own custom message to an already existing validator.
> chore(validator): add documentation for custom message

- packages/field/src/FormControlMixin.js
- packages/field/src/LionField.js
- packages/field/test/lion-field.test.js
Fixing issue : https://github.com/ing-bank/lion/issues/431
Removing state-disabled and state-filled classes and adapting tests and CSS.
> fix(field): replace state-disabled/filled css classes with attributes

- packages/validate/README.md
- packages/validate/stories/Overview.stories.mdx
Improve validation code example.
> chore(validation): improve validate example

- packages/tabs/src/LionTabs.js
> fix(tab): remove scroll while navigating the tabs using up/down arrows 

- packages/field/src/LionField.js
- packages/field/test/lion-field.test.js
- packages/form-system/stories/17-Validation-Examples.stories.mdx
- packages/validate/src/ValidateMixin.js
disable validation of disabled fields
> fix(field): do not validate disabled fields

- README.md
Fixes #581 based on the comment asking for a PR! I wasn't entirely sure where to put the badge, I think above the heading looks ok, also tried to the right of it. Happy to amend if there's a more sensible place.
Thank you for considering the PR and I hope the TODO browser is interesting/useful!
> chore: add TODOs Badge to README

- packages/ajax/stories/index.stories.mdx
Updated the storybook docs for ajax. Added some more examples.
> docs: update ajax story

- packages/checkbox-group/stories/index.stories.mdx
- packages/field/test-suites/FormatMixin.suite.js
- packages/field/test/lion-field.test.js
- packages/fieldset/src/FormElementsHaveNoError.js
- packages/fieldset/test/lion-fieldset.test.js
- packages/form-system/stories/15-features-overview.stories.mdx
- packages/form-system/stories/17-Validation-Examples.stories.mdx
- packages/form-system/stories/35-System-InteractionStates.stories.mdx
- packages/form-system/stories/fieldset-examples.stories.mdx
- packages/input-datepicker/src/LionInputDatepicker.js
- packages/input-email/stories/index.stories.mdx
- packages/input-iban/src/validators.js
- packages/radio-group/stories/index.stories.mdx
- packages/switch/stories/index.stories.mdx
- packages/validate/README.md
- packages/validate/src/ValidateMixin.js
- packages/validate/src/Validator.js
- packages/validate/src/loadDefaultFeedbackMessages.js
- packages/validate/src/validators/DateValidators.js
- packages/validate/src/validators/NumberValidators.js
- packages/validate/src/validators/Required.js
- packages/validate/src/validators/StringValidators.js
- packages/validate/stories/Overview.stories.mdx
- packages/validate/test-helpers/ExampleValidators.js
- packages/validate/test-suites/ValidateMixin.suite.js
- packages/validate/test-suites/ValidateMixinFeedbackPart.suite.js
- packages/validate/test/DateValidators.test.js
- packages/validate/test/NumberValidators.test.js
- packages/validate/test/StringValidators.test.js
- packages/validate/test/Validator.test.js
> feat(validate): change to use static validatorName instead of instance name

- packages/input-date/src/LionInputDate.js
- packages/input-date/test/lion-input-date.test.js
> fix(input-date): use timezone offset in serializedValue

- packages/calendar/src/LionCalendar.js
- packages/choice-input/src/ChoiceInputMixin.js
- packages/field/src/FormControlMixin.js
- packages/field/src/LionField.js
- packages/fieldset/src/FormGroupMixin.js
- packages/form-system/stories/helper-wc/h-output.js
- packages/input-amount/src/LionInputAmount.js
- packages/input-date/src/LionInputDate.js
- packages/input-datepicker/src/LionInputDatepicker.js
- packages/input/src/LionInput.js
- packages/select-rich/src/LionSelectRich.js
- packages/steps/src/LionSteps.js
- packages/validate/src/ValidateMixin.js
- packages/validate/src/utils/SyncUpdatableMixin.js
- packages/validate/test/SyncUpdatableMixin.test.js
Renaming `changedProps` and `c` to `changedProperties` as per #580
> chore: unify the naming of changedProperties param

- demo/stories/10-announcement.stories.mdx
I found this sentence confusing to read, I believe with these changes the pronouns are more consistent.
> chore: Make pronouns in announcement post consistent

- packages/localize/src/number/forceENAUSymbols.js
- packages/localize/src/number/normalizeIntl.js
- packages/localize/test/number/formatNumber.test.js
See the issue for details on the symbols fixed for the particular locale 'en-AU'
fixes issue #432
> fix: force symbols for locale 'en-AU'

- packages/choice-input/src/ChoiceGroupMixin.js
- packages/field/src/FormControlMixin.js
- packages/form-system/stories/15-features-overview.stories.mdx
Draft branch.
TODO: merge into https://github.com/ing-bank/lion/pull/602 and close this pr aftwerwards
> chore: wip normalize event propagation

- packages/button/src/LionButton.js
- packages/field/src/InteractionStateMixin.js
- packages/field/test-suites/InteractionStateMixin.suite.js
- packages/select-rich/src/LionSelectInvoker.js
- packages/select-rich/src/LionSelectRich.js
- packages/select-rich/test/lion-select-rich.test.js
Some fixes cherry-picked from our extension layer where we had to do these fixes in order for our lion rich select extension to work properly.
> Select Rich fixes

- packages/choice-input/src/ChoiceGroupMixin.js
- packages/choice-input/src/ChoiceInputMixin.js
- packages/field/src/FormControlMixin.js
- packages/field/src/InteractionStateMixin.js
- packages/field/src/LionField.js
- packages/field/test-suites/InteractionStateMixin.suite.js
- packages/field/test/lion-field.test.js
- packages/fieldset/src/FormGroupMixin.js
- packages/fieldset/test/lion-fieldset.test.js
- packages/form-system/stories/35-System-InteractionStates.stories.mdx
- packages/validate/src/ValidateMixin.js
- packages/validate/test-suites/ValidateMixin.suite.js
fixes https://github.com/ing-bank/lion/issues/645
> Field isEmpty / filled / prefilled aligning

- packages/tooltip/stories/index.stories.mdx
> fix(659): Fix closing div tags in tooltip stories

- packages/calendar/src/LionCalendar.js
- packages/input-datepicker/src/LionCalendarOverlayFrame.js
- packages/input-datepicker/src/LionInputDatepicker.js
- packages/input-iban/src/validators.js
- packages/validate/src/loadDefaultFeedbackMessages.js
fixes https://github.com/ing-bank/lion/issues/653
fixes https://github.com/ing-bank/lion/issues/396
> fix: convert unnecessary backticks to single quotes for unpkg

- packages/overlays/src/OverlayController.js
- packages/overlays/test/OverlayController.test.js
implementation for bug #269 
fixes #269
> feat(OverlayController): add invokerRelation option

- packages/select-rich/src/LionSelectInvoker.js
- packages/select-rich/src/LionSelectRich.js
- packages/select-rich/test/lion-select-rich.test.js
Closes issue
https://github.com/ing-bank/lion/issues/677
> feat(select-rich): added signleoption functionality

- packages/input-range/src/LionInputRange.js
fixes https://github.com/ing-bank/lion/issues/686
> fix(input-range): securely apply css

- packages/select-rich/src/LionSelectInvoker.js
- packages/select-rich/src/LionSelectRich.js
- packages/select-rich/stories/index.stories.mdx
- packages/select-rich/test/lion-select-invoker.test.js
- packages/select-rich/test/lion-select-rich.test.js
all changes done as suggested in [this](https://github.com/ing-bank/lion/pull/678) MR
> chore(select-rich): docs for single-option and fix review comments

- .eslintrc.js
- packages/babel-plugin-extend-docs/README.md
- packages/babel-plugin-extend-docs/demo/index.html
- packages/babel-plugin-extend-docs/demo/my-app.demo.js
- packages/babel-plugin-extend-docs/demo/my-counter.js
- packages/babel-plugin-extend-docs/demo/my-extension/MyExtension.js
- packages/babel-plugin-extend-docs/demo/my-extension/index.js
- packages/babel-plugin-extend-docs/demo/my-extension/my-extension.js
- packages/babel-plugin-extend-docs/demo/server.config.js
- packages/babel-plugin-extend-docs/demo/server.no-babel.config.js
- packages/babel-plugin-extend-docs/demo/src/MyCounter.js
- packages/babel-plugin-extend-docs/index.js
- packages/babel-plugin-extend-docs/package.json
- packages/babel-plugin-extend-docs/src/babelPluginExtendDocs.js
- packages/babel-plugin-extend-docs/src/handleImports.js
- packages/babel-plugin-extend-docs/src/helpers.js
- packages/babel-plugin-extend-docs/src/validateOptions.js
- packages/babel-plugin-extend-docs/test-node/babelPluginExtendDocs.test.js
- packages/babel-plugin-extend-docs/test-node/helpers.js
- packages/babel-plugin-extend-docs/test-node/integration.test.js
- packages/babel-plugin-extend-docs/test-node/validateOptions.test.js
- yarn.lock
> feat(babel-plugin-extends-docs): extend docs by rewriting imports/code

- packages/tabs/src/LionTabs.js
> fix(tabs): tab keyboard navigation trap

- packages/form-system/stories/17-Validation-Examples.stories.mdx
- packages/validate/index.js
- packages/validate/src/loadDefaultFeedbackMessages.js
- packages/validate/src/validators/StringValidators.js
- packages/validate/stories/Overview.stories.mdx
- packages/validate/test/StringValidators.test.js
- packages/validate/translations/bg.js
- packages/validate/translations/cs.js
- packages/validate/translations/de.js
- packages/validate/translations/en.js
- packages/validate/translations/es.js
- packages/validate/translations/fr.js
- packages/validate/translations/hu.js
- packages/validate/translations/it.js
- packages/validate/translations/nl.js
- packages/validate/translations/pl.js
- packages/validate/translations/ro.js
- packages/validate/translations/ru.js
- packages/validate/translations/sk.js
- packages/validate/translations/uk.js
- packages/validate/translations/zh.js
1. Added IsPattern validator for strings validators
2. Modified - Default Translation files for the error message
3. Added tests 
#My first attempt to contribute - #caution
> Feat pattern validator

- packages/fieldset/src/FormGroupMixin.js
- packages/fieldset/test/lion-fieldset.test.js
- packages/form-system/stories/form-examples.stories.mdx
This is for clearGroup functionality for form. https://github.com/ing-bank/lion/issues/706
> feat: clearGroup for form

- packages/select-rich/src/LionSelectInvoker.js
> fix(select-rich): prevent scrolling when focused

- packages/tabs/src/LionTabs.js
- packages/tabs/test/lion-tabs.test.js
> fix(tabs): do not focus tabs when selectedIndex is set

- packages/button/src/LionButton.js
- packages/button/test/lion-button.test.js
- packages/switch/src/LionSwitchButton.js
- packages/switch/test/lion-switch-button.test.js
> fix(button): aria-disabled for button and switch

- packages/overlays/src/OverlayController.js
- packages/overlays/test-suites/OverlayMixin.suite.js
> fix(overlays): body resize on global overlay open

- packages/localize/docs/40-google-translate-integration.md
- packages/localize/src/LocalizeManager.js
- packages/localize/test/LocalizeManager.test.js
> feat(localize): support google translate

- packages/form-core/src/InteractionStateMixin.js
- packages/form-core/test-suites/InteractionStateMixin.suite.js
- packages/form-integrations/docs/17-validation-examples.md
- packages/form-integrations/test/form-reset.test.js
- yarn.lock
Validation not removed when resetting a form for lion-checkbox-group and lion-radio-group.
> fix(form-core): on reset the submitted values becomes false

- packages/localize/src/LocalizeManager.js
> fix(localize): loading of new translations

- packages/button/src/LionButton.js
> fix(button): prevent scrolling when repeating space key

- packages/dialog/README.md
- packages/dialog/docs/slots-dialog-content.js
- packages/overlays/src/utils/get-focusable-elements.js
> fix(overlays): make focusable slotted buttons

- packages/accordion/package.json
- packages/accordion/src/LionAccordion.js
- packages/accordion/test/lion-accordion.test.js
- Removed rolling key behavior
- Set correct preventDefault behavior of keys
> fix(accordion): fix keyboard interaction

- packages/form-integrations/test/helpers/umbrella-form.js
- packages/input-amount/test/parsers.test.js
> tests: timezone and locale

- packages/form-core/src/form-group/FormGroupMixin.js
- packages/overlays/src/OverlayController.js
- packages/overlays/src/OverlayMixin.js
closes https://github.com/ing-bank/lion/issues/781
> fix(overlays): only teardown when overlayCtrl defined

- packages/form-core/src/registration/FormRegistrarPortalMixin.js
- packages/select-rich/src/LionSelectRich.js
See discussion about that here:
https://polymer.slack.com/archives/CJGFWJN9J/p1591901856272600
Issue was revealed when select-rich is rendered with react
> fix(select-rich): instantiation after first update

- packages/form-core/src/form-group/FormGroupMixin.js
_setValueForAllFormElements must wait for formElements to be registered
Closes #707
> fix(formgroup): wait for formElements to register

- packages/form-core/src/validate/ValidateMixin.js
- packages/form-core/test-suites/ValidateMixin.suite.js
- packages/form-core/test-suites/ValidateMixinFeedbackPart.suite.js
- packages/form-core/test/lion-field.test.js
- packages/form-core/test/validate/DateValidators.test.js
- packages/form-core/test/validate/NumberValidators.test.js
- packages/form-core/test/validate/StringValidators.test.js
> test(validators): validatorName instead of name

- package.json
- web-test-runner.config.js
- yarn.lock
Speed improvements and some bug fixes
> chore: update web test runner to 0.6.14

- .changeset/rare-glasses-collect.md
- .lintstagedrc.js
- packages/select-rich/src/LionSelectRich.js
- packages/select-rich/test/lion-select-rich.test.js
closes https://github.com/ing-bank/lion/issues/757
> fix(select-rich): clicking on the label should focus the invoker button

- .changeset/clever-trains-remember.md
- packages/providence-analytics/src/cli/cli-helpers.js
- packages/providence-analytics/src/cli/cli.js
- packages/providence-analytics/src/cli/generate-extend-docs-data.js
- packages/providence-analytics/src/program/services/InputDataService.js
- packages/providence-analytics/test-helpers/project-mocks-analyzer-outputs/find-classes.json
- packages/providence-analytics/test-helpers/project-mocks-analyzer-outputs/find-customelements.json
- packages/providence-analytics/test-helpers/project-mocks-analyzer-outputs/find-exports.json
- packages/providence-analytics/test-helpers/project-mocks-analyzer-outputs/find-imports.json
- packages/providence-analytics/test-helpers/project-mocks-analyzer-outputs/match-imports.json
- packages/providence-analytics/test-helpers/project-mocks-analyzer-outputs/match-paths.json
- packages/providence-analytics/test-helpers/project-mocks-analyzer-outputs/match-subclasses.json
- packages/providence-analytics/test-helpers/project-mocks/README.md
- packages/providence-analytics/test-helpers/project-mocks/importing-target-project/target-src/match-subclasses/ExtendedComp.js
- packages/providence-analytics/test-node/cli/cli.test.js
- packages/providence-analytics/test-node/program/analyzers/e2e/all-analyzers.e2e.js
- packages/providence-analytics/test-node/program/services/InputDataService.test.js
closes https://github.com/ing-bank/lion/issues/850
closes https://github.com/ing-bank/lion/issues/851
> feat(providence-analytics): add --allowlist-mode option

- README.md
this PR tries to add the essence of the comment https://github.com/ing-bank/lion/issues/905#issuecomment-680732775 into the Storybook.
hopefully this is the right file to get it into https://lion-web-components.netlify.app/?path=/docs/intro-lion-web-components--page
> Added note regarding prerequisites to run the demos

- .changeset/smooth-apricots-laugh.md
- packages/babel-plugin-extend-docs/demo/src/MyCounter.js
- packages/form-core/src/registration/FormRegisteringMixin.js
- packages/listbox/README.md
What I did:
- Remove usage of Public Class Field => closes https://github.com/ing-bank/lion/issues/923
- Fixed listbox demos
> fix(form-core): remove usage of Public Class Fields to not break builds

- .changeset/rotten-dancers-breathe.md
- .changeset/thin-rocks-chew.md
- packages/accordion/src/LionAccordion.js
- packages/accordion/test/lion-accordion.test.js
- packages/tabs/src/LionTabs.js
- tsconfig.json
> Small fix for accordion and tabs, and type accordion package

- .changeset/orange-geckos-begin.md
- .changeset/silly-chairs-grow.md
- packages/fieldset/src/LionFieldset.js
- packages/form-core/types/form-group/FormGroupMixinTypes.d.ts
- packages/form/src/LionForm.js
- packages/form/test/lion-form.test.js
- tsconfig.json
1. add types for form
2. add types for fieldset
3. added submitGroup method to types definition file of FormGroupMixin
> feat: add types for fieldset & form

- .changeset/tidy-ads-greet.md
- packages/collapsible/demo/CustomCollapsible.js
- packages/collapsible/src/LionCollapsible.js
- packages/collapsible/test/lion-collapsible.test.js
- tsconfig.json
> feat(collapsible): add types for collapsible

- .changeset/metal-maps-collect.md
- packages/dialog/src/LionDialog.js
- packages/dialog/test/lion-dialog.test.js
- tsconfig.json
> feat(dialog): add types for dialog

- .changeset/ninety-vans-cheer.md
- packages/pagination/src/LionPagination.js
- packages/pagination/test/lion-pagination.test.js
- tsconfig.json
> feat(pagination): add types

- .changeset/early-ghosts-pay.md
- packages/progress-indicator/src/LionProgressIndicator.js
- tsconfig.json
1. add types for progress-indicator
> feat(progress-indicator): add types

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- CONTRIBUTING.md
- README.md
1. update docs (issue template, readme, contribution) so that new feature requests should be created in discussions
> chore: use discussions for feature requests

- .changeset/late-pugs-jog.md
- .changeset/slimy-windows-sing.md
- packages/form-core/src/choice-group/ChoiceGroupMixin.js
- packages/form-integrations/docs/15-features-overview.md
- packages/listbox/src/ListboxMixin.js
- packages/listbox/test-suites/ListboxMixin.suite.js
1. Add reset function to listbox
- improved version of: https://github.com/ing-bank/lion/pull/710
> fix(listbox): add reset function

- .changeset/eighty-planes-build.md
- packages/listbox/src/ListboxMixin.js
- packages/listbox/test-suites/ListboxMixin.suite.js
closes https://github.com/ing-bank/lion/issues/984
> fix(listbox): no cancellation multi mouse click

- packages/combobox/package.json
1. define side effects for combobox
> chore: fix storybook build of combobox demo

- .changeset/ten-moles-kneel.md
- packages/combobox/src/LionCombobox.js
> add inherited styles in combobox to allow styling

- .changeset/eleven-bears-repair.md
- .changeset/late-pugs-jog.md
- .changeset/more.md
> chore: changesets

- .changeset/cold-panthers-tie.md
- packages/form-core/src/validate/ValidateMixin.js
- packages/form-core/test-suites/ValidateMixin.suite.js
This commit filters the validators by the showing feedback conditions in order to fix https://github.com/ing-bank/lion/issues/899
> fix(form-core): filter feedback messages according feedback conditions

- .changeset/slow-laws-trade.md
- packages/combobox/src/LionCombobox.js
1. Allow customization of background in combobox
> fix(combobox): inherit background for native input

- .changeset/curly-oranges-promise.md
- .changeset/tasty-rabbits-fry.md
- packages/button/CHANGELOG.md
- packages/button/package.json
- packages/form-integrations/CHANGELOG.md
- packages/form-integrations/package.json
- packages/providence-analytics/CHANGELOG.md
- packages/providence-analytics/package.json
- packages/select-rich/CHANGELOG.md
- packages/select-rich/package.json
1. Manual release, as one of the changesets was improperly formatted and broke the CI
https://github.com/ing-bank/lion/pull/1035/files#r507704027
> chore: release packages

- .changeset/large-walls-dance.md
- packages/core/types/SlotMixinTypes.d.ts
- packages/localize/types/LocalizeMixinTypes.d.ts
- packages/select-rich/src/LionSelectInvoker.js
- packages/select-rich/test/lion-select-invoker.test.js
type enhancements SlotMixin, LocalizeMixin, SelectRichInvoker
> chore: type enhancements SlotMixin, LocalizeMixin, SelectRichInvoker

- .changeset/strong-tables-drum.md
- packages/babel-plugin-extend-docs/src/handleImports.js
fixes https://github.com/ing-bank/lion/issues/1050
> fix(babel-plugin-extend-docs): consider windows paths

- .changeset/afraid-maps-fix.md
- packages/button/src/LionButton.js
- packages/button/test/lion-button.test.js
closes https://github.com/ing-bank/lion/issues/1081
closes https://github.com/ing-bank/lion/issues/1069
closes https://github.com/ing-bank/lion/pull/1068
> fix(button): do not override aria-labelledby from user

- .changeset/tall-eagles-doubt.md
- packages/ajax/test/AjaxClass.languages.test.js
- tsconfig.build.types.json
> chore: release type files for ajax

- .changeset/strong-humans-sip.md
- packages/form-core/src/FormControlMixin.js
- packages/form-core/src/choice-group/ChoiceInputMixin.js
- packages/listbox/src/ListboxMixin.js
- packages/overlays/src/ArrowMixin.js
> fix: point to parent constructor in static get styles (points to undefined atm)

- packages/overlays/package.json
fixes https://github.com/ing-bank/lion/issues/1107
> chore: add demo-overlay-backdrop side-effect file for storybook

- .changeset/tricky-mugs-switch.md
- packages/combobox/test/lion-combobox.test.js
- packages/input-datepicker/test-helpers/DatepickerInputObject.js
- packages/overlays/src/OverlayController.js
1. Keep transitionShow and transitionHide as user hooks
> fix(overlays): keep hide/show hooks

- .changeset/curly-ladybugs-grab.md
- packages/calendar/src/LionCalendar.js
- packages/calendar/test/lion-calendar.test.js
> fix(calendar): solve previousMonth and nextMonth conditions error

- .changeset/lovely-toys-relate.md
- packages/core/package.json
- yarn.lock
> fix(core): upgrade @open-wc/scoped-elments version to latest

- tsconfig.build.types.json
> chore: fix tsconfig.build

- packages/form-core/src/validate/ValidateMixin.js
- packages/form-core/test-suites/ValidateMixin.suite.js
1. Based on: https://polymer.slack.com/archives/CJGFWJN9J/p1608528031390200Improve, the error message is improved.
2. In my opinion, no real need to increase the version, it would be okay to wait a little for this to be released.
> chore: improve validators instance error message

- .changeset/blue-frogs-enjoy.md
- .changeset/forty-ants-relate.md
- packages/button/src/LionButton.js
- packages/select-rich/src/LionSelectInvoker.js
> fix(button): add user-select rule with prefixes

- .changeset/long-parents-divide.md
- packages/combobox/src/LionCombobox.js
- packages/select-rich/src/LionSelectInvoker.js
- packages/tooltip/src/LionTooltip.js
fixes https://github.com/ing-bank/lion/issues/1169
> fix: type issues with regards to static styles

- .changeset/rich-pens-repeat.md
- packages/form-core/src/choice-group/ChoiceInputMixin.js
- packages/form-core/test-suites/choice-group/ChoiceGroupMixin.suite.js
- packages/form-core/types/choice-group/ChoiceInputMixinTypes.d.ts
fixes https://github.com/ing-bank/lion/issues/1132
> fix(form-core): fix infinite loop syncing name to parent

- .changeset/proud-waves-kick.md
- packages-node/providence-analytics/src/cli/cli.js
- packages-node/providence-analytics/test-node/cli/cli.test.js
- packages-node/providence-analytics/test-node/program/services/InputDataService.test.js
closes https://github.com/ing-bank/lion/issues/1190
> fix(providence-analytics): pass globs via cli

- .changeset/friendly-pianos-wonder.md
- .changeset/strange-cougars-shout.md
- packages/button/src/LionButton.js
- packages/form-integrations/docs/15-features-overview.md
- packages/form/README.md
- packages/form/src/LionForm.js
- packages/form/test/lion-form.test.js
fixes https://github.com/ing-bank/lion/issues/1047
> fix(form): dispatch submit ev on native form node and add docs

- .changeset/rich-masks-shout.md
- .github/workflows/release.yml
- .github/workflows/verify.yml
- packages/form-core/src/validate/ValidateMixin.js
- packages/listbox/src/ListboxMixin.js
- packages/select-rich/src/LionSelectRich.js
- packages/switch/src/LionSwitch.js
fixes https://github.com/ing-bank/lion/issues/1219
> fix: add data-tag-name attribute on scoped slottables

- packages/form-integrations/docs/17-validation-examples.md
1. Add a backend validator example
> docs(validation): add backend validator example

- .changeset/orange-walls-sniff.md
- .eslintignore
- packages/form-core/src/validate/ResultValidator.js
- packages/form-core/src/validate/ValidateMixin.js
- packages/form-core/src/validate/resultValidators/DefaultSuccess.js
- packages/form-core/test-suites/ValidateMixin.suite.js
- packages/form-core/test/validate/ResultValidator.test.js
- packages/form-core/types/validate/ValidateMixinTypes.d.ts
- packages/form-integrations/test/form-validation-integrations.test.js
fixes https://github.com/ing-bank/lion/issues/1236
fixes https://github.com/ing-bank/lion/issues/1237
> fix(form-core): only show success after recovery from shown feedback

- yarn.lock
> chore: update lock file for latest  @web/rollup-plugin-polyfills-loader

- docs/blog/controlling-exports.11tydata.cjs
- docs/blog/ing-open-sources-lion.11tydata.cjs
- docs/blog/introducing-lions-website.11tydata.cjs
- docs/components/index.11tydata.cjs
- docs/index.11tydata.cjs
1. Add more info into social media images of certain pages
> chore: improve social media images

- docs/_assets/variables.css
1. Changed the primary color to give a contrast ratio of at least 4.5:1 on a white background
> fix: make primary color accessible

- .changeset/hip-terms-watch.md
- docs/components/inputs/checkbox-group/features.md
- packages/checkbox-group/package.json
fixes https://github.com/ing-bank/lion/issues/1269
> fix(checkbox-group): add side effect define.js to package.json

- .changeset/sweet-terms-act.md
- packages/form-core/src/utils/SyncUpdatableMixin.js
- packages/form-core/test/utils/SyncUpdatableMixin.test.js
- packages/form-integrations/test/form-integrations.test.js
- packages/form-integrations/test/helpers/umbrella-form.js
fixes https://github.com/ing-bank/lion/issues/1220
> fix: make sync updatable mixin work with re-connecting to DOM

- .changeset/cuddly-tips-teach.md
1. Pushing a changeset to add missing packages from next release
> chore: add missing packages to changeset-release/master

- .changeset/fifty-items-act.md
- packages-node/remark-extend/docs/test.md
- packages-node/remark-extend/src/remarkExtend.js
- packages-node/remark-extend/test-node/remark-extend.test.js
> fix(remark-extend): do not touch image urls

- docs/docs/systems/form/model-value.md
closes https://github.com/ing-bank/lion/issues/1285
> chore: docs for model-value-changed meta

- .changeset/wise-moles-teach.md
- docs/docs/systems/form/model-value.md
- packages/form-integrations/test/model-value-consistency.test.js
- packages/listbox/src/ListboxMixin.js
closes https://github.com/ing-bank/lion/issues/1173
> isTriggeredByUser for listbox (descendants)

- .changeset/chilled-tools-help.md
- packages-node/providence-analytics/package.json
- packages-node/providence-analytics/src/program/analyzers/index.js
Expose analyzers that are requested to be run in external contexts
> fix(providence): expose analyzers

- .changeset/dry-fishes-shake.md
- docs/components/content/collapsible/overview.md
- docs/components/inputs/checkbox-group/overview.md
- docs/components/inputs/fieldset/overview.md
- docs/components/inputs/form/overview.md
- docs/components/inputs/input-amount/overview.md
- docs/components/inputs/input-date/overview.md
- docs/components/inputs/input-datepicker/overview.md
- docs/components/inputs/input-email/overview.md
- docs/components/inputs/input-iban/overview.md
- docs/components/inputs/input-range/overview.md
- docs/components/inputs/input-stepper/overview.md
- docs/components/inputs/radio-group/overview.md
- docs/components/inputs/select/overview.md
- docs/components/inputs/textarea/overview.md
> chore(docs): remove lion references for easier extending

- docs/components/inputs/input/overview.md
Small typo caught my eyes, and punctuation improvements while on it.
> chore(typo): input overview

- .changeset/eight-pumpkins-clean.md
- packages/ajax/src/AjaxClient.js
- packages/ajax/src/interceptors-cache.js
- packages/ajax/src/interceptors.js
- packages/ajax/test/AjaxClient.test.js
- packages/ajax/test/interceptors-cache.test.js
1. Fix options expansion
2. Fix removing request interceptors
3. Use 1 hour as the default time to live
4. Check for null when serializing the search params
> fix(ajax): bug fixes and readability improvements

- .changeset/nervous-paws-tease.md
- packages/combobox/src/LionCombobox.js
- packages/combobox/test/lion-combobox.test.js
- packages/listbox/src/ListboxMixin.js
1.Added clear functionality for combobox
closes https://github.com/ing-bank/lion/discussions/1268
> fix: combobox clear function

- .changeset/famous-wolves-notice.md
- .changeset/sharp-laws-scream.md
- .changeset/sharp-ravens-buy.md
- docs/components/interaction/switch/features.md
- packages/form-core/src/InteractionStateMixin.js
- packages/form-core/src/validate/ValidateMixin.js
- packages/form-core/test-suites/ValidateMixin.suite.js
- packages/form-core/types/InteractionStateMixinTypes.d.ts
- packages/form-core/types/validate/ValidateMixinTypes.d.ts
- packages/switch/src/LionSwitch.js
- packages/switch/test/lion-switch.test.js
closes https://github.com/ing-bank/lion/issues/1322
closes https://github.com/ing-bank/lion/issues/1203
closes https://github.com/ing-bank/lion/issues/1204
> fix(switch|form-core): enhanced feedback visibility configuration / applied on switch / a11y fix

- .changeset/rotten-dots-argue.md
- .changeset/rude-ducks-hide.md
- .changeset/slimy-items-wait.md
- packages/combobox/src/LionCombobox.js
- packages/combobox/test/lion-combobox.test.js
- packages/form-core/src/FormControlMixin.js
- packages/form-core/src/choice-group/ChoiceInputMixin.js
- packages/form-core/src/form-group/FormGroupMixin.js
- packages/form-core/src/registration/FormRegistrarMixin.js
- packages/form-core/test-suites/choice-group/ChoiceGroupMixin.suite.js
- packages/form-core/test-suites/form-group/FormGroupMixin-input.suite.js
- packages/form-core/test/FormControlMixin.test.js
- packages/form-core/test/lion-field.test.js
- packages/form-core/types/FormControlMixinTypes.d.ts
- packages/form-core/types/choice-group/ChoiceGroupMixinTypes.d.ts
- packages/form-core/types/form-group/FormGroupMixinTypes.d.ts
closes https://github.com/ing-bank/lion/issues/1162
closes https://github.com/ing-bank/lion/issues/1327
closes https://github.com/ing-bank/lion/issues/1015
> fix(form-core): a11y / types / test fixes

- .changeset/fair-geese-drum.md
- docs/docs/systems/form/interaction-states.md
- docs/docs/systems/form/validate.md
- packages/form-core/src/InteractionStateMixin.js
- packages/form-core/src/LionField.js
- packages/form-core/src/validate/ValidateMixin.js
- packages/form-core/test-suites/ValidateMixin.suite.js
- packages/form-core/test-suites/form-group/FormGroupMixin.suite.js
- packages/form-core/test/lion-field.test.js
- packages/form-core/types/NativeTextFieldMixinTypes.d.ts
- packages/form-core/types/form-group/FormGroupMixinTypes.d.ts
- packages/form-core/types/utils/SyncUpdatableMixinTypes.d.ts
- packages/form-core/types/validate/ValidateMixinTypes.d.ts
- packages/listbox/src/LionListbox.js
- packages/listbox/test-suites/ListboxMixin.suite.js
- packages/switch/test/lion-switch.test.js
closes https://github.com/ing-bank/lion/discussions/1222
closes https://github.com/ing-bank/lion/issues/1329
closes https://github.com/ing-bank/lion/discussions/1159
closes https://github.com/ing-bank/lion/issues/1324
> fix(form-core): validate on child change + {feedbackType}StateChanged

- .changeset/lemon-shoes-doubt.md
- .changeset/loud-rocks-teach.md
- packages/checkbox-group/src/LionCheckboxGroup.js
- packages/checkbox-group/test/lion-checkbox-group.test.js
- packages/overlays/src/OverlayController.js
- packages/overlays/test/OverlayController.test.js
closes https://github.com/ing-bank/lion/issues/759
> fix(overlays): only focus controlled elements after hide

- .changeset/dirty-rules-wash.md
- packages/button/src/LionButton.js
- packages/calendar/src/LionCalendar.js
- packages/form-core/src/FormatMixin.js
- packages/form-core/types/FormatMixinTypes.d.ts
- packages/input-amount/src/LionInputAmount.js
- packages/input-datepicker/src/LionInputDatepicker.js
- packages/input-datepicker/test-helpers/DatepickerInputObject.js
- packages/select-rich/src/LionSelectRich.js
> fix: expose members as protected for extension compat. till v1

- .changeset/shaggy-wasps-doubt.md
- packages/calendar/src/LionCalendar.js
- packages/calendar/test/lion-calendar.test.js
- packages/input-datepicker/src/LionInputDatepicker.js
- packages/input-datepicker/test-helpers/DatepickerInputObject.js
- packages/input-datepicker/test/lion-input-datepicker.test.js
closes https://github.com/ing-bank/lion/issues/1338
> fix(calendar): reset centralDate, focusedDate and disableDates

- docs/components/index.md
closes https://github.com/ing-bank/lion/issues/1334
> chore: adjust texts Component group overview

- docs/components/inputs/combobox/features.md
really small doc update (right heading level + some better explanation)...
> chore: server interaction example update

- .changeset/selfish-ears-flash.md
- .changeset/short-llamas-share.md
- .changeset/tough-lizards-fly.md
This reverts commit 1b54857de11df4a08089b05be786e2b1223cd1a7.
Restore temp disabled changesets
> Revert "chore: temp delete unneeded changesets"

- docs/_data/footer.json
> chore: update social channels

- docs/_assets/style.css
> chore(docs): reduce length of sidebar by hiding in-page urls

- .changeset/dirty-ducks-juggle.md
- packages/form-integrations/test/model-value-consistency.test.js
- packages/switch/src/LionSwitch.js
- packages/switch/test/lion-switch.test.js
> fix(switch): fire model-value-changed with isTriggeredByUser: true

- patches/@rocket+cli+0.6.3.patch
closes https://github.com/ing-bank/lion/issues/1394
fixes [object Object] for story previews in new simulator windows
> chore: temp patch @rocket/cli simulator window

- .changeset/big-hotels-exercise.md
- .changeset/fuzzy-snails-attack.md
1. lit update does not affect most node-packages
2. add more info about lit 2 update
> chore: improve lit 2 release info and only release if needed

- .changeset/eleven-meals-laugh.md
- packages-node/rocket-preset-extend-lion-docs/package.json
> fix(rocket-preset-extend-lion-docs): add missing dependency

- docs/docs/systems/overlays/overview.md
Apply missing OverlayMixin in docs
> docs(overlays): apply missing OverlayMixin

- docs/docs/tools/ajax/features.md
> chore: fix ajax invalidate cache demo

- .changeset/clean-lobsters-glow.md
- docs/components/interaction/switch/overview.md
- packages/form-core/src/validate/ValidateMixin.js
- packages/form-integrations/test/model-value-consistency.test.js
- packages/listbox/src/ListboxMixin.js
- packages/select-rich/src/LionSelectRich.js
- packages/switch/src/LionSwitch.js
- yarn.lock
1.  use customElementRegistry from component registry for slots used via SlotMixin
> fix: create scoped elements also when slotting them in

- packages/core/docs/guides/how-to/create-a-custom-field.md
- packages/core/docs/guides/how-to/creating-a-custom-field.md
- packages/core/docs/guides/how-to/extend-a-native-input.md
> chore: publish all guides

- .changeset/old-penguins-dream.md
- packages/overlays/index.js
1. Export useful utilities from the overlay system so they can be used on their own.
> fix(overlays): export overlay utils

- .changeset/blue-socks-prove.md
- packages/form-integrations/test/model-value-consistency.test.js
- packages/input-datepicker/src/LionInputDatepicker.js
- packages/input-datepicker/test/lion-input-datepicker.test.js
> fix(input-datepicker): set isTriggeredByUser on change via calendar

- .husky/commit-msg
- commitlint.config.js
- package.json
- yarn.lock
1. Remove commitlint as we no longer release based on commit messages linting them is more annoying then useful
> chore: remove commitlint

- .changeset/poor-swans-hope.md
- packages/listbox/src/ListboxMixin.js
- packages/listbox/test-suites/ListboxMixin.suite.js
- packages/listbox/types/ListboxMixinTypes.d.ts
- yarn.lock
fixes https://github.com/ing-bank/lion/issues/1413
> fix(listbox): always scroll active item into view

- .changeset/large-mails-roll.md
- packages/form-integrations/test/form-integrations.test.js
- packages/select/src/LionSelect.js
- packages/select/test/lion-select.test.js
Fix: https://github.com/ing-bank/lion/issues/1384
> fix(select): set formattedValue to text of selected option

- .changeset/tender-kangaroos-visit.md
- packages/input-stepper/src/LionInputStepper.js
- packages/input-stepper/test/lion-input-stepper.test.js
aaaaaanother one
See changeset :)
> fix(input-stepper): redispatch btn blurs on stepper

- .changeset/hip-fishes-flash.md
- packages/core/src/SlotMixin.js
- packages/core/test/SlotMixin.test.js
- packages/core/types/SlotMixinTypes.d.ts
Support scoped elements via a (complex) template
> feat(core): scoped templates in SlotMixin

- .changeset/silent-seahorses-battle.md
- packages/accordion/src/LionAccordion.js
1. Refactored some methods and args so that the same "StoreEntry" interface is used, this makes the code more predictable and readable.
2. Make some of the functions outside the class a protected member of the class, so that subclassers can easily override them.
> feat(accordion): refactor for readability & extensibility

- .changeset/twelve-zoos-turn.md
- packages-node/providence-analytics/src/cli/cli-helpers.js
1. Based on conversations with @tlouisse
> Correct default target in Windows if no -t

- .changeset/nervous-suns-wonder.md
- packages/combobox/src/LionCombobox.js
1. Removed use of innerHTML from LionComboBox to make Checkmarx happy
> fix: Removed use of innerHTML from LionComboBox

- netlify.toml
- package.json
- yarn.lock
1. Updating to rocket with more security measures for the mdjs preview simulator
2. Add csp rules
> chore: improve security

- package.json
- yarn.lock
1. makes the search dropdown work again
> chore: fix search by updating dependency

- .changeset/brave-pots-type.md
- packages-node/providence-analytics/src/program/utils/get-providence-conf.mjs
1. Fixed issue with loading config on the machine with windows
> fix(providance-analytics): Fixed issue with loading config on windows

- docs/docs/systems/form/validate.md
> chore(form-core): add a better example for custom validator

- .github/workflows/release.yml
> chore: run tests for release

- docs/blog/accessibility.md
1. Gave some context to the term "accessible" which we use widely
> chore: accessibility blog

- docs/blog/accessibility.md
Looks like a typo, am I wrong?
Thanks for this content @erikkroes, it's really useful :heart:
> Typo in accessibility.md

- .changeset/lemon-ravens-mate.md
- docs/components/interaction/button/features.md
- packages/button/src/LionButton.js
> fix(button): increase click area to meet WCAG success criteria

- .github/workflows/release.yml
- .github/workflows/verify.yml
- README.md
- docs/about/slack.md
- docs/blog/ing-open-sources-lion.md
- docs/guides/how-to/get-started.md
> chore: upgrade node version

- package.json
- yarn.lock
> chore: upgrade custom-elements-manifest/analyzer version

- .changeset/tender-islands-wait.md
- packages/collapsible/src/LionCollapsible.js
- packages/collapsible/test/lion-collapsible.test.js
1. Moved `.bind(this)` to constructor
> fix(collapsible): moved binding to constructor

- .changeset/thirty-scissors-hug.md
- packages-node/providence-analytics/src/program/services/InputDataService.js
- packages-node/providence-analytics/test-node/program/services/InputDataService.test.js
closes https://github.com/ing-bank/lion/issues/1640
> fix(providence-analytics): better allowlist-mode detection

- docs/components/combobox/overview.md
- docs/components/combobox/use-cases.md
- docs/guides/how-to/create-a-custom-field.md
- docs/guides/how-to/extend-a-native-input.md
> chore: fix imports in docs pages blocking deploys

- .changeset/green-rocks-rule.md
- packages/core/src/SlotMixin.js
- packages/core/test/SlotMixin.test.js
closes https://github.com/ing-bank/lion/issues/1652
> fix(core): scoped slots

- packages/ajax/test/Ajax.test.js
1. Add tests for the response values and headers of cached requests in the ajax library
2. Changed fetchStub to return a different response each time
> chore(ajax): add tests for response values and headers in caching calls

- .changeset/clean-terms-give.md
- docs/components/checkbox-group/use-cases.md
- packages/checkbox-group/src/LionCheckboxIndeterminate.js
- packages/checkbox-group/test/lion-checkbox-indeterminate.test.js
[See WAI-ARIA docs on this pattern](https://www.w3.org/TR/wai-aria-practices-1.1/examples/checkbox/checkbox-2/checkbox-2.html)
> feat: add tri-state indeterminate checkbox feature

- .changeset/fresh-paws-run.md
- docs/components/listbox/use-cases.md
- packages/combobox/src/LionCombobox.js
- packages/listbox/src/ListboxMixin.js
- packages/listbox/test-suites/ListboxMixin.suite.js
- packages/listbox/types/ListboxMixinTypes.d.ts
- packages/select-rich/src/LionSelectRich.js
- packages/select-rich/test/lion-select-rich-interaction.test.js
> feat(listbox): add type ahead option

- .changeset/fresh-paws-run.md
> chore(listbox): change feature into patch release

- .changeset/four-buses-drum.md
- .husky/_/husky.sh
- packages/core/package.json
- tsconfig.json
- yarn.lock
> chore: Update to latest lit v1

- .changeset/popular-grapes-drop.md
- .gitignore
- packages/core/directive.d.ts
- packages/core/directive.js
- packages/core/index.js
- packages/core/package.json
1. Export lit-html 2.0 directive in separate file following the lit-html convention
> fix: export lit-html2 directive

- .changeset/mighty-bats-decide.md
- packages/checkbox-group/src/LionCheckboxIndeterminate.js
- packages/checkbox-group/test/lion-checkbox-indeterminate.test.js
- yarn.lock
The [other PR](https://github.com/ing-bank/lion/pull/1679) from @DannyMoerkerke has 7 commits that needed to be squashed, rebased and a changeset had to be added.
However, locally, my history would be quite different on his branch so something was off there history-wise it seemed.. so I just cherry-picked his stuff on this new branch to quickly fix it. 
Has my approval, tests & code looks great!
@gerjanvangeest tagging you for approval
> fix(checkbox-group): indeterminate checkbox respects disabled states

- .changeset/nervous-cobras-know.md
- packages/accordion/package.json
- packages/accordion/src/LionAccordion.js
- packages/collapsible/package.json
- packages/collapsible/src/LionCollapsible.js
- packages/form-core/package.json
- packages/form-core/src/FormControlMixin.js
- packages/helpers/index.js
- packages/helpers/uuid/uuid.js
- packages/listbox/package.json
- packages/listbox/src/ListboxMixin.js
- packages/tabs/package.json
- packages/tabs/src/LionTabs.js
- added UUID method in the "helpers" package
- removed separate implementations for UUID from all the packages
- added imports for UUID in respective packages
> feat(helpers): add uuid method

- docs/fundamentals/tools/ajax/overview.md
1. Add documentation for the various initialization and cache configuration options in the ajax library
> docs(ajax): update the config and cache options in overview.md

- .changeset/real-actors-drum.md
- packages/form-integrations/test/form-integrations.test.js
- packages/input-tel-dropdown/src/LionInputTelDropdown.js
- packages/input-tel-dropdown/test-suites/LionInputTelDropdown.suite.js
1. sync value of dropdown on init if input has no value
> fix(input-tel-dropdown): syncs value of dropdown on init if input has no value

- .changeset/fast-grapes-care.md
- packages/input-tel-dropdown/src/LionInputTelDropdown.js
- packages/input-tel-dropdown/test-suites/LionInputTelDropdown.suite.js
1. fix edge cases onDropdownValueChanged
> fix(input-tel-dropdown): fix edge cases onDropdownValueChanged

- CONTRIBUTING.md
> chore: update our contributing guidelines

- .changeset/eighty-hats-bake.md
- packages/overlays/src/globalOverlaysStyle.js
> fix(overlays): change opacity to filter to fix chromium bug

- .github/workflows/verify.yml
> chore: verify using node 16

- docs/fundamentals/systems/overlays/use-cases.md
> Fix overlay docs: correct events names

- .changeset/sixty-donkeys-tell.md
- docs/components/progress-indicator/assets/my-determinate-progress-bar.js
- docs/components/progress-indicator/assets/my-indeterminate-progress-spinner.js
- docs/components/progress-indicator/examples.md
- docs/components/progress-indicator/overview.md
- packages/progress-indicator/package.json
- packages/progress-indicator/src/LionProgressIndicator.js
- packages/progress-indicator/test/lion-progress-indicator.test.js
1. Added progress bar support in `progress-indicator`
> feat(progress-indicator): add support for progress bar

- .github/CODEOWNERS
1. Added @athirlwall, @dereli, and myself as code owners as requested by @narzac
> chore: add some ing people to codeowners

- .github/CODEOWNERS
> chore: add danny as code owner

- packages/ajax/src/Ajax.js
> fix: relax content type restriction of json response

- .changeset/olive-rats-mate.md
> ci: changeset

- packages/ui/components/core/test/SlotMixin.test.js
proper tests for SlotMixin when polyfill is loaded
> chore: SlotMixin scoped els test fix

- .changeset/lucky-windows-bathe.md
- packages/ui/components/localize/types/LocalizeMixinTypes.ts
- packages/ui/exports/core.js
- packages/ui/exports/form-core.js
- packages/ui/exports/input-tel-dropdown.js
- packages/ui/exports/input-tel.js
- packages/ui/exports/localize.js
- packages/ui/exports/overlays.js
> fix(ui): export types that are useful for subclassers

- .changeset/four-news-float.md
- docs/fundamentals/systems/core/SlotMixin.md
- packages/ui/components/form-core/test-suites/ValidateMixin.suite.js
- packages/ui/components/input-tel-dropdown/src/LionInputTelDropdown.js
- packages/ui/components/input-tel/src/LionInputTel.js
Polish SlotMixin docs and LionInputTel(Dropdown)
> fix(lion-input-tel): polish/cleanup input-tel(-dropdown)

- .changeset/cold-laws-check.md
- packages/ui/components/core/src/SlotMixin.js
- packages/ui/components/core/test/SlotMixin.test.js
> fix(core): SlotMixin: conditional slots should not break init loop

- .changeset/long-actors-clap.md
- .changeset/thin-pigs-cover.md
- packages/ui/components/icon/src/icons.js
- packages/ui/components/localize/src/singleton.js
- packages/ui/components/localize/test/localize.test.js
- packages/ui/components/overlays/src/singleton.js
- packages/ui/exports/icon-no-side-effects.js
- packages/ui/exports/icon.js
- packages/ui/exports/localize-no-side-effects.js
- packages/ui/exports/localize.js
- packages/ui/exports/overlays-no-side-effects.js
- packages/ui/exports/overlays.js
> fix(ui): use correct names for singleton registrations

- .changeset/great-seals-attack.md
- packages/ui/components/dialog/src/LionDialog.js
- packages/ui/components/dialog/test/lion-dialog.test.js
- packages/ui/components/input-datepicker/src/LionInputDatepicker.js
- packages/ui/components/localize/src/singleton.js
- packages/ui/components/overlays/src/OverlayController.js
- packages/ui/components/overlays/src/configurations/visibility-trigger-partials/withClickInteraction.js
- packages/ui/components/overlays/src/configurations/visibility-trigger-partials/withHoverInteraction.js
- packages/ui/components/overlays/src/configurations/withBottomSheetConfig.js
- packages/ui/components/overlays/src/configurations/withDropdownConfig.js
- packages/ui/components/overlays/src/configurations/withModalDialogConfig.js
- packages/ui/components/overlays/src/configurations/withTooltipConfig.js
- packages/ui/components/overlays/types/OverlayConfig.ts
- packages/ui/components/tooltip/src/LionTooltip.js
- packages/ui/components/tooltip/test/lion-tooltip.test.js
- packages/ui/exports/overlays.js
PR that prevents all components that use ing-tooltip inside from freezing (plus some cleanups)
> fix(ui): prevent infinite tooltip loops

- .changeset/fair-actors-decide.md
- packages/ui/components/overlays/src/OverlayController.js
- packages/ui/components/overlays/test/OverlayController.test.js
- packages/ui/components/select-rich/src/LionSelectRich.js
- packages/ui/components/tooltip/src/LionTooltip.js
- packages/ui/components/tooltip/test/lion-tooltip.test.js
> fix(ui): overlay fixes (responsive backdrop/select-rich/tooltip)

- docs/components/select-rich/use-cases.md
- packages/ui/components/overlays/src/OverlayController.js
- packages/ui/components/select-rich/src/LionSelectRich.js
> chore: small cleanup and RichSelect demo fix

- .changeset/chilly-taxis-sin.md
- packages/ui/components/listbox/src/ListboxMixin.js
- packages/ui/components/listbox/types/ListboxMixinTypes.ts
- packages/ui/components/select-rich/src/LionSelectRich.js
- packages/ui/components/select-rich/test/lion-select-rich.test.js
> fix(select-rich): solve case of having singleOption and hasNoDefaultSelected

- .changeset/wild-clocks-call.md
- packages/ui/components/input-tel-dropdown/src/LionInputTelDropdown.js
- packages/ui/components/input-tel/translations/bg.js
- packages/ui/components/input-tel/translations/cs.js
- packages/ui/components/input-tel/translations/de.js
- packages/ui/components/input-tel/translations/en.js
- packages/ui/components/input-tel/translations/es.js
- packages/ui/components/input-tel/translations/fr.js
- packages/ui/components/input-tel/translations/hu.js
- packages/ui/components/input-tel/translations/it.js
- packages/ui/components/input-tel/translations/nl.js
- packages/ui/components/input-tel/translations/pl.js
- packages/ui/components/input-tel/translations/ro.js
- packages/ui/components/input-tel/translations/ru.js
- packages/ui/components/input-tel/translations/sk.js
- packages/ui/components/input-tel/translations/uk.js
- packages/ui/components/input-tel/translations/zh.js
> fix(input-tel-dropddown): add translations for 'All countries' and 'Suggested countries' labels

- .changeset/green-elephants-jog.md
- docs/fundamentals/systems/overlays/configuration.md
> fix: overlay docs error: 'return' outside of function

- .changeset/blue-flowers-care.md
- .changeset/honest-ghosts-dance.md
- packages/ui/components/localize/types/LocalizeMixinTypes.ts
> Release `@lion/ui` beta 0.1.0

- .changeset/seven-hotels-reflect.md
- packages/ui/components/localize/src/number/parseNumber.js
- packages/ui/components/localize/test/number/parseNumber.test.js
1. fix https://github.com/ing-bank/lion/issues/1890
> fix(localize): parse negative numbers correctly

- packages/ui/README.md
1. Added link to root level README for lion/ui package
> chore: add README for lion/ui package

- .changeset/eighty-dogs-travel.md
- packages/ui/components/listbox/src/ListboxMixin.js
- packages/ui/components/listbox/test-suites/ListboxMixin.suite.js
> fix(listbox): allow use of arrow keys when focus is not on listbox

- .changeset/silver-lizards-repeat.md
- packages/ui/components/combobox/src/LionCombobox.js
- packages/ui/components/combobox/test/lion-combobox.test.js
> fix(combobox): update option list after clear

- docs/blog/introducing-lion-ui.md
1. wrote a blogpost on @lion/ui
It has no image yet.
> chore: wrote a blogpost on @lion/ui

- docs/fundamentals/index.md
> Added missing word: "Systems"

- docs/components/select-rich/overview.md
- docs/components/select-rich/use-cases.md
fix: https://github.com/ing-bank/lion/issues/1483
> chore(select-rich): update docs

- .changeset/orange-eels-pay.md
- docs/components/input-amount/use-cases.md
- package-lock.json
- package.json
- packages/ui/components/input-amount/src/LionInputAmount.js
- packages/ui/components/input-amount/test/lion-input-amount.test.js
Added a _currencyDisplayNodeSlot variable to the LionInputAmount component to be able to customize the slot to put the currency label.
> feat(@lion/ui): add _currencyDisplayNodeSlot to LionInputAmount

- .changeset/slot-mixin-reactivity-align.md
- docs/fundamentals/systems/core/SlotMixin.md
- packages/ui/components/core/src/SlotMixin.js
- packages/ui/components/core/test/SlotMixin.test.js
- packages/ui/components/core/types/SlotMixinTypes.ts
- packages/ui/components/input-tel-dropdown/src/LionInputTelDropdown.js
> chore: SlotRerenderObject aligned with reactive cycle (docs + changelog)

- .changeset/small-cows-tease.md
- docs/guides/how-to/get-started.md
- package-lock.json
- package.json
- packages/ui/.gitignore
- packages/ui/custom-elements-manifest.config.js
> feat: expose vscode custom-data

- .changeset/spotty-pumpkins-matter.md
- packages/ui/components/combobox/src/LionCombobox.js
- packages/ui/components/combobox/test/lion-combobox.test.js
- packages/ui/components/listbox/src/ListboxMixin.js
- packages/ui/components/listbox/test-suites/ListboxMixin.suite.js
> fix(combobox): submit form on [Enter]

- .changeset/neat-poets-hope.md
- docs/components/checkbox-group/overview.md
- docs/components/checkbox-group/use-cases.md
- packages/ui/components/checkbox-group/src/LionCheckboxIndeterminate.js
- packages/ui/components/checkbox-group/test-suites/CheckboxIndeterminate.suite.js
- packages/ui/components/checkbox-group/test/lion-checkbox-indeterminate-integrations.test.js
- packages/ui/exports/checkbox-group-test-suites.js
1. Create test-suite for CheckboxIndeterminate
2. Replaced slot="checkbox" to a normal slot
> chore: add checkboxIndeterminate test suite

- .changeset/plenty-taxis-attend.md
- packages/ui/components/localize/types/LocalizeMixinTypes.ts
> fix(localize): fix type of localizeNameSpaces

- .github/CODEOWNERS
> chore: add code-owner

- docs/fundamentals/rationales/accessibility.md
Enhanced documentation with slides about:
- latest development wrt cross-root-aria proposals
- step-by-step explanation of how we handle cross-root-aria challenges today
> chore: cross-root-aria docs

- src/pages/[top]/[...slug].astro
- src/pages/components/[component].astro
- src/utils/remark-plugings/copyMdjsStories/copyMdjsStories.js
> chore: fix dynamic imports

- .changeset/big-chicken-listen.md
- docs/fundamentals/systems/form/validate.md
- packages/ui/components/form-core/test-suites/ValidateMixin.suite.js
Updated documentation for "Form -> Validation" and added a related unit test
> fix: update documentation and unit tests for validation

- .changeset/soft-melons-kiss.md
> chore: correct changelog singleton-manager

- docs/fundamentals/tools/ajax/overview.md
1. add some proper documentation for ajax package
> docs: add proper ajax documentation

- src/pages/[top]/[...slug].astro
- src/utils/pages/render-entries.ts
> chore: create a common file for rendering [...slug] and [component]

- docs/fundamentals/systems/overlays/assets/demo-el-using-overlaymixin.mjs
fixed broken overlay system demos
> chore: fix broken overlay system demos

- .changeset/sixty-peaches-pump.md
- package-lock.json
- package.json
- packages-node/providence-analytics/package.json
> fix: web-dev-server update

- .changeset/plenty-turtles-remember.md
- .changeset/popular-schools-grow.md
- docs/components/form/overview.md
- docs/components/form/use-cases.md
- docs/fundamentals/systems/form/use-cases.md
- packages/ui/components/form/src/LionForm.js
- packages/ui/components/form/test/lion-form.test.js
> feat(form): set focus to the first erroneous form element on submit

- .changeset/fresh-moles-reflect.md
- packages/ui/components/form-core/test-suites/FormRegistrationMixins.suite.js
- packages/ui/components/localize/src/LocalizeMixin.js
> fix: migrate deprecated `performUpdate` api to `scheduleUpdate`

- docs/fundamentals/tools/ajax/overview.md
Added explanation on the new functionality
> doc: add missing explanation of the new option in @lion/ajax

- .changeset/fifty-ants-end.md
- package-lock.json
- package.json
- packages/ui/components/textarea/src/LionTextarea.js
- packages/ui/components/textarea/test/lion-textarea.test.js
- packages/ui/package.json
> fix(textarea): fix box-sizing inside tests to make it work cross browser

- docs/fundamentals/systems/form/styling.md
> chore: add data-label to doc examples with explanation

- docs/guides/principles/scoped-elements.md
> chore: update scopedElementsMixin documentation

- .changeset/fifty-ants-end.md
- .changeset/forty-seas-study.md
- .changeset/funny-numbers-prove.md
- .changeset/rare-crabs-compare.md
- .changeset/seven-beans-give.md
- docs/fundamentals/systems/core/SlotMixin.md
- packages/ui/CHANGELOG.md
- packages/ui/components/core/src/SlotMixin.js
- packages/ui/components/core/test/SlotMixin.test.js
- packages/ui/components/core/types/SlotMixinTypes.ts
- packages/ui/package.json
> Lit3 alpha  slot mixin plus scoped el backw compat

- .changeset/fuzzy-badgers-glow.md
- packages-node/providence-analytics/src/program/utils/resolve-import-path.js
> fix(providence-analytics): allow compatibility with node 16

- package-lock.json
- package.json
1. Removed unused `whatwg-fetch` dependency.
> Remove unused `whatwg-fetch` dependency

- .changeset/wise-lemons-hug.md
- docs/components/input-tel-dropdown/src/intl-input-tel-dropdown.js
- package-lock.json
- package.json
- packages/ui/components/input-tel-dropdown/src/LionInputTelDropdown.js
- packages/ui/components/input-tel-dropdown/test-suites/LionInputTelDropdown.suite.js
- packages/ui/components/input-tel-dropdown/types/index.ts
Instead of using setTimeout to focus the input field, let's use the `elementToFocusAfterHide` property
> fix: optimize the way we focus the input field for LionInputTelDropdown

- .github/workflows/release.yml
1. revert https://github.com/ing-bank/lion/pull/2268
> chore: revert release.yml

- docs/fundamentals/systems/form/assets/h-output.js
- package-lock.json
- package.json
- packages/ui/components/helpers/src/SbActionLogger.js
1. Updated ESLint
2. ~Fixed~ Ignore any violations that come up
~This is waiting for #2253 to land before I'll take it out of draft mode.~
> Update eslint proper

- .github/CODEOWNERS
> chore: change account in codeowners

- packages/ui/components/overlays/src/OverlayMixin.js
> chore: add description for opened to the jsdoc

- .github/CODEOWNERS
1. removed `@tkgroot`, added `@ryubro`
> Chore: update the list to reflect the current team

- package.json
> chore: tag lit2 releases to prevent them being latest

- packages/ui/components/button/test-suites/LionButton.suite.js
> Tests: Missing closing tag in button test suite

- README.md
- scripts/rewrite-links.js
1. make the readme logo absolute path
👉 Small change to fix the broken link on [npmjs.org](https://www.npmjs.com/package/@lion/ui)
[![Screenshot 2024-08-21 at 10 34 00](https://github.com/user-attachments/assets/8c47b257-cd10-460c-af31-da38078baa7a)](https://www.npmjs.com/package/@lion/ui)
> chore: make readme logo absolute path

- .changeset/brave-plums-drum.md
- docs/components/combobox/use-cases.md
- packages/ui/components/combobox/src/LionCombobox.js
- packages/ui/components/combobox/test/lion-combobox.test.js
> fix(combobox): when multiple choice reset all listbox options on select

- .changeset/avoid-growing-margin.md
- avoid-growing-margin.md
- packages/ui/components/overlays/src/OverlayController.js
- packages/ui/components/overlays/test/OverlayController.test.js
1. fix the _keepBodySize to return instantly if controller uses local placement
2. wrote a test to confirm this
> Fix/overlay growing margin, issue 2323 

- .gitignore
- .vscode/extensions.json
- .vscode/settings.json
Align best DX for all developers and make sure editor output is aligned with ci output
> share vscode settings

- README.md
- docs/blog/extending-documentation.md
- packages/ui/components/form-core/src/registration/FormRegisteringMixin.js
- packages/ui/components/form-core/types/registration/FormRegisteringMixinTypes.ts
- packages/ui/components/listbox/test-suites/ListboxMixin.suite.js
- packages/ui/components/overlays/src/OverlayController.js
> chore: update portal url

- docs/components/form/use-cases.md
> chore: enhance form documentation

- .eleventyignore
- patches/@rocket+cli+0.10.2.patch
> chore: better Rocket DX (no endless refresh loops, but manual refresh)

- .changeset/tasty-fishes-occur.md
- packages/ui/components/core/src/DisabledMixin.js
- packages/ui/components/core/test/DisabledMixin.test.js
closes https://github.com/ing-bank/lion/issues/2330
closes https://github.com/ing-bank/lion/pull/2354
> chore(core): prevent click on disabled elements

- packages/ui/components/input-stepper/src/LionInputStepper.js
> chore(input-stepper): remove valueTextMapping attribute

- .changeset/blue-glasses-invite.md
- .changeset/healthy-starfishes-impress.md
- packages-node/providence-analytics/package.json
- packages-node/providence-analytics/src/program/core/Analyzer.js
- packages-node/providence-analytics/src/program/core/QueryService.js
- packages-node/providence-analytics/src/program/utils/memoize.js
- packages-node/providence-analytics/test-helpers/mock-project-helpers.js
- packages-node/providence-analytics/test-node/program/utils/memoize.test.js
> feat(providence): lfu and lru cache strategies for memoize

- .changeset/perfect-pans-cover.md
- package-lock.json
- packages/ui/components/input-datepicker/translations/es.js
1. Replace a spanish literal for openDatepickerLabel related to a11y in order to be more clear and concise
> Update spanish translation for openDatePickerLabel

- .changeset/poor-ligers-punch.md
- .changeset/proud-pugs-think.md
> chore: add changelog input-amount

- .changeset/bright-snakes-smash.md
- .changeset/twenty-planes-push.md
- packages/ui/components/form-core/src/FormatMixin.js
- packages/ui/components/form-core/test-suites/FormatMixin.suite.js
- packages/ui/components/form-core/types/FormatMixinTypes.ts
- packages/ui/components/input-amount/test/lion-input-amount.test.js
- packages/ui/components/input-amount/test/parsers.test.js
- packages/ui/components/localize/src/number/parseNumber.js
- packages/ui/components/localize/test/number/parseNumber.test.js
- packages/ui/components/localize/types/LocalizeMixinTypes.ts
> fix(ui): [form-core] enhance formatter and parser meta

- .changeset/nine-keys-matter.md
- packages/ui/components/calendar/src/LionCalendar.js
- packages/ui/components/calendar/test/lion-calendar.test.js
- packages/ui/components/calendar/translations/bg.js
- packages/ui/components/calendar/translations/cs.js
- packages/ui/components/calendar/translations/de.js
- packages/ui/components/calendar/translations/en.js
- packages/ui/components/calendar/translations/es.js
- packages/ui/components/calendar/translations/fr.js
- packages/ui/components/calendar/translations/hu.js
- packages/ui/components/calendar/translations/it.js
- packages/ui/components/calendar/translations/nl.js
- packages/ui/components/calendar/translations/pl.js
- packages/ui/components/calendar/translations/ro.js
- packages/ui/components/calendar/translations/ru.js
- packages/ui/components/calendar/translations/sk.js
- packages/ui/components/calendar/translations/uk.js
- packages/ui/components/calendar/translations/zh.js
> fix(calendar): add translations for disabled dates

- .changeset/selfish-wasps-switch.md
- packages-node/providence-analytics/src/program/utils/optimised-glob.js
> fix(providence): [optimised-glob] use Array.concat for memory efficiency

- .changeset/red-monkeys-retire.md
> chore: make sure we do not release a new minor

- .changeset/swift-tigers-joke.md
- package-lock.json
- packages-node/providence-analytics/package.json
- packages-node/providence-analytics/src/program/analyzers/find-customelements.js
- packages-node/providence-analytics/src/program/analyzers/find-exports.js
- packages-node/providence-analytics/src/program/analyzers/find-imports.js
- packages-node/providence-analytics/src/program/core/AstService.js
- packages-node/providence-analytics/src/program/utils/get-source-code-fragment-of-declaration.js
- packages-node/providence-analytics/src/program/utils/oxc-traverse.js
- packages-node/providence-analytics/src/program/utils/track-down-identifier.js
- packages-node/providence-analytics/test-node/program/analyzers/find-exports.test.js
- packages-node/providence-analytics/test-node/program/analyzers/find-imports.test.js
- packages-node/providence-analytics/test-node/program/utils/oxc-traverse.test.js
- packages-node/providence-analytics/types/utils/index.d.ts
> fix(providence): pin oxc-parser; fix default edge cases

- packages/ui/scripts/cem.js
> chore: add sorting to api tables

- .changeset/shy-foxes-shop.md
> chore: prepare documentation for cross-compatibility rocket and astro

- .changeset/purple-ties-complain.md
- packages-node/remark-extend/src/remarkExtend.js
- packages-node/remark-extend/test-node/fixtures/three-sections-red-with-frontmatter.md
- packages-node/remark-extend/test-node/remark-extend.test.mjs
Fixes the problem described here: https://github.com/ing-bank/lion/pull/2499 
Closes https://github.com/ing-bank/lion/pull/2499
> fix(remark-extend): support md files with frontmatter

- .github/workflows/release.yml
- .github/workflows/verify-pr.yml
- package-lock.json
- package.json
> chore: wireit actions v2

- .changeset/little-sloths-punch.md
- package-lock.json
- package.json
- packages-node/providence-analytics/package.json
- packages/ui/components/form-core/src/FormControlMixin.js
- packages/ui/components/form-core/test/FormControlMixin.test.js
> chore: update to @lit/reactive-element 2.1.0

- .changeset/silver-eyes-count.md
- packages/ui/components/input-stepper/src/LionInputStepper.js
1. Follow up of: https://github.com/ing-bank/lion/pull/2511
> chore(input-stepper): small edit after previous input-stepper fix

- .changeset/modern-terms-fix.md
- packages/ui/components/input-file/src/LionInputFile.js
- packages/ui/components/input-file/test/lion-input-file.test.js
> fix(input-file): set buttonLabel initially

- .changeset/strange-islands-judge.md
- packages/ui/components/input-amount-dropdown/src/LionInputAmountDropdown.js
- packages/ui/components/input-amount-dropdown/test-suites/LionInputAmountDropdown.suite.js
- packages/ui/components/input-amount-dropdown/test/LionInputAmountDropdown.test.js
- packages/ui/components/input-amount-dropdown/types/index.ts
- packages/ui/exports/types/input-amount-dropdown.ts
1. exported missing types
2. removed an unnecessary opinionated styling which annoyed subclassers
> amount-dropdown small fixes

- src/utils/remark-plugings/remark-process-demos.mjs
1. Fixed hardcoded name of the root directory because in the build its different
> Fixed root directory

- src/pages/components/[...path].astro
- src/pages/fundamentals/[...path].astro
- src/pages/guides/[...path].astro
1. Changed "lit" syntax to "astro" syntax to fix demo loading
> fix: fixed demos
